// Auto-generated by scripts/updateData.js — last update: 2026-04-29
// CZ: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 4096,
  "multiItemOrders": 685,
  "pairs": [
    {
      "productA": "Skinners 2.0 Comfort",
      "productB": "Skinners KIDS 2.0",
      "count": 12,
      "pct": 0.29
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "count": 12,
      "pct": 0.29
    },
    {
      "productA": "Skinners 2.0 Comfort",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 11,
      "pct": 0.27
    },
    {
      "productA": "Skinners KIDS 2.0",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 10,
      "pct": 0.24
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "Skinners 2.0 Comfort",
      "count": 10,
      "pct": 0.24
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "KS Lite Short - nízké běžecké ponožky",
      "count": 9,
      "pct": 0.22
    },
    {
      "productA": "KS 600/Speed",
      "productB": "KS CoolMax - chladivé běžecké ponožky",
      "count": 9,
      "pct": 0.22
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "Čisticí kartáčky na barefoot a sportovní obuv | Nikwax",
      "count": 7,
      "pct": 0.17
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "Čističe na barefoot a sportovní obuv | Nikwax",
      "count": 7,
      "pct": 0.17
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "Sportovní ponožky KS QGO - běh, chůze, cyklistika",
      "count": 6,
      "pct": 0.15
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "Sportovní ponožky KS QGO - běh, chůze, cyklistika",
      "count": 6,
      "pct": 0.15
    },
    {
      "productA": "Turistické ponožky KS Merib MERINO - chladné počasí",
      "productB": "XERO Alpine dámská zimní barefoot obuv",
      "count": 6,
      "pct": 0.15
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "VÝPRODEJ XERO Alpine dámská zimní barefoot obuv",
      "count": 6,
      "pct": 0.15
    },
    {
      "productA": "GRIZLY Arašídový krém s mléčnou čokoládou v tubě 75 g",
      "productB": "Skinners 2.0 Comfort",
      "count": 5,
      "pct": 0.12
    },
    {
      "productA": "GRIZLY RAW Bar acai-kešu-konopné semínko 55 g",
      "productB": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "count": 5,
      "pct": 0.12
    },
    {
      "productA": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 5,
      "pct": 0.12
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "Skinners KIDS 2.0",
      "count": 5,
      "pct": 0.12
    },
    {
      "productA": "Skinners 2.0 Comfort",
      "productB": "Sportovní ponožky KS QGO",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "productB": "Skinners KIDS 2.0",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "KS Lite Short - nízké sportovní ponožky",
      "productB": "Skinners KIDS 2.0",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "GRIZLY Arašídový krém 500g",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "Běžecké sportovní ponožky KS RUN-2EX",
      "productB": "Sportovní ponožky KS QGO - běh, chůze, cyklistika",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "productB": "KS Lite Short - nízké běžecké ponožky",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "XERO Scrambler Low Woman - dámské trailové a trekové barefoot boty",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "KS 600/Speed",
      "productB": "KS Lite Short - nízké běžecké ponožky",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "KS 600/Speed",
      "productB": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "VÝPRODEJ XERO Ridgeway pánské voděodolné boty",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "KS Lite Short - nízké sportovní ponožky",
      "count": 4,
      "pct": 0.1
    },
    {
      "productA": "COMPRESSPORT běžecké podkolenky FULL SOCKS RUN",
      "productB": "COMPRESSPORT kompresní návleky R2 3.0",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "GRIZLY RAW Bar acai-kešu-konopné semínko 55 g",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS CoolMax",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Skinners KIDS 2.0",
      "productB": "Sušené maso Beef Jerky GymBeam Original 50g",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Běžecké sportovní ponožky KS RUN-2EX",
      "productB": "KS Lite Short - nízké běžecké ponožky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "Skinners 2.0 Comfort",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Skinners 2.0 Comfort",
      "productB": "Sportovní ponožky KS QGO - běh, chůze, cyklistika",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Běžecké sportovní ponožky KS RUN-2EX",
      "productB": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "KS Lite Short - nízké běžecké ponožky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "Xero Aqua X Sport pánské obojživelné trailovky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "COMPRESSPORT Běžecké ponožky  PRS V4.0 RUN LOW",
      "productB": "KS CoolMax - chladivé běžecké ponožky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Běžecké sportovní ponožky KS RUN-2EX",
      "productB": "KS CoolMax - chladivé běžecké ponožky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "Xero Prio NEO W - dámská mulitsportovní obuv",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "Xero Wynn – dámské retro barefoot tenisky pro maximální volnost pohybu",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "VÝPRODEJ Xero Shoes Z-Trek barefoot sandály – dámské",
      "productB": "Xero Shoes Z-Trek barefoot sandály – pánské",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "VÝPRODEJ Xero Prio dámské barefoot boty – běh, trénink, každodenní nošení",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS Hike MERINO - turistické ponožky celoroční",
      "productB": "KS Lite Short - nízké běžecké ponožky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Merrell Vapor Glove 6 - dámská sportovní barefoot obuv",
      "productB": "Tričko vel M W za nákup zdarma",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Tričko Pánské Barefoot Concept Store Třebíč",
      "productB": "XERO Nexus Knit MEN - pánské sportovní barefoot tenisky pro volný čas",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Skinners 2.0 Comfort",
      "productB": "Tričko Pánské Barefoot Concept Store Třebíč",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Tričko Dámské Barefoot Concept Store Třebíč",
      "productB": "VÝPRODEJ XERO Nexus Knit WOMEN - dámské sportovní barefoot tenisky pro volný čas",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "productB": "Turistické ponožky KS Merib MERINO - chladné počasí",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "VÝPRODEJ Xero Shoes Denver Leather pánské",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Be Lenka Synergy Fleece UNISEX",
      "productB": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "VÝPRODEJ XERO Ridgeway dámské voděodolné boty",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "XERO Alpine dámská zimní barefoot obuv",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "VÝPRODEJ Xero Gracie – lehké dámské barefoot holínky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Impregnace na barefoot a sportovní obuv | Nikwax",
      "productB": "KS CoolMax - chladivé běžecké ponožky",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "VÝPRODEJ Xero Prio dámské barefoot boty – běh, trénink, každodenní nošení",
      "count": 3,
      "pct": 0.07
    },
    {
      "productA": "Med květový balený 10x10g",
      "productB": "Sportovní ponožky KS QGO",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Merrell Vapor Glove 6 - dámská sportovní barefoot obuv",
      "productB": "Xero HFS - dámské běžecké boty",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém slaný karamel v tubě 75 g",
      "productB": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém slaný karamel v tubě 75 g",
      "productB": "Skinners 2.0 Comfort",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "productB": "Skinners 2.0 Comfort",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "GRIZLY Datle sušené BIO 1000 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Datle sušené BIO 1000 g",
      "productB": "Skinners 2.0 Comfort",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Skinners 2.0 Comfort",
      "productB": "SmellWell polštářky ACTIVE",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "Nominal Cereální kaše Sport 60 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Skinners KIDS 2.0 LIMITED EDITION",
      "productB": "Sušené maso Beef Jerky GymBeam Original 50g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY RAW Bar kokos-kešu-kakao 55 g",
      "productB": "GRIZLY RAW Bar mango-makadam-černý rybíz 55 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY RAW Bar kokos-kešu-kakao 55 g",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Med květový balený 10x10g",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém slaný karamel v tubě 75 g",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Nominal Cereální kaše semínková 300 g",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Nominal Cereální kaše čiroková 300 g",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Nominal Cereální kaše rýžová 300 g",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "GRIZLY Arašídový krém v tubě 75 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém v tubě 75 g",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém slaný karamel v tubě 75 g",
      "productB": "Skinners KIDS 2.0 LIMITED EDITION",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "productB": "Turistické ponožky KS Merib MERINO",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Ovonex ionilyte hypotonický iontový koncentrát",
      "productB": "Turistické ponožky KS Merib MERINO",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Lískooříškový krém v tubě 75 g",
      "productB": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Lískooříškový krém v tubě 75 g",
      "productB": "KS CoolMax - chladivé běžecké ponožky",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "Xero Z-Trail EV pánské turistické sandály",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "GRIZLY Lískooříškový krém v tubě 75 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Lískooříškový krém v tubě 75 g",
      "productB": "Skinners 2.0 Comfort",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Skinners KIDS 2.0",
      "productB": "Xero Prio dětské",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "XERO Nexus Knit WOMEN - dámské sportovní barefoot tenisky pro volný čas",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Sportovní ponožky KS QGO - běh, chůze, cyklistika",
      "productB": "Xero Z-Trail EV pánské turistické sandály",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "Merrell Vapor Glove 6 - dámská sportovní barefoot obuv",
      "productB": "Xero Prio dětské",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "GRIZLY Arašídový krém s mléčnou čokoládou v tubě 75 g",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS CoolMax - chladivé běžecké ponožky",
      "productB": "Skinners 2.0 Comfort",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "productB": "Sportovní ponožky KS QGO - běh, chůze, cyklistika",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "XERO Nexus Knit MEN - pánské sportovní barefoot tenisky pro volný čas",
      "productB": "XERO Nexus Knit WOMEN - dámské sportovní barefoot tenisky pro volný čas",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS Cross MERINO - Běžecké ponožky vhodné i na ULTRA",
      "productB": "Xero Z-Trail EV dámské turistické barefoot sandály",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "KS Lite Short - nízké běžecké ponožky",
      "productB": "Skinners KIDS 2.0",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "GRIZLY Arašídový krém s belgickou čokoládou v tubě 75 g",
      "productB": "Xero Prio NEO W - dámská mulitsportovní obuv",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "SmellWell polštářky ACTIVE",
      "productB": "Xero Prio NEO W - dámská mulitsportovní obuv",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "SmellWell polštářky ACTIVE",
      "productB": "XERO Scrambler Low Woman - dámské trailové a trekové barefoot boty",
      "count": 2,
      "pct": 0.05
    },
    {
      "productA": "SmellWell polštářky SENSITIVE",
      "productB": "XERO Scrambler Low Woman - dámské trailové a trekové barefoot boty",
      "count": 2,
      "pct": 0.05
    }
  ]
};
