// Auto-generated by scripts/updateData.js — last update: 2026-09-17
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZProdejna: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 2,
    "totalRevenue": 1809.92,
    "totalOrders": 1,
    "avgRevenue": 904.96,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 2,
    "totalRevenue": 2388.43,
    "totalOrders": 1,
    "avgRevenue": 1194.21,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 31,
    "totalRevenue": 426.44,
    "totalOrders": 1,
    "avgRevenue": 13.76,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 31,
    "totalRevenue": 2447.11,
    "totalOrders": 1,
    "avgRevenue": 78.94,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 31,
    "totalRevenue": 5603.31,
    "totalOrders": 2,
    "avgRevenue": 180.75,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 31,
    "totalRevenue": 5074.38,
    "totalOrders": 3,
    "avgRevenue": 163.69,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 31,
    "totalRevenue": 38117.28,
    "totalOrders": 18,
    "avgRevenue": 1229.59,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 31,
    "totalRevenue": 28041.34,
    "totalOrders": 17,
    "avgRevenue": 904.56,
    "avgOrders": 0.55
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 31,
    "totalRevenue": 28632.25,
    "totalOrders": 13,
    "avgRevenue": 923.62,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 31,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 45.05,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 45,
    "totalRevenue": 2437.19,
    "totalOrders": 1,
    "avgRevenue": 54.16,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 45,
    "totalRevenue": 17571.73,
    "totalOrders": 9,
    "avgRevenue": 390.48,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 45,
    "totalRevenue": 33890.11,
    "totalOrders": 14,
    "avgRevenue": 753.11,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 45,
    "totalRevenue": 21217.37,
    "totalOrders": 12,
    "avgRevenue": 471.5,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 45,
    "totalRevenue": 13238.51,
    "totalOrders": 6,
    "avgRevenue": 294.19,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 45,
    "totalRevenue": 19724.82,
    "totalOrders": 9,
    "avgRevenue": 438.33,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 45,
    "totalRevenue": 15527.28,
    "totalOrders": 8,
    "avgRevenue": 345.05,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 45,
    "totalRevenue": 39425.14,
    "totalOrders": 24,
    "avgRevenue": 876.11,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 45,
    "totalRevenue": 16743.8,
    "totalOrders": 9,
    "avgRevenue": 372.08,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 45,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 24.78,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 45,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 57,
    "totalRevenue": 17821.48,
    "totalOrders": 9,
    "avgRevenue": 312.66,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 57,
    "totalRevenue": 27478.71,
    "totalOrders": 14,
    "avgRevenue": 482.08,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 57,
    "totalRevenue": 19866.63,
    "totalOrders": 11,
    "avgRevenue": 348.54,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 57,
    "totalRevenue": 11938.86,
    "totalOrders": 6,
    "avgRevenue": 209.45,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 57,
    "totalRevenue": 31786.3,
    "totalOrders": 15,
    "avgRevenue": 557.65,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 57,
    "totalRevenue": 55178.71,
    "totalOrders": 23,
    "avgRevenue": 968.05,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 57,
    "totalRevenue": 44335.74,
    "totalOrders": 21,
    "avgRevenue": 777.82,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 57,
    "totalRevenue": 43351.96,
    "totalOrders": 20,
    "avgRevenue": 760.56,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 57,
    "totalRevenue": 28801.67,
    "totalOrders": 11,
    "avgRevenue": 505.29,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 57,
    "totalRevenue": 2850.41,
    "totalOrders": 1,
    "avgRevenue": 50.01,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 57,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 47,
    "totalRevenue": 12973.55,
    "totalOrders": 6,
    "avgRevenue": 276.03,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 47,
    "totalRevenue": 34074.4,
    "totalOrders": 15,
    "avgRevenue": 724.99,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 47,
    "totalRevenue": 28133.57,
    "totalOrders": 10,
    "avgRevenue": 598.59,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 47,
    "totalRevenue": 3803.37,
    "totalOrders": 3,
    "avgRevenue": 80.92,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 47,
    "totalRevenue": 30023.98,
    "totalOrders": 13,
    "avgRevenue": 638.81,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 47,
    "totalRevenue": 20541.34,
    "totalOrders": 10,
    "avgRevenue": 437.05,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 47,
    "totalRevenue": 44094.25,
    "totalOrders": 20,
    "avgRevenue": 938.18,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 47,
    "totalRevenue": 2594.21,
    "totalOrders": 2,
    "avgRevenue": 55.2,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 54,
    "totalRevenue": 11415.7,
    "totalOrders": 7,
    "avgRevenue": 211.4,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 54,
    "totalRevenue": 36679.41,
    "totalOrders": 16,
    "avgRevenue": 679.25,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 54,
    "totalRevenue": 28651.85,
    "totalOrders": 13,
    "avgRevenue": 530.59,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 54,
    "totalRevenue": 14781.83,
    "totalOrders": 6,
    "avgRevenue": 273.74,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 54,
    "totalRevenue": 38377.77,
    "totalOrders": 18,
    "avgRevenue": 710.7,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 54,
    "totalRevenue": 31151.25,
    "totalOrders": 11,
    "avgRevenue": 576.88,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 54,
    "totalRevenue": 50081.84,
    "totalOrders": 24,
    "avgRevenue": 927.44,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 54,
    "totalRevenue": 35376.87,
    "totalOrders": 19,
    "avgRevenue": 655.13,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 54,
    "totalRevenue": 14684.31,
    "totalOrders": 8,
    "avgRevenue": 271.93,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 2075.21,
    "totalOrders": 1,
    "avgRevenue": 518.8,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 2040.5,
    "totalOrders": 2,
    "avgRevenue": 510.13,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 1479.34,
    "totalOrders": 1,
    "avgRevenue": 369.84,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  }
];
