// Auto-generated by scripts/updateData.js — last update: 2026-09-12
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZProdejna: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 2,
    "totalRevenue": 1809.92,
    "totalOrders": 1,
    "avgRevenue": 904.96,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 2,
    "totalRevenue": 2388.43,
    "totalOrders": 1,
    "avgRevenue": 1194.21,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 30,
    "totalRevenue": 426.44,
    "totalOrders": 1,
    "avgRevenue": 14.21,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 30,
    "totalRevenue": 2447.11,
    "totalOrders": 1,
    "avgRevenue": 81.57,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 30,
    "totalRevenue": 2305.79,
    "totalOrders": 1,
    "avgRevenue": 76.86,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 30,
    "totalRevenue": 5074.38,
    "totalOrders": 3,
    "avgRevenue": 169.15,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 30,
    "totalRevenue": 36059.43,
    "totalOrders": 17,
    "avgRevenue": 1201.98,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 30,
    "totalRevenue": 28041.34,
    "totalOrders": 17,
    "avgRevenue": 934.71,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 30,
    "totalRevenue": 28632.25,
    "totalOrders": 13,
    "avgRevenue": 954.41,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 30,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 46.56,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 44,
    "totalRevenue": 2437.19,
    "totalOrders": 1,
    "avgRevenue": 55.39,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 44,
    "totalRevenue": 14804.96,
    "totalOrders": 8,
    "avgRevenue": 336.48,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 44,
    "totalRevenue": 33890.11,
    "totalOrders": 14,
    "avgRevenue": 770.23,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 44,
    "totalRevenue": 21217.37,
    "totalOrders": 12,
    "avgRevenue": 482.21,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 44,
    "totalRevenue": 13238.51,
    "totalOrders": 6,
    "avgRevenue": 300.88,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 44,
    "totalRevenue": 19724.82,
    "totalOrders": 9,
    "avgRevenue": 448.29,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 44,
    "totalRevenue": 15527.28,
    "totalOrders": 8,
    "avgRevenue": 352.89,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 44,
    "totalRevenue": 36378.03,
    "totalOrders": 22,
    "avgRevenue": 826.77,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 44,
    "totalRevenue": 16743.8,
    "totalOrders": 9,
    "avgRevenue": 380.54,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 44,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 25.34,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 44,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 56,
    "totalRevenue": 17821.48,
    "totalOrders": 9,
    "avgRevenue": 318.24,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 56,
    "totalRevenue": 27478.71,
    "totalOrders": 14,
    "avgRevenue": 490.69,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 56,
    "totalRevenue": 19866.63,
    "totalOrders": 11,
    "avgRevenue": 354.76,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 56,
    "totalRevenue": 11938.86,
    "totalOrders": 6,
    "avgRevenue": 213.19,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 56,
    "totalRevenue": 31786.3,
    "totalOrders": 15,
    "avgRevenue": 567.61,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 56,
    "totalRevenue": 55178.71,
    "totalOrders": 23,
    "avgRevenue": 985.33,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 56,
    "totalRevenue": 41864.67,
    "totalOrders": 20,
    "avgRevenue": 747.58,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 56,
    "totalRevenue": 43351.96,
    "totalOrders": 20,
    "avgRevenue": 774.14,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 56,
    "totalRevenue": 28801.67,
    "totalOrders": 11,
    "avgRevenue": 514.32,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 56,
    "totalRevenue": 2850.41,
    "totalOrders": 1,
    "avgRevenue": 50.9,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 56,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 46,
    "totalRevenue": 12973.55,
    "totalOrders": 6,
    "avgRevenue": 282.03,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 46,
    "totalRevenue": 31850.43,
    "totalOrders": 14,
    "avgRevenue": 692.4,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 46,
    "totalRevenue": 28133.57,
    "totalOrders": 10,
    "avgRevenue": 611.6,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 46,
    "totalRevenue": 3803.37,
    "totalOrders": 3,
    "avgRevenue": 82.68,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 46,
    "totalRevenue": 30023.98,
    "totalOrders": 13,
    "avgRevenue": 652.7,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 46,
    "totalRevenue": 20541.34,
    "totalOrders": 10,
    "avgRevenue": 446.55,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 46,
    "totalRevenue": 44094.25,
    "totalOrders": 20,
    "avgRevenue": 958.57,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 46,
    "totalRevenue": 2594.21,
    "totalOrders": 2,
    "avgRevenue": 56.4,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 54,
    "totalRevenue": 11415.7,
    "totalOrders": 7,
    "avgRevenue": 211.4,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 54,
    "totalRevenue": 36679.41,
    "totalOrders": 16,
    "avgRevenue": 679.25,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 54,
    "totalRevenue": 28651.85,
    "totalOrders": 13,
    "avgRevenue": 530.59,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 54,
    "totalRevenue": 14781.83,
    "totalOrders": 6,
    "avgRevenue": 273.74,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 54,
    "totalRevenue": 38377.77,
    "totalOrders": 18,
    "avgRevenue": 710.7,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 54,
    "totalRevenue": 31151.25,
    "totalOrders": 11,
    "avgRevenue": 576.88,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 54,
    "totalRevenue": 50081.84,
    "totalOrders": 24,
    "avgRevenue": 927.44,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 54,
    "totalRevenue": 35376.87,
    "totalOrders": 19,
    "avgRevenue": 655.13,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 54,
    "totalRevenue": 14684.31,
    "totalOrders": 8,
    "avgRevenue": 271.93,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 54,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 2075.21,
    "totalOrders": 1,
    "avgRevenue": 518.8,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 2040.5,
    "totalOrders": 2,
    "avgRevenue": 510.13,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 1479.34,
    "totalOrders": 1,
    "avgRevenue": 369.84,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  }
];
