// Auto-generated by scripts/updateData.js — last update: 2026-09-25
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZEshop: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 160,
    "totalRevenue": 8458.67,
    "totalOrders": 5,
    "avgRevenue": 52.87,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 160,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 160,
    "totalRevenue": 3214.05,
    "totalOrders": 2,
    "avgRevenue": 20.09,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 160,
    "totalRevenue": 4859.5,
    "totalOrders": 2,
    "avgRevenue": 30.37,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 160,
    "totalRevenue": 2542.15,
    "totalOrders": 3,
    "avgRevenue": 15.89,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 160,
    "totalRevenue": 4528.92,
    "totalOrders": 2,
    "avgRevenue": 28.31,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 160,
    "totalRevenue": 7702.49,
    "totalOrders": 6,
    "avgRevenue": 48.14,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 160,
    "totalRevenue": 26472.73,
    "totalOrders": 12,
    "avgRevenue": 165.45,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 160,
    "totalRevenue": 27026.47,
    "totalOrders": 13,
    "avgRevenue": 168.92,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 160,
    "totalRevenue": 56973.57,
    "totalOrders": 31,
    "avgRevenue": 356.08,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 160,
    "totalRevenue": 64286.8,
    "totalOrders": 35,
    "avgRevenue": 401.79,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 160,
    "totalRevenue": 78056.2,
    "totalOrders": 43,
    "avgRevenue": 487.85,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 160,
    "totalRevenue": 69482.69,
    "totalOrders": 32,
    "avgRevenue": 434.27,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 160,
    "totalRevenue": 90457.6,
    "totalOrders": 45,
    "avgRevenue": 565.36,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 160,
    "totalRevenue": 70627.28,
    "totalOrders": 34,
    "avgRevenue": 441.42,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 160,
    "totalRevenue": 68289.27,
    "totalOrders": 35,
    "avgRevenue": 426.81,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 160,
    "totalRevenue": 66160.34,
    "totalOrders": 31,
    "avgRevenue": 413.5,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 160,
    "totalRevenue": 82642.18,
    "totalOrders": 42,
    "avgRevenue": 516.51,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 160,
    "totalRevenue": 68083.53,
    "totalOrders": 33,
    "avgRevenue": 425.52,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 160,
    "totalRevenue": 100388.52,
    "totalOrders": 55,
    "avgRevenue": 627.43,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 160,
    "totalRevenue": 108771.94,
    "totalOrders": 56,
    "avgRevenue": 679.82,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 160,
    "totalRevenue": 108688.39,
    "totalOrders": 59,
    "avgRevenue": 679.3,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 160,
    "totalRevenue": 95374.36,
    "totalOrders": 46,
    "avgRevenue": 596.09,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 160,
    "totalRevenue": 43989.24,
    "totalOrders": 19,
    "avgRevenue": 274.93,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 162,
    "totalRevenue": 11467.78,
    "totalOrders": 6,
    "avgRevenue": 70.79,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 162,
    "totalRevenue": 6576.03,
    "totalOrders": 4,
    "avgRevenue": 40.59,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 162,
    "totalRevenue": 6958.68,
    "totalOrders": 3,
    "avgRevenue": 42.95,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 162,
    "totalRevenue": 958.68,
    "totalOrders": 1,
    "avgRevenue": 5.92,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 162,
    "totalRevenue": 2718.19,
    "totalOrders": 2,
    "avgRevenue": 16.78,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 162,
    "totalRevenue": 7932.23,
    "totalOrders": 3,
    "avgRevenue": 48.96,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 162,
    "totalRevenue": 31967.76,
    "totalOrders": 16,
    "avgRevenue": 197.33,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 162,
    "totalRevenue": 56379.32,
    "totalOrders": 30,
    "avgRevenue": 348.02,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 162,
    "totalRevenue": 70545.76,
    "totalOrders": 38,
    "avgRevenue": 435.47,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 162,
    "totalRevenue": 99124.12,
    "totalOrders": 52,
    "avgRevenue": 611.88,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 162,
    "totalRevenue": 75990.86,
    "totalOrders": 37,
    "avgRevenue": 469.08,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 162,
    "totalRevenue": 83504.48,
    "totalOrders": 45,
    "avgRevenue": 515.46,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 162,
    "totalRevenue": 102230.31,
    "totalOrders": 56,
    "avgRevenue": 631.05,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 162,
    "totalRevenue": 72782.66,
    "totalOrders": 35,
    "avgRevenue": 449.28,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 162,
    "totalRevenue": 75780.22,
    "totalOrders": 44,
    "avgRevenue": 467.78,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 162,
    "totalRevenue": 75620.14,
    "totalOrders": 45,
    "avgRevenue": 466.79,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 162,
    "totalRevenue": 77857.06,
    "totalOrders": 46,
    "avgRevenue": 480.6,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 162,
    "totalRevenue": 77293.45,
    "totalOrders": 41,
    "avgRevenue": 477.12,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 162,
    "totalRevenue": 79783.51,
    "totalOrders": 38,
    "avgRevenue": 492.49,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 162,
    "totalRevenue": 87674.4,
    "totalOrders": 43,
    "avgRevenue": 541.2,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 162,
    "totalRevenue": 117751.47,
    "totalOrders": 54,
    "avgRevenue": 726.86,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 162,
    "totalRevenue": 99590.23,
    "totalOrders": 49,
    "avgRevenue": 614.75,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 162,
    "totalRevenue": 84310.77,
    "totalOrders": 43,
    "avgRevenue": 520.44,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 162,
    "totalRevenue": 26340.6,
    "totalOrders": 16,
    "avgRevenue": 162.6,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 159,
    "totalRevenue": 20718.19,
    "totalOrders": 13,
    "avgRevenue": 130.3,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 159,
    "totalRevenue": 1954.55,
    "totalOrders": 1,
    "avgRevenue": 12.29,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 159,
    "totalRevenue": 2851.24,
    "totalOrders": 1,
    "avgRevenue": 17.93,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 159,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 159,
    "totalRevenue": 5533.88,
    "totalOrders": 2,
    "avgRevenue": 34.8,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 159,
    "totalRevenue": 4784.3,
    "totalOrders": 2,
    "avgRevenue": 30.09,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 159,
    "totalRevenue": 9047.94,
    "totalOrders": 5,
    "avgRevenue": 56.91,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 159,
    "totalRevenue": 45904.97,
    "totalOrders": 27,
    "avgRevenue": 288.71,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 159,
    "totalRevenue": 84396.74,
    "totalOrders": 41,
    "avgRevenue": 530.8,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 159,
    "totalRevenue": 95073.62,
    "totalOrders": 49,
    "avgRevenue": 597.95,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 159,
    "totalRevenue": 86585.63,
    "totalOrders": 48,
    "avgRevenue": 544.56,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 159,
    "totalRevenue": 95482.85,
    "totalOrders": 50,
    "avgRevenue": 600.52,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 159,
    "totalRevenue": 93062.12,
    "totalOrders": 47,
    "avgRevenue": 585.3,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 159,
    "totalRevenue": 89483.94,
    "totalOrders": 47,
    "avgRevenue": 562.79,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 159,
    "totalRevenue": 70523.56,
    "totalOrders": 38,
    "avgRevenue": 443.54,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 159,
    "totalRevenue": 80309.65,
    "totalOrders": 48,
    "avgRevenue": 505.09,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 159,
    "totalRevenue": 69021.35,
    "totalOrders": 41,
    "avgRevenue": 434.1,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 159,
    "totalRevenue": 69182.76,
    "totalOrders": 40,
    "avgRevenue": 435.11,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 159,
    "totalRevenue": 81166.51,
    "totalOrders": 46,
    "avgRevenue": 510.48,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 159,
    "totalRevenue": 94913.88,
    "totalOrders": 50,
    "avgRevenue": 596.94,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 159,
    "totalRevenue": 94968.62,
    "totalOrders": 50,
    "avgRevenue": 597.29,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 159,
    "totalRevenue": 113589.3,
    "totalOrders": 56,
    "avgRevenue": 714.4,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 159,
    "totalRevenue": 86206.66,
    "totalOrders": 47,
    "avgRevenue": 542.18,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 159,
    "totalRevenue": 36340.51,
    "totalOrders": 16,
    "avgRevenue": 228.56,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 162,
    "totalRevenue": 26265.29,
    "totalOrders": 13,
    "avgRevenue": 162.13,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 162,
    "totalRevenue": 9743.8,
    "totalOrders": 7,
    "avgRevenue": 60.15,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 162,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 8.62,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 162,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 162,
    "totalRevenue": 3118.19,
    "totalOrders": 2,
    "avgRevenue": 19.25,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 162,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 162,
    "totalRevenue": 30042.95,
    "totalOrders": 17,
    "avgRevenue": 185.45,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 162,
    "totalRevenue": 40371.09,
    "totalOrders": 25,
    "avgRevenue": 249.2,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 162,
    "totalRevenue": 60910.33,
    "totalOrders": 34,
    "avgRevenue": 375.99,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 162,
    "totalRevenue": 85185.61,
    "totalOrders": 46,
    "avgRevenue": 525.84,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 162,
    "totalRevenue": 100888.43,
    "totalOrders": 47,
    "avgRevenue": 622.77,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 162,
    "totalRevenue": 74592.61,
    "totalOrders": 43,
    "avgRevenue": 460.45,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 162,
    "totalRevenue": 92311.76,
    "totalOrders": 46,
    "avgRevenue": 569.83,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 162,
    "totalRevenue": 84208.06,
    "totalOrders": 45,
    "avgRevenue": 519.8,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 162,
    "totalRevenue": 79285.99,
    "totalOrders": 41,
    "avgRevenue": 489.42,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 162,
    "totalRevenue": 68714.08,
    "totalOrders": 37,
    "avgRevenue": 424.16,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 162,
    "totalRevenue": 55538.01,
    "totalOrders": 32,
    "avgRevenue": 342.83,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 162,
    "totalRevenue": 82158.3,
    "totalOrders": 44,
    "avgRevenue": 507.15,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 162,
    "totalRevenue": 65400.82,
    "totalOrders": 29,
    "avgRevenue": 403.71,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 162,
    "totalRevenue": 60215.71,
    "totalOrders": 33,
    "avgRevenue": 371.7,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 162,
    "totalRevenue": 75051.98,
    "totalOrders": 44,
    "avgRevenue": 463.28,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 162,
    "totalRevenue": 90137.14,
    "totalOrders": 41,
    "avgRevenue": 556.4,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 162,
    "totalRevenue": 74889.28,
    "totalOrders": 37,
    "avgRevenue": 462.28,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 162,
    "totalRevenue": 46789.26,
    "totalOrders": 22,
    "avgRevenue": 288.82,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 154,
    "totalRevenue": 24925.7,
    "totalOrders": 9,
    "avgRevenue": 161.86,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 154,
    "totalRevenue": 3743.8,
    "totalOrders": 2,
    "avgRevenue": 24.31,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 154,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 154,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 154,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 154,
    "totalRevenue": 3785.12,
    "totalOrders": 2,
    "avgRevenue": 24.58,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 154,
    "totalRevenue": 20195.86,
    "totalOrders": 10,
    "avgRevenue": 131.14,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 154,
    "totalRevenue": 45951,
    "totalOrders": 28,
    "avgRevenue": 298.38,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 154,
    "totalRevenue": 67485.98,
    "totalOrders": 35,
    "avgRevenue": 438.22,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 154,
    "totalRevenue": 79554.5,
    "totalOrders": 42,
    "avgRevenue": 516.59,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 154,
    "totalRevenue": 85418.1,
    "totalOrders": 50,
    "avgRevenue": 554.66,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 154,
    "totalRevenue": 92371.61,
    "totalOrders": 51,
    "avgRevenue": 599.82,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 154,
    "totalRevenue": 56523.15,
    "totalOrders": 31,
    "avgRevenue": 367.03,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 154,
    "totalRevenue": 74881.02,
    "totalOrders": 43,
    "avgRevenue": 486.24,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 154,
    "totalRevenue": 78706.22,
    "totalOrders": 43,
    "avgRevenue": 511.08,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 154,
    "totalRevenue": 50810.74,
    "totalOrders": 27,
    "avgRevenue": 329.94,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 154,
    "totalRevenue": 52832.29,
    "totalOrders": 34,
    "avgRevenue": 343.07,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 154,
    "totalRevenue": 51299.54,
    "totalOrders": 29,
    "avgRevenue": 333.11,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 154,
    "totalRevenue": 73706.3,
    "totalOrders": 38,
    "avgRevenue": 478.61,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 154,
    "totalRevenue": 62395.87,
    "totalOrders": 30,
    "avgRevenue": 405.17,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 154,
    "totalRevenue": 72912.41,
    "totalOrders": 43,
    "avgRevenue": 473.46,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 154,
    "totalRevenue": 75762.82,
    "totalOrders": 42,
    "avgRevenue": 491.97,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 154,
    "totalRevenue": 55205.97,
    "totalOrders": 30,
    "avgRevenue": 358.48,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 154,
    "totalRevenue": 29435.54,
    "totalOrders": 16,
    "avgRevenue": 191.14,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 147,
    "totalRevenue": 6255.37,
    "totalOrders": 4,
    "avgRevenue": 42.55,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 147,
    "totalRevenue": 3221.49,
    "totalOrders": 2,
    "avgRevenue": 21.91,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 147,
    "totalRevenue": 983.47,
    "totalOrders": 1,
    "avgRevenue": 6.69,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 147,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 147,
    "totalRevenue": 1238.84,
    "totalOrders": 1,
    "avgRevenue": 8.43,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 147,
    "totalRevenue": 8483.46,
    "totalOrders": 4,
    "avgRevenue": 57.71,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 147,
    "totalRevenue": 19181,
    "totalOrders": 8,
    "avgRevenue": 130.48,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 147,
    "totalRevenue": 44581.93,
    "totalOrders": 21,
    "avgRevenue": 303.28,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 147,
    "totalRevenue": 64215.83,
    "totalOrders": 36,
    "avgRevenue": 436.84,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 147,
    "totalRevenue": 72678.49,
    "totalOrders": 36,
    "avgRevenue": 494.41,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 147,
    "totalRevenue": 72619.85,
    "totalOrders": 36,
    "avgRevenue": 494.01,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 147,
    "totalRevenue": 71875.19,
    "totalOrders": 36,
    "avgRevenue": 488.95,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 147,
    "totalRevenue": 65755.54,
    "totalOrders": 36,
    "avgRevenue": 447.32,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 147,
    "totalRevenue": 80447.58,
    "totalOrders": 42,
    "avgRevenue": 547.26,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 147,
    "totalRevenue": 73904.99,
    "totalOrders": 36,
    "avgRevenue": 502.76,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 147,
    "totalRevenue": 51251.23,
    "totalOrders": 29,
    "avgRevenue": 348.65,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 147,
    "totalRevenue": 45676.27,
    "totalOrders": 25,
    "avgRevenue": 310.72,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 147,
    "totalRevenue": 62409.93,
    "totalOrders": 33,
    "avgRevenue": 424.56,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 147,
    "totalRevenue": 45784.31,
    "totalOrders": 24,
    "avgRevenue": 311.46,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 147,
    "totalRevenue": 53482.64,
    "totalOrders": 26,
    "avgRevenue": 363.83,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 147,
    "totalRevenue": 73990.09,
    "totalOrders": 30,
    "avgRevenue": 503.33,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 147,
    "totalRevenue": 58473.56,
    "totalOrders": 28,
    "avgRevenue": 397.78,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 147,
    "totalRevenue": 47300.02,
    "totalOrders": 21,
    "avgRevenue": 321.77,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 147,
    "totalRevenue": 32428.11,
    "totalOrders": 14,
    "avgRevenue": 220.6,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 143,
    "totalRevenue": 7268.61,
    "totalOrders": 4,
    "avgRevenue": 50.83,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 143,
    "totalRevenue": 2706.62,
    "totalOrders": 1,
    "avgRevenue": 18.93,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 143,
    "totalRevenue": 2719.01,
    "totalOrders": 1,
    "avgRevenue": 19.01,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 143,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 143,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 143,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 7.8,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 143,
    "totalRevenue": 12699.16,
    "totalOrders": 5,
    "avgRevenue": 88.81,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 143,
    "totalRevenue": 32073.61,
    "totalOrders": 15,
    "avgRevenue": 224.29,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 143,
    "totalRevenue": 58296.71,
    "totalOrders": 29,
    "avgRevenue": 407.67,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 143,
    "totalRevenue": 70630.27,
    "totalOrders": 28,
    "avgRevenue": 493.92,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 143,
    "totalRevenue": 46682.96,
    "totalOrders": 22,
    "avgRevenue": 326.45,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 143,
    "totalRevenue": 71544.89,
    "totalOrders": 34,
    "avgRevenue": 500.31,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 143,
    "totalRevenue": 43314.91,
    "totalOrders": 24,
    "avgRevenue": 302.9,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 143,
    "totalRevenue": 44264.57,
    "totalOrders": 24,
    "avgRevenue": 309.54,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 143,
    "totalRevenue": 75707.6,
    "totalOrders": 37,
    "avgRevenue": 529.42,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 143,
    "totalRevenue": 45803.32,
    "totalOrders": 23,
    "avgRevenue": 320.3,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 143,
    "totalRevenue": 60095.13,
    "totalOrders": 32,
    "avgRevenue": 420.25,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 143,
    "totalRevenue": 51485.95,
    "totalOrders": 24,
    "avgRevenue": 360.04,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 143,
    "totalRevenue": 56067.84,
    "totalOrders": 32,
    "avgRevenue": 392.08,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 143,
    "totalRevenue": 55812.42,
    "totalOrders": 27,
    "avgRevenue": 390.3,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 143,
    "totalRevenue": 75255.41,
    "totalOrders": 35,
    "avgRevenue": 526.26,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 143,
    "totalRevenue": 68098.86,
    "totalOrders": 34,
    "avgRevenue": 476.22,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 143,
    "totalRevenue": 66056.36,
    "totalOrders": 36,
    "avgRevenue": 461.93,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 143,
    "totalRevenue": 34224.78,
    "totalOrders": 18,
    "avgRevenue": 239.33,
    "avgOrders": 0.13
  }
];
