// Auto-generated by scripts/updateData.js — last update: 2026-07-27
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 153,
    "totalRevenue": 8458.67,
    "totalOrders": 5,
    "avgRevenue": 55.29,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 153,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 153,
    "totalRevenue": 3214.05,
    "totalOrders": 2,
    "avgRevenue": 21.01,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 153,
    "totalRevenue": 4859.5,
    "totalOrders": 2,
    "avgRevenue": 31.76,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 153,
    "totalRevenue": 2542.15,
    "totalOrders": 3,
    "avgRevenue": 16.62,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 153,
    "totalRevenue": 4528.92,
    "totalOrders": 2,
    "avgRevenue": 29.6,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 153,
    "totalRevenue": 7702.49,
    "totalOrders": 6,
    "avgRevenue": 50.34,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 153,
    "totalRevenue": 26472.73,
    "totalOrders": 12,
    "avgRevenue": 173.02,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 153,
    "totalRevenue": 28836.39,
    "totalOrders": 14,
    "avgRevenue": 188.47,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 153,
    "totalRevenue": 51923.15,
    "totalOrders": 29,
    "avgRevenue": 339.37,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 153,
    "totalRevenue": 60989.28,
    "totalOrders": 34,
    "avgRevenue": 398.62,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 153,
    "totalRevenue": 74257.01,
    "totalOrders": 40,
    "avgRevenue": 485.34,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 153,
    "totalRevenue": 63452.94,
    "totalOrders": 30,
    "avgRevenue": 414.73,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 153,
    "totalRevenue": 85027.84,
    "totalOrders": 42,
    "avgRevenue": 555.74,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 153,
    "totalRevenue": 63909.1,
    "totalOrders": 32,
    "avgRevenue": 417.71,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 153,
    "totalRevenue": 64338.86,
    "totalOrders": 33,
    "avgRevenue": 420.52,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 153,
    "totalRevenue": 65672.73,
    "totalOrders": 31,
    "avgRevenue": 429.23,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 153,
    "totalRevenue": 80749.62,
    "totalOrders": 41,
    "avgRevenue": 527.78,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 153,
    "totalRevenue": 63118.24,
    "totalOrders": 31,
    "avgRevenue": 412.54,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 153,
    "totalRevenue": 98377.78,
    "totalOrders": 52,
    "avgRevenue": 642.99,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 153,
    "totalRevenue": 108441.37,
    "totalOrders": 56,
    "avgRevenue": 708.77,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 153,
    "totalRevenue": 108458.63,
    "totalOrders": 57,
    "avgRevenue": 708.88,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 153,
    "totalRevenue": 95374.36,
    "totalOrders": 46,
    "avgRevenue": 623.36,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 153,
    "totalRevenue": 41931.39,
    "totalOrders": 18,
    "avgRevenue": 274.06,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 154,
    "totalRevenue": 11467.78,
    "totalOrders": 6,
    "avgRevenue": 74.47,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 154,
    "totalRevenue": 5096.69,
    "totalOrders": 3,
    "avgRevenue": 33.1,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 154,
    "totalRevenue": 5479.34,
    "totalOrders": 2,
    "avgRevenue": 35.58,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 154,
    "totalRevenue": 958.68,
    "totalOrders": 1,
    "avgRevenue": 6.23,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 154,
    "totalRevenue": 2718.19,
    "totalOrders": 2,
    "avgRevenue": 17.65,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 154,
    "totalRevenue": 7932.23,
    "totalOrders": 3,
    "avgRevenue": 51.51,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 154,
    "totalRevenue": 30398.34,
    "totalOrders": 15,
    "avgRevenue": 197.39,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 154,
    "totalRevenue": 47935.52,
    "totalOrders": 27,
    "avgRevenue": 311.27,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 154,
    "totalRevenue": 68920.97,
    "totalOrders": 36,
    "avgRevenue": 447.54,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 154,
    "totalRevenue": 97698.5,
    "totalOrders": 53,
    "avgRevenue": 634.41,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 154,
    "totalRevenue": 75828.05,
    "totalOrders": 35,
    "avgRevenue": 492.39,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 154,
    "totalRevenue": 80497.04,
    "totalOrders": 43,
    "avgRevenue": 522.71,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 154,
    "totalRevenue": 104436.92,
    "totalOrders": 57,
    "avgRevenue": 678.16,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 154,
    "totalRevenue": 100961.92,
    "totalOrders": 48,
    "avgRevenue": 655.6,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 154,
    "totalRevenue": 102643.88,
    "totalOrders": 57,
    "avgRevenue": 666.52,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 154,
    "totalRevenue": 104055.7,
    "totalOrders": 57,
    "avgRevenue": 675.69,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 154,
    "totalRevenue": 71270.28,
    "totalOrders": 43,
    "avgRevenue": 462.79,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 154,
    "totalRevenue": 74086.84,
    "totalOrders": 39,
    "avgRevenue": 481.08,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 154,
    "totalRevenue": 81018.22,
    "totalOrders": 39,
    "avgRevenue": 526.09,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 154,
    "totalRevenue": 84872.75,
    "totalOrders": 42,
    "avgRevenue": 551.12,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 154,
    "totalRevenue": 113804.36,
    "totalOrders": 52,
    "avgRevenue": 738.99,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 154,
    "totalRevenue": 91482.78,
    "totalOrders": 47,
    "avgRevenue": 594.04,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 154,
    "totalRevenue": 83062.01,
    "totalOrders": 42,
    "avgRevenue": 539.36,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 154,
    "totalRevenue": 24291.01,
    "totalOrders": 14,
    "avgRevenue": 157.73,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 150,
    "totalRevenue": 16726.46,
    "totalOrders": 10,
    "avgRevenue": 111.51,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 150,
    "totalRevenue": 1954.55,
    "totalOrders": 1,
    "avgRevenue": 13.03,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 150,
    "totalRevenue": 2851.24,
    "totalOrders": 1,
    "avgRevenue": 19.01,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 150,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 150,
    "totalRevenue": 5533.88,
    "totalOrders": 2,
    "avgRevenue": 36.89,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 150,
    "totalRevenue": 4784.3,
    "totalOrders": 2,
    "avgRevenue": 31.9,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 150,
    "totalRevenue": 9047.94,
    "totalOrders": 5,
    "avgRevenue": 60.32,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 150,
    "totalRevenue": 40904.96,
    "totalOrders": 23,
    "avgRevenue": 272.7,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 150,
    "totalRevenue": 83671.95,
    "totalOrders": 40,
    "avgRevenue": 557.81,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 150,
    "totalRevenue": 108671.97,
    "totalOrders": 56,
    "avgRevenue": 724.48,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 150,
    "totalRevenue": 115823.67,
    "totalOrders": 59,
    "avgRevenue": 772.16,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 150,
    "totalRevenue": 109882.86,
    "totalOrders": 57,
    "avgRevenue": 732.55,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 150,
    "totalRevenue": 103692.69,
    "totalOrders": 52,
    "avgRevenue": 691.28,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 150,
    "totalRevenue": 95934.38,
    "totalOrders": 49,
    "avgRevenue": 639.56,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 150,
    "totalRevenue": 85162.99,
    "totalOrders": 45,
    "avgRevenue": 567.75,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 150,
    "totalRevenue": 106442.73,
    "totalOrders": 64,
    "avgRevenue": 709.62,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 150,
    "totalRevenue": 78446.15,
    "totalOrders": 46,
    "avgRevenue": 522.97,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 150,
    "totalRevenue": 65001.77,
    "totalOrders": 38,
    "avgRevenue": 433.35,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 150,
    "totalRevenue": 81166.51,
    "totalOrders": 46,
    "avgRevenue": 541.11,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 150,
    "totalRevenue": 94087.44,
    "totalOrders": 50,
    "avgRevenue": 627.25,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 150,
    "totalRevenue": 91496.72,
    "totalOrders": 48,
    "avgRevenue": 609.98,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 150,
    "totalRevenue": 109624.01,
    "totalOrders": 54,
    "avgRevenue": 730.83,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 150,
    "totalRevenue": 86206.66,
    "totalOrders": 47,
    "avgRevenue": 574.71,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 150,
    "totalRevenue": 33581,
    "totalOrders": 15,
    "avgRevenue": 223.87,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 154,
    "totalRevenue": 26265.29,
    "totalOrders": 13,
    "avgRevenue": 170.55,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 154,
    "totalRevenue": 10809.92,
    "totalOrders": 7,
    "avgRevenue": 70.19,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 154,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 9.07,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 154,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 154,
    "totalRevenue": 3118.19,
    "totalOrders": 2,
    "avgRevenue": 20.25,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 154,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 154,
    "totalRevenue": 30042.95,
    "totalOrders": 17,
    "avgRevenue": 195.08,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 154,
    "totalRevenue": 38085.96,
    "totalOrders": 23,
    "avgRevenue": 247.31,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 154,
    "totalRevenue": 54199.6,
    "totalOrders": 32,
    "avgRevenue": 351.95,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 154,
    "totalRevenue": 97398.85,
    "totalOrders": 51,
    "avgRevenue": 632.46,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 154,
    "totalRevenue": 120383.67,
    "totalOrders": 57,
    "avgRevenue": 781.71,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 154,
    "totalRevenue": 90749.32,
    "totalOrders": 50,
    "avgRevenue": 589.28,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 154,
    "totalRevenue": 98994.44,
    "totalOrders": 50,
    "avgRevenue": 642.82,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 154,
    "totalRevenue": 114283.62,
    "totalOrders": 56,
    "avgRevenue": 742.1,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 154,
    "totalRevenue": 113368.66,
    "totalOrders": 56,
    "avgRevenue": 736.16,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 154,
    "totalRevenue": 93600.23,
    "totalOrders": 50,
    "avgRevenue": 607.79,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 154,
    "totalRevenue": 94691.62,
    "totalOrders": 50,
    "avgRevenue": 614.88,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 154,
    "totalRevenue": 104887.25,
    "totalOrders": 52,
    "avgRevenue": 681.09,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 154,
    "totalRevenue": 53549.58,
    "totalOrders": 26,
    "avgRevenue": 347.72,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 154,
    "totalRevenue": 57991.74,
    "totalOrders": 32,
    "avgRevenue": 376.57,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 154,
    "totalRevenue": 73845.37,
    "totalOrders": 43,
    "avgRevenue": 479.52,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 154,
    "totalRevenue": 85508.21,
    "totalOrders": 39,
    "avgRevenue": 555.25,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 154,
    "totalRevenue": 70427.29,
    "totalOrders": 35,
    "avgRevenue": 457.32,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 154,
    "totalRevenue": 46789.26,
    "totalOrders": 22,
    "avgRevenue": 303.83,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 146,
    "totalRevenue": 23611.65,
    "totalOrders": 8,
    "avgRevenue": 161.72,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 146,
    "totalRevenue": 3743.8,
    "totalOrders": 2,
    "avgRevenue": 25.64,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 146,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 146,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 146,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 146,
    "totalRevenue": 3785.12,
    "totalOrders": 2,
    "avgRevenue": 25.93,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 146,
    "totalRevenue": 20195.86,
    "totalOrders": 10,
    "avgRevenue": 138.33,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 146,
    "totalRevenue": 45951,
    "totalOrders": 28,
    "avgRevenue": 314.73,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 146,
    "totalRevenue": 65007.47,
    "totalOrders": 34,
    "avgRevenue": 445.26,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 146,
    "totalRevenue": 85685.9,
    "totalOrders": 43,
    "avgRevenue": 586.89,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 146,
    "totalRevenue": 114962.74,
    "totalOrders": 63,
    "avgRevenue": 787.42,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 146,
    "totalRevenue": 117355.6,
    "totalOrders": 59,
    "avgRevenue": 803.81,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 146,
    "totalRevenue": 59299.18,
    "totalOrders": 32,
    "avgRevenue": 406.16,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 146,
    "totalRevenue": 99590.95,
    "totalOrders": 53,
    "avgRevenue": 682.13,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 146,
    "totalRevenue": 85536.82,
    "totalOrders": 46,
    "avgRevenue": 585.87,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 146,
    "totalRevenue": 87979.37,
    "totalOrders": 43,
    "avgRevenue": 602.6,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 146,
    "totalRevenue": 52914.93,
    "totalOrders": 34,
    "avgRevenue": 362.43,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 146,
    "totalRevenue": 54273.1,
    "totalOrders": 31,
    "avgRevenue": 371.73,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 146,
    "totalRevenue": 73312.91,
    "totalOrders": 37,
    "avgRevenue": 502.14,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 146,
    "totalRevenue": 58304.96,
    "totalOrders": 28,
    "avgRevenue": 399.35,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 146,
    "totalRevenue": 69586.79,
    "totalOrders": 41,
    "avgRevenue": 476.62,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 146,
    "totalRevenue": 70538.02,
    "totalOrders": 40,
    "avgRevenue": 483.14,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 146,
    "totalRevenue": 55205.97,
    "totalOrders": 30,
    "avgRevenue": 378.12,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 146,
    "totalRevenue": 25072.73,
    "totalOrders": 14,
    "avgRevenue": 171.73,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 142,
    "totalRevenue": 2833.06,
    "totalOrders": 2,
    "avgRevenue": 19.95,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 142,
    "totalRevenue": 3221.49,
    "totalOrders": 2,
    "avgRevenue": 22.69,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 142,
    "totalRevenue": 983.47,
    "totalOrders": 1,
    "avgRevenue": 6.93,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 142,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 142,
    "totalRevenue": 1238.84,
    "totalOrders": 1,
    "avgRevenue": 8.72,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 142,
    "totalRevenue": 8483.46,
    "totalOrders": 4,
    "avgRevenue": 59.74,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 142,
    "totalRevenue": 19181,
    "totalOrders": 8,
    "avgRevenue": 135.08,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 142,
    "totalRevenue": 41772.84,
    "totalOrders": 20,
    "avgRevenue": 294.17,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 142,
    "totalRevenue": 62984.43,
    "totalOrders": 35,
    "avgRevenue": 443.55,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 142,
    "totalRevenue": 69152.03,
    "totalOrders": 37,
    "avgRevenue": 486.99,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 142,
    "totalRevenue": 102331.48,
    "totalOrders": 48,
    "avgRevenue": 720.64,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 142,
    "totalRevenue": 99212.99,
    "totalOrders": 48,
    "avgRevenue": 698.68,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 142,
    "totalRevenue": 80537.37,
    "totalOrders": 42,
    "avgRevenue": 567.16,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 142,
    "totalRevenue": 111503.04,
    "totalOrders": 57,
    "avgRevenue": 785.23,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 142,
    "totalRevenue": 99906.65,
    "totalOrders": 45,
    "avgRevenue": 703.57,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 142,
    "totalRevenue": 98060.34,
    "totalOrders": 50,
    "avgRevenue": 690.57,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 142,
    "totalRevenue": 69465.53,
    "totalOrders": 39,
    "avgRevenue": 489.19,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 142,
    "totalRevenue": 75366.97,
    "totalOrders": 40,
    "avgRevenue": 530.75,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 142,
    "totalRevenue": 46320.68,
    "totalOrders": 24,
    "avgRevenue": 326.2,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 142,
    "totalRevenue": 46761.99,
    "totalOrders": 25,
    "avgRevenue": 329.31,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 142,
    "totalRevenue": 73990.09,
    "totalOrders": 30,
    "avgRevenue": 521.06,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 142,
    "totalRevenue": 59961.16,
    "totalOrders": 28,
    "avgRevenue": 422.26,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 142,
    "totalRevenue": 47300.02,
    "totalOrders": 21,
    "avgRevenue": 333.1,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 142,
    "totalRevenue": 30948.77,
    "totalOrders": 13,
    "avgRevenue": 217.95,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 138,
    "totalRevenue": 7268.61,
    "totalOrders": 4,
    "avgRevenue": 52.67,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 138,
    "totalRevenue": 2706.62,
    "totalOrders": 1,
    "avgRevenue": 19.61,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 138,
    "totalRevenue": 2719.01,
    "totalOrders": 1,
    "avgRevenue": 19.7,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 138,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 138,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 138,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 8.08,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 138,
    "totalRevenue": 12699.16,
    "totalOrders": 5,
    "avgRevenue": 92.02,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 138,
    "totalRevenue": 32073.61,
    "totalOrders": 15,
    "avgRevenue": 232.42,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 138,
    "totalRevenue": 58296.71,
    "totalOrders": 29,
    "avgRevenue": 422.44,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 138,
    "totalRevenue": 70630.27,
    "totalOrders": 28,
    "avgRevenue": 511.81,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 138,
    "totalRevenue": 42090.4,
    "totalOrders": 20,
    "avgRevenue": 305,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 138,
    "totalRevenue": 70148.2,
    "totalOrders": 33,
    "avgRevenue": 508.32,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 138,
    "totalRevenue": 43199.21,
    "totalOrders": 24,
    "avgRevenue": 313.04,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 138,
    "totalRevenue": 42466.22,
    "totalOrders": 23,
    "avgRevenue": 307.73,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 138,
    "totalRevenue": 74045.62,
    "totalOrders": 37,
    "avgRevenue": 536.56,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 138,
    "totalRevenue": 45598.36,
    "totalOrders": 23,
    "avgRevenue": 330.42,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 138,
    "totalRevenue": 56723.23,
    "totalOrders": 30,
    "avgRevenue": 411.04,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 138,
    "totalRevenue": 51485.95,
    "totalOrders": 24,
    "avgRevenue": 373.09,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 138,
    "totalRevenue": 52516.6,
    "totalOrders": 30,
    "avgRevenue": 380.56,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 138,
    "totalRevenue": 55812.42,
    "totalOrders": 27,
    "avgRevenue": 404.44,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 138,
    "totalRevenue": 71883.51,
    "totalOrders": 34,
    "avgRevenue": 520.89,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 138,
    "totalRevenue": 68098.86,
    "totalOrders": 34,
    "avgRevenue": 493.47,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 138,
    "totalRevenue": 66056.36,
    "totalOrders": 36,
    "avgRevenue": 478.67,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 138,
    "totalRevenue": 32662.8,
    "totalOrders": 17,
    "avgRevenue": 236.69,
    "avgOrders": 0.12
  }
];
