// Auto-generated by scripts/updateData.js — last update: 2026-08-18
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 156,
    "totalRevenue": 8458.67,
    "totalOrders": 5,
    "avgRevenue": 54.22,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 156,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 156,
    "totalRevenue": 3214.05,
    "totalOrders": 2,
    "avgRevenue": 20.6,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 156,
    "totalRevenue": 4859.5,
    "totalOrders": 2,
    "avgRevenue": 31.15,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 156,
    "totalRevenue": 2542.15,
    "totalOrders": 3,
    "avgRevenue": 16.3,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 156,
    "totalRevenue": 4528.92,
    "totalOrders": 2,
    "avgRevenue": 29.03,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 156,
    "totalRevenue": 7702.49,
    "totalOrders": 6,
    "avgRevenue": 49.37,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 156,
    "totalRevenue": 26472.73,
    "totalOrders": 12,
    "avgRevenue": 169.7,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 156,
    "totalRevenue": 28836.39,
    "totalOrders": 14,
    "avgRevenue": 184.85,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 156,
    "totalRevenue": 54303.32,
    "totalOrders": 30,
    "avgRevenue": 348.1,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 156,
    "totalRevenue": 62716.55,
    "totalOrders": 35,
    "avgRevenue": 402.03,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 156,
    "totalRevenue": 76389.25,
    "totalOrders": 42,
    "avgRevenue": 489.67,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 156,
    "totalRevenue": 61973.6,
    "totalOrders": 30,
    "avgRevenue": 397.27,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 156,
    "totalRevenue": 88399.75,
    "totalOrders": 44,
    "avgRevenue": 566.67,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 156,
    "totalRevenue": 65023.98,
    "totalOrders": 33,
    "avgRevenue": 416.82,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 156,
    "totalRevenue": 65487.62,
    "totalOrders": 34,
    "avgRevenue": 419.79,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 156,
    "totalRevenue": 62871.08,
    "totalOrders": 30,
    "avgRevenue": 403.02,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 156,
    "totalRevenue": 84121.52,
    "totalOrders": 42,
    "avgRevenue": 539.24,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 156,
    "totalRevenue": 65919.89,
    "totalOrders": 32,
    "avgRevenue": 422.56,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 156,
    "totalRevenue": 99492.66,
    "totalOrders": 53,
    "avgRevenue": 637.77,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 156,
    "totalRevenue": 107375.25,
    "totalOrders": 55,
    "avgRevenue": 688.3,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 156,
    "totalRevenue": 110688.39,
    "totalOrders": 58,
    "avgRevenue": 709.54,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 156,
    "totalRevenue": 95374.36,
    "totalOrders": 46,
    "avgRevenue": 611.37,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 156,
    "totalRevenue": 41931.39,
    "totalOrders": 18,
    "avgRevenue": 268.79,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 157,
    "totalRevenue": 11467.78,
    "totalOrders": 6,
    "avgRevenue": 73.04,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 157,
    "totalRevenue": 6576.03,
    "totalOrders": 4,
    "avgRevenue": 41.89,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 157,
    "totalRevenue": 6958.68,
    "totalOrders": 3,
    "avgRevenue": 44.32,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 157,
    "totalRevenue": 958.68,
    "totalOrders": 1,
    "avgRevenue": 6.11,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 157,
    "totalRevenue": 2718.19,
    "totalOrders": 2,
    "avgRevenue": 17.31,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 157,
    "totalRevenue": 7932.23,
    "totalOrders": 3,
    "avgRevenue": 50.52,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 157,
    "totalRevenue": 30398.34,
    "totalOrders": 15,
    "avgRevenue": 193.62,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 157,
    "totalRevenue": 54652.05,
    "totalOrders": 29,
    "avgRevenue": 348.1,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 157,
    "totalRevenue": 64805.27,
    "totalOrders": 35,
    "avgRevenue": 412.77,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 157,
    "totalRevenue": 96583.62,
    "totalOrders": 52,
    "avgRevenue": 615.18,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 157,
    "totalRevenue": 78437.97,
    "totalOrders": 38,
    "avgRevenue": 499.6,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 157,
    "totalRevenue": 80497.04,
    "totalOrders": 43,
    "avgRevenue": 512.72,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 157,
    "totalRevenue": 105246.84,
    "totalOrders": 58,
    "avgRevenue": 670.36,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 157,
    "totalRevenue": 104686.71,
    "totalOrders": 50,
    "avgRevenue": 666.79,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 157,
    "totalRevenue": 98685.2,
    "totalOrders": 58,
    "avgRevenue": 628.57,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 157,
    "totalRevenue": 111192.89,
    "totalOrders": 59,
    "avgRevenue": 708.23,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 157,
    "totalRevenue": 72914.91,
    "totalOrders": 44,
    "avgRevenue": 464.43,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 157,
    "totalRevenue": 75648.82,
    "totalOrders": 40,
    "avgRevenue": 481.84,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 157,
    "totalRevenue": 81456.24,
    "totalOrders": 39,
    "avgRevenue": 518.83,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 157,
    "totalRevenue": 84872.75,
    "totalOrders": 42,
    "avgRevenue": 540.59,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 157,
    "totalRevenue": 113804.36,
    "totalOrders": 52,
    "avgRevenue": 724.87,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 157,
    "totalRevenue": 91482.78,
    "totalOrders": 47,
    "avgRevenue": 582.69,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 157,
    "totalRevenue": 83062.01,
    "totalOrders": 42,
    "avgRevenue": 529.06,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 157,
    "totalRevenue": 25605.06,
    "totalOrders": 15,
    "avgRevenue": 163.09,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 154,
    "totalRevenue": 18123.15,
    "totalOrders": 11,
    "avgRevenue": 117.68,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 154,
    "totalRevenue": 1954.55,
    "totalOrders": 1,
    "avgRevenue": 12.69,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 154,
    "totalRevenue": 2851.24,
    "totalOrders": 1,
    "avgRevenue": 18.51,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 154,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 154,
    "totalRevenue": 5533.88,
    "totalOrders": 2,
    "avgRevenue": 35.93,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 154,
    "totalRevenue": 4784.3,
    "totalOrders": 2,
    "avgRevenue": 31.07,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 154,
    "totalRevenue": 9047.94,
    "totalOrders": 5,
    "avgRevenue": 58.75,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 154,
    "totalRevenue": 43085.96,
    "totalOrders": 25,
    "avgRevenue": 279.78,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 154,
    "totalRevenue": 84878.56,
    "totalOrders": 41,
    "avgRevenue": 551.16,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 154,
    "totalRevenue": 109878.58,
    "totalOrders": 57,
    "avgRevenue": 713.5,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 154,
    "totalRevenue": 122162.51,
    "totalOrders": 61,
    "avgRevenue": 793.26,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 154,
    "totalRevenue": 115229.97,
    "totalOrders": 60,
    "avgRevenue": 748.25,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 154,
    "totalRevenue": 108386.08,
    "totalOrders": 54,
    "avgRevenue": 703.81,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 154,
    "totalRevenue": 99769.92,
    "totalOrders": 51,
    "avgRevenue": 647.86,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 154,
    "totalRevenue": 85232.66,
    "totalOrders": 45,
    "avgRevenue": 553.46,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 154,
    "totalRevenue": 109911.64,
    "totalOrders": 66,
    "avgRevenue": 713.71,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 154,
    "totalRevenue": 82145.32,
    "totalOrders": 48,
    "avgRevenue": 533.41,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 154,
    "totalRevenue": 67059.62,
    "totalOrders": 39,
    "avgRevenue": 435.45,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 154,
    "totalRevenue": 81166.51,
    "totalOrders": 46,
    "avgRevenue": 527.06,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 154,
    "totalRevenue": 94087.44,
    "totalOrders": 50,
    "avgRevenue": 610.96,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 154,
    "totalRevenue": 92745.48,
    "totalOrders": 49,
    "avgRevenue": 602.24,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 154,
    "totalRevenue": 109624.01,
    "totalOrders": 54,
    "avgRevenue": 711.84,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 154,
    "totalRevenue": 86206.66,
    "totalOrders": 47,
    "avgRevenue": 559.78,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 154,
    "totalRevenue": 36340.51,
    "totalOrders": 16,
    "avgRevenue": 235.98,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 157,
    "totalRevenue": 26265.29,
    "totalOrders": 13,
    "avgRevenue": 167.29,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 157,
    "totalRevenue": 9743.8,
    "totalOrders": 7,
    "avgRevenue": 62.06,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 157,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 8.9,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 157,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 157,
    "totalRevenue": 3118.19,
    "totalOrders": 2,
    "avgRevenue": 19.86,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 157,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 157,
    "totalRevenue": 30042.95,
    "totalOrders": 17,
    "avgRevenue": 191.36,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 157,
    "totalRevenue": 39200.84,
    "totalOrders": 24,
    "avgRevenue": 249.69,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 157,
    "totalRevenue": 54199.6,
    "totalOrders": 32,
    "avgRevenue": 345.22,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 157,
    "totalRevenue": 96688.1,
    "totalOrders": 51,
    "avgRevenue": 615.85,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 157,
    "totalRevenue": 120383.67,
    "totalOrders": 57,
    "avgRevenue": 766.77,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 157,
    "totalRevenue": 92608.82,
    "totalOrders": 52,
    "avgRevenue": 589.87,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 157,
    "totalRevenue": 100556.42,
    "totalOrders": 51,
    "avgRevenue": 640.49,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 157,
    "totalRevenue": 111316.68,
    "totalOrders": 56,
    "avgRevenue": 709.02,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 157,
    "totalRevenue": 123856.27,
    "totalOrders": 59,
    "avgRevenue": 788.89,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 157,
    "totalRevenue": 98501.89,
    "totalOrders": 52,
    "avgRevenue": 627.4,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 157,
    "totalRevenue": 96005.67,
    "totalOrders": 51,
    "avgRevenue": 611.5,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 157,
    "totalRevenue": 108166.59,
    "totalOrders": 54,
    "avgRevenue": 688.96,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 157,
    "totalRevenue": 53549.58,
    "totalOrders": 26,
    "avgRevenue": 341.08,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 157,
    "totalRevenue": 57991.74,
    "totalOrders": 32,
    "avgRevenue": 369.37,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 157,
    "totalRevenue": 75051.98,
    "totalOrders": 44,
    "avgRevenue": 478.04,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 157,
    "totalRevenue": 85508.21,
    "totalOrders": 39,
    "avgRevenue": 544.64,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 157,
    "totalRevenue": 72583.49,
    "totalOrders": 36,
    "avgRevenue": 462.32,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 157,
    "totalRevenue": 46789.26,
    "totalOrders": 22,
    "avgRevenue": 298.02,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 149,
    "totalRevenue": 23611.65,
    "totalOrders": 8,
    "avgRevenue": 158.47,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 149,
    "totalRevenue": 3743.8,
    "totalOrders": 2,
    "avgRevenue": 25.13,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 149,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 149,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 149,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 149,
    "totalRevenue": 3785.12,
    "totalOrders": 2,
    "avgRevenue": 25.4,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 149,
    "totalRevenue": 20195.86,
    "totalOrders": 10,
    "avgRevenue": 135.54,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 149,
    "totalRevenue": 45951,
    "totalOrders": 28,
    "avgRevenue": 308.4,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 149,
    "totalRevenue": 65007.47,
    "totalOrders": 34,
    "avgRevenue": 436.29,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 149,
    "totalRevenue": 89652.02,
    "totalOrders": 46,
    "avgRevenue": 601.69,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 149,
    "totalRevenue": 117268.53,
    "totalOrders": 64,
    "avgRevenue": 787.04,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 149,
    "totalRevenue": 120505.18,
    "totalOrders": 61,
    "avgRevenue": 808.76,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 149,
    "totalRevenue": 60087.68,
    "totalOrders": 33,
    "avgRevenue": 403.27,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 149,
    "totalRevenue": 104905,
    "totalOrders": 56,
    "avgRevenue": 704.06,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 149,
    "totalRevenue": 86743.43,
    "totalOrders": 47,
    "avgRevenue": 582.17,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 149,
    "totalRevenue": 87979.37,
    "totalOrders": 43,
    "avgRevenue": 590.47,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 149,
    "totalRevenue": 55426.5,
    "totalOrders": 36,
    "avgRevenue": 371.99,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 149,
    "totalRevenue": 51299.54,
    "totalOrders": 29,
    "avgRevenue": 344.29,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 149,
    "totalRevenue": 73706.3,
    "totalOrders": 38,
    "avgRevenue": 494.67,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 149,
    "totalRevenue": 59511.57,
    "totalOrders": 29,
    "avgRevenue": 399.41,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 149,
    "totalRevenue": 71231.42,
    "totalOrders": 42,
    "avgRevenue": 478.06,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 149,
    "totalRevenue": 70538.02,
    "totalOrders": 40,
    "avgRevenue": 473.41,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 149,
    "totalRevenue": 55205.97,
    "totalOrders": 30,
    "avgRevenue": 370.51,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 149,
    "totalRevenue": 25072.73,
    "totalOrders": 14,
    "avgRevenue": 168.27,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 145,
    "totalRevenue": 4064.46,
    "totalOrders": 3,
    "avgRevenue": 28.03,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 145,
    "totalRevenue": 3221.49,
    "totalOrders": 2,
    "avgRevenue": 22.22,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 145,
    "totalRevenue": 983.47,
    "totalOrders": 1,
    "avgRevenue": 6.78,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 145,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 145,
    "totalRevenue": 1238.84,
    "totalOrders": 1,
    "avgRevenue": 8.54,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 145,
    "totalRevenue": 8483.46,
    "totalOrders": 4,
    "avgRevenue": 58.51,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 145,
    "totalRevenue": 19181,
    "totalOrders": 8,
    "avgRevenue": 132.28,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 145,
    "totalRevenue": 41772.84,
    "totalOrders": 20,
    "avgRevenue": 288.09,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 145,
    "totalRevenue": 64215.83,
    "totalOrders": 36,
    "avgRevenue": 442.87,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 145,
    "totalRevenue": 81284.26,
    "totalOrders": 41,
    "avgRevenue": 560.58,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 145,
    "totalRevenue": 104183.55,
    "totalOrders": 49,
    "avgRevenue": 718.51,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 145,
    "totalRevenue": 100527.04,
    "totalOrders": 49,
    "avgRevenue": 693.29,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 145,
    "totalRevenue": 80537.37,
    "totalOrders": 42,
    "avgRevenue": 555.43,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 145,
    "totalRevenue": 116436.92,
    "totalOrders": 59,
    "avgRevenue": 803.01,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 145,
    "totalRevenue": 101312.44,
    "totalOrders": 46,
    "avgRevenue": 698.71,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 145,
    "totalRevenue": 96208.27,
    "totalOrders": 49,
    "avgRevenue": 663.51,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 145,
    "totalRevenue": 68506.03,
    "totalOrders": 39,
    "avgRevenue": 472.46,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 145,
    "totalRevenue": 75366.97,
    "totalOrders": 40,
    "avgRevenue": 519.77,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 145,
    "totalRevenue": 43726.46,
    "totalOrders": 23,
    "avgRevenue": 301.56,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 145,
    "totalRevenue": 46761.99,
    "totalOrders": 25,
    "avgRevenue": 322.5,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 145,
    "totalRevenue": 73990.09,
    "totalOrders": 30,
    "avgRevenue": 510.28,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 145,
    "totalRevenue": 57159.51,
    "totalOrders": 27,
    "avgRevenue": 394.2,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 145,
    "totalRevenue": 47300.02,
    "totalOrders": 21,
    "avgRevenue": 326.21,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 145,
    "totalRevenue": 32428.11,
    "totalOrders": 14,
    "avgRevenue": 223.64,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 140,
    "totalRevenue": 7268.61,
    "totalOrders": 4,
    "avgRevenue": 51.92,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 140,
    "totalRevenue": 2706.62,
    "totalOrders": 1,
    "avgRevenue": 19.33,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 140,
    "totalRevenue": 2719.01,
    "totalOrders": 1,
    "avgRevenue": 19.42,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 140,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 140,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 140,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 7.96,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 140,
    "totalRevenue": 12699.16,
    "totalOrders": 5,
    "avgRevenue": 90.71,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 140,
    "totalRevenue": 32073.61,
    "totalOrders": 15,
    "avgRevenue": 229.1,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 140,
    "totalRevenue": 58296.71,
    "totalOrders": 29,
    "avgRevenue": 416.41,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 140,
    "totalRevenue": 70630.27,
    "totalOrders": 28,
    "avgRevenue": 504.5,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 140,
    "totalRevenue": 44601.97,
    "totalOrders": 21,
    "avgRevenue": 318.59,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 140,
    "totalRevenue": 70148.2,
    "totalOrders": 33,
    "avgRevenue": 501.06,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 140,
    "totalRevenue": 45390.12,
    "totalOrders": 25,
    "avgRevenue": 324.22,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 140,
    "totalRevenue": 44264.57,
    "totalOrders": 24,
    "avgRevenue": 316.18,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 140,
    "totalRevenue": 77748.1,
    "totalOrders": 39,
    "avgRevenue": 555.34,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 140,
    "totalRevenue": 44036.38,
    "totalOrders": 22,
    "avgRevenue": 314.55,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 140,
    "totalRevenue": 56723.23,
    "totalOrders": 30,
    "avgRevenue": 405.17,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 140,
    "totalRevenue": 51485.95,
    "totalOrders": 24,
    "avgRevenue": 367.76,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 140,
    "totalRevenue": 54672.8,
    "totalOrders": 31,
    "avgRevenue": 390.52,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 140,
    "totalRevenue": 55812.42,
    "totalOrders": 27,
    "avgRevenue": 398.66,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 140,
    "totalRevenue": 71883.51,
    "totalOrders": 34,
    "avgRevenue": 513.45,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 140,
    "totalRevenue": 68098.86,
    "totalOrders": 34,
    "avgRevenue": 486.42,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 140,
    "totalRevenue": 66056.36,
    "totalOrders": 36,
    "avgRevenue": 471.83,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 140,
    "totalRevenue": 32662.8,
    "totalOrders": 17,
    "avgRevenue": 233.31,
    "avgOrders": 0.12
  }
];
