// Auto-generated by scripts/updateData.js — last update: 2026-08-27
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZEshop: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 157,
    "totalRevenue": 8458.67,
    "totalOrders": 5,
    "avgRevenue": 53.88,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 157,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 157,
    "totalRevenue": 3214.05,
    "totalOrders": 2,
    "avgRevenue": 20.47,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 157,
    "totalRevenue": 4859.5,
    "totalOrders": 2,
    "avgRevenue": 30.95,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 157,
    "totalRevenue": 2542.15,
    "totalOrders": 3,
    "avgRevenue": 16.19,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 157,
    "totalRevenue": 4528.92,
    "totalOrders": 2,
    "avgRevenue": 28.85,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 157,
    "totalRevenue": 7702.49,
    "totalOrders": 6,
    "avgRevenue": 49.06,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 157,
    "totalRevenue": 26472.73,
    "totalOrders": 12,
    "avgRevenue": 168.62,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 157,
    "totalRevenue": 27026.47,
    "totalOrders": 13,
    "avgRevenue": 172.14,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 157,
    "totalRevenue": 56973.57,
    "totalOrders": 31,
    "avgRevenue": 362.89,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 157,
    "totalRevenue": 62716.55,
    "totalOrders": 35,
    "avgRevenue": 399.47,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 157,
    "totalRevenue": 76389.25,
    "totalOrders": 42,
    "avgRevenue": 486.56,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 157,
    "totalRevenue": 61973.6,
    "totalOrders": 30,
    "avgRevenue": 394.74,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 157,
    "totalRevenue": 88399.75,
    "totalOrders": 44,
    "avgRevenue": 563.06,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 157,
    "totalRevenue": 65023.98,
    "totalOrders": 33,
    "avgRevenue": 414.17,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 157,
    "totalRevenue": 65487.62,
    "totalOrders": 34,
    "avgRevenue": 417.12,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 157,
    "totalRevenue": 62871.08,
    "totalOrders": 30,
    "avgRevenue": 400.45,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 157,
    "totalRevenue": 82642.18,
    "totalOrders": 42,
    "avgRevenue": 526.38,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 157,
    "totalRevenue": 68083.53,
    "totalOrders": 33,
    "avgRevenue": 433.65,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 157,
    "totalRevenue": 99492.66,
    "totalOrders": 53,
    "avgRevenue": 633.71,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 157,
    "totalRevenue": 107375.25,
    "totalOrders": 55,
    "avgRevenue": 683.92,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 157,
    "totalRevenue": 107185.08,
    "totalOrders": 57,
    "avgRevenue": 682.71,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 157,
    "totalRevenue": 95374.36,
    "totalOrders": 46,
    "avgRevenue": 607.48,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 157,
    "totalRevenue": 41931.39,
    "totalOrders": 18,
    "avgRevenue": 267.08,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 158,
    "totalRevenue": 11467.78,
    "totalOrders": 6,
    "avgRevenue": 72.58,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 158,
    "totalRevenue": 6576.03,
    "totalOrders": 4,
    "avgRevenue": 41.62,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 158,
    "totalRevenue": 6958.68,
    "totalOrders": 3,
    "avgRevenue": 44.04,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 158,
    "totalRevenue": 958.68,
    "totalOrders": 1,
    "avgRevenue": 6.07,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 158,
    "totalRevenue": 2718.19,
    "totalOrders": 2,
    "avgRevenue": 17.2,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 158,
    "totalRevenue": 7932.23,
    "totalOrders": 3,
    "avgRevenue": 50.2,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 158,
    "totalRevenue": 30398.34,
    "totalOrders": 15,
    "avgRevenue": 192.39,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 158,
    "totalRevenue": 54652.05,
    "totalOrders": 29,
    "avgRevenue": 345.9,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 158,
    "totalRevenue": 64805.27,
    "totalOrders": 35,
    "avgRevenue": 410.16,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 158,
    "totalRevenue": 96157.18,
    "totalOrders": 51,
    "avgRevenue": 608.59,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 158,
    "totalRevenue": 75990.86,
    "totalOrders": 37,
    "avgRevenue": 480.95,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 158,
    "totalRevenue": 78191.25,
    "totalOrders": 42,
    "avgRevenue": 494.88,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 158,
    "totalRevenue": 101735.27,
    "totalOrders": 56,
    "avgRevenue": 643.89,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 158,
    "totalRevenue": 68627.28,
    "totalOrders": 33,
    "avgRevenue": 434.35,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 158,
    "totalRevenue": 75780.22,
    "totalOrders": 44,
    "avgRevenue": 479.62,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 158,
    "totalRevenue": 82560.64,
    "totalOrders": 46,
    "avgRevenue": 522.54,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 158,
    "totalRevenue": 72914.91,
    "totalOrders": 44,
    "avgRevenue": 461.49,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 158,
    "totalRevenue": 75648.82,
    "totalOrders": 40,
    "avgRevenue": 478.79,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 158,
    "totalRevenue": 81456.24,
    "totalOrders": 39,
    "avgRevenue": 515.55,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 158,
    "totalRevenue": 84872.75,
    "totalOrders": 42,
    "avgRevenue": 537.17,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 158,
    "totalRevenue": 116110.15,
    "totalOrders": 53,
    "avgRevenue": 734.87,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 158,
    "totalRevenue": 90086.09,
    "totalOrders": 46,
    "avgRevenue": 570.17,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 158,
    "totalRevenue": 83062.01,
    "totalOrders": 42,
    "avgRevenue": 525.71,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 158,
    "totalRevenue": 25605.06,
    "totalOrders": 15,
    "avgRevenue": 162.06,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 155,
    "totalRevenue": 19082.65,
    "totalOrders": 12,
    "avgRevenue": 123.11,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 155,
    "totalRevenue": 1954.55,
    "totalOrders": 1,
    "avgRevenue": 12.61,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 155,
    "totalRevenue": 2851.24,
    "totalOrders": 1,
    "avgRevenue": 18.4,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 155,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 155,
    "totalRevenue": 5533.88,
    "totalOrders": 2,
    "avgRevenue": 35.7,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 155,
    "totalRevenue": 4784.3,
    "totalOrders": 2,
    "avgRevenue": 30.87,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 155,
    "totalRevenue": 9047.94,
    "totalOrders": 5,
    "avgRevenue": 58.37,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 155,
    "totalRevenue": 43904.14,
    "totalOrders": 26,
    "avgRevenue": 283.25,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 155,
    "totalRevenue": 82441.37,
    "totalOrders": 40,
    "avgRevenue": 531.88,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 155,
    "totalRevenue": 95073.62,
    "totalOrders": 49,
    "avgRevenue": 613.38,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 155,
    "totalRevenue": 86585.63,
    "totalOrders": 48,
    "avgRevenue": 558.62,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 155,
    "totalRevenue": 94168.8,
    "totalOrders": 49,
    "avgRevenue": 607.54,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 155,
    "totalRevenue": 93062.12,
    "totalOrders": 47,
    "avgRevenue": 600.4,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 155,
    "totalRevenue": 81004.6,
    "totalOrders": 43,
    "avgRevenue": 522.61,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 155,
    "totalRevenue": 70523.56,
    "totalOrders": 38,
    "avgRevenue": 454.99,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 155,
    "totalRevenue": 78665.02,
    "totalOrders": 47,
    "avgRevenue": 507.52,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 155,
    "totalRevenue": 69021.35,
    "totalOrders": 41,
    "avgRevenue": 445.3,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 155,
    "totalRevenue": 69182.76,
    "totalOrders": 40,
    "avgRevenue": 446.34,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 155,
    "totalRevenue": 83472.3,
    "totalOrders": 47,
    "avgRevenue": 538.53,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 155,
    "totalRevenue": 92972.56,
    "totalOrders": 49,
    "avgRevenue": 599.82,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 155,
    "totalRevenue": 94968.62,
    "totalOrders": 50,
    "avgRevenue": 612.7,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 155,
    "totalRevenue": 113589.3,
    "totalOrders": 56,
    "avgRevenue": 732.83,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 155,
    "totalRevenue": 86206.66,
    "totalOrders": 47,
    "avgRevenue": 556.17,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 155,
    "totalRevenue": 36340.51,
    "totalOrders": 16,
    "avgRevenue": 234.45,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 158,
    "totalRevenue": 26265.29,
    "totalOrders": 13,
    "avgRevenue": 166.24,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 158,
    "totalRevenue": 9743.8,
    "totalOrders": 7,
    "avgRevenue": 61.67,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 158,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 8.84,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 158,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 158,
    "totalRevenue": 3118.19,
    "totalOrders": 2,
    "avgRevenue": 19.74,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 158,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 158,
    "totalRevenue": 30042.95,
    "totalOrders": 17,
    "avgRevenue": 190.15,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 158,
    "totalRevenue": 40371.09,
    "totalOrders": 25,
    "avgRevenue": 255.51,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 158,
    "totalRevenue": 54199.6,
    "totalOrders": 32,
    "avgRevenue": 343.04,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 158,
    "totalRevenue": 85764.13,
    "totalOrders": 46,
    "avgRevenue": 542.81,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 158,
    "totalRevenue": 100888.43,
    "totalOrders": 47,
    "avgRevenue": 638.53,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 158,
    "totalRevenue": 73857.07,
    "totalOrders": 42,
    "avgRevenue": 467.45,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 158,
    "totalRevenue": 92311.76,
    "totalOrders": 46,
    "avgRevenue": 584.25,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 158,
    "totalRevenue": 82894.01,
    "totalOrders": 44,
    "avgRevenue": 524.65,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 158,
    "totalRevenue": 72451.28,
    "totalOrders": 38,
    "avgRevenue": 458.55,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 158,
    "totalRevenue": 68714.08,
    "totalOrders": 37,
    "avgRevenue": 434.9,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 158,
    "totalRevenue": 55538.01,
    "totalOrders": 32,
    "avgRevenue": 351.51,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 158,
    "totalRevenue": 79364.92,
    "totalOrders": 43,
    "avgRevenue": 502.31,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 158,
    "totalRevenue": 57243.8,
    "totalOrders": 27,
    "avgRevenue": 362.3,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 158,
    "totalRevenue": 57991.74,
    "totalOrders": 32,
    "avgRevenue": 367.04,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 158,
    "totalRevenue": 75051.98,
    "totalOrders": 44,
    "avgRevenue": 475.01,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 158,
    "totalRevenue": 84137.14,
    "totalOrders": 39,
    "avgRevenue": 532.51,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 158,
    "totalRevenue": 72583.49,
    "totalOrders": 36,
    "avgRevenue": 459.39,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 158,
    "totalRevenue": 46789.26,
    "totalOrders": 22,
    "avgRevenue": 296.13,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 150,
    "totalRevenue": 23611.65,
    "totalOrders": 8,
    "avgRevenue": 157.41,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 150,
    "totalRevenue": 3743.8,
    "totalOrders": 2,
    "avgRevenue": 24.96,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 150,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 150,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 150,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 150,
    "totalRevenue": 3785.12,
    "totalOrders": 2,
    "avgRevenue": 25.23,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 150,
    "totalRevenue": 20195.86,
    "totalOrders": 10,
    "avgRevenue": 134.64,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 150,
    "totalRevenue": 45951,
    "totalOrders": 28,
    "avgRevenue": 306.34,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 150,
    "totalRevenue": 65007.47,
    "totalOrders": 34,
    "avgRevenue": 433.38,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 150,
    "totalRevenue": 79554.5,
    "totalOrders": 42,
    "avgRevenue": 530.36,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 150,
    "totalRevenue": 85418.1,
    "totalOrders": 50,
    "avgRevenue": 569.45,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 150,
    "totalRevenue": 94429.46,
    "totalOrders": 52,
    "avgRevenue": 629.53,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 150,
    "totalRevenue": 56284.31,
    "totalOrders": 30,
    "avgRevenue": 375.23,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 150,
    "totalRevenue": 74881.02,
    "totalOrders": 43,
    "avgRevenue": 499.21,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 150,
    "totalRevenue": 69078.12,
    "totalOrders": 39,
    "avgRevenue": 460.52,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 150,
    "totalRevenue": 49414.05,
    "totalOrders": 26,
    "avgRevenue": 329.43,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 150,
    "totalRevenue": 52832.29,
    "totalOrders": 34,
    "avgRevenue": 352.22,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 150,
    "totalRevenue": 52861.52,
    "totalOrders": 30,
    "avgRevenue": 352.41,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 150,
    "totalRevenue": 73706.3,
    "totalOrders": 38,
    "avgRevenue": 491.38,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 150,
    "totalRevenue": 59511.57,
    "totalOrders": 29,
    "avgRevenue": 396.74,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 150,
    "totalRevenue": 72912.41,
    "totalOrders": 43,
    "avgRevenue": 486.08,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 150,
    "totalRevenue": 72878.52,
    "totalOrders": 41,
    "avgRevenue": 485.86,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 150,
    "totalRevenue": 55205.97,
    "totalOrders": 30,
    "avgRevenue": 368.04,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 150,
    "totalRevenue": 25072.73,
    "totalOrders": 14,
    "avgRevenue": 167.15,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 144,
    "totalRevenue": 4064.46,
    "totalOrders": 3,
    "avgRevenue": 28.23,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 144,
    "totalRevenue": 3221.49,
    "totalOrders": 2,
    "avgRevenue": 22.37,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 144,
    "totalRevenue": 983.47,
    "totalOrders": 1,
    "avgRevenue": 6.83,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 144,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 144,
    "totalRevenue": 1238.84,
    "totalOrders": 1,
    "avgRevenue": 8.6,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 144,
    "totalRevenue": 8483.46,
    "totalOrders": 4,
    "avgRevenue": 58.91,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 144,
    "totalRevenue": 19181,
    "totalOrders": 8,
    "avgRevenue": 133.2,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 144,
    "totalRevenue": 43417.47,
    "totalOrders": 21,
    "avgRevenue": 301.51,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 144,
    "totalRevenue": 64215.83,
    "totalOrders": 36,
    "avgRevenue": 445.94,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 144,
    "totalRevenue": 72467.74,
    "totalOrders": 36,
    "avgRevenue": 503.25,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 144,
    "totalRevenue": 69809.93,
    "totalOrders": 34,
    "avgRevenue": 484.79,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 144,
    "totalRevenue": 71875.19,
    "totalOrders": 36,
    "avgRevenue": 499.13,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 144,
    "totalRevenue": 65755.54,
    "totalOrders": 36,
    "avgRevenue": 456.64,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 144,
    "totalRevenue": 80447.58,
    "totalOrders": 42,
    "avgRevenue": 558.66,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 144,
    "totalRevenue": 73904.99,
    "totalOrders": 36,
    "avgRevenue": 513.23,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 144,
    "totalRevenue": 48945.44,
    "totalOrders": 28,
    "avgRevenue": 339.9,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 144,
    "totalRevenue": 42957.26,
    "totalOrders": 24,
    "avgRevenue": 298.31,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 144,
    "totalRevenue": 62409.93,
    "totalOrders": 33,
    "avgRevenue": 433.4,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 144,
    "totalRevenue": 43726.46,
    "totalOrders": 23,
    "avgRevenue": 303.66,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 144,
    "totalRevenue": 46761.99,
    "totalOrders": 25,
    "avgRevenue": 324.74,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 144,
    "totalRevenue": 73990.09,
    "totalOrders": 30,
    "avgRevenue": 513.82,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 144,
    "totalRevenue": 57159.51,
    "totalOrders": 27,
    "avgRevenue": 396.94,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 144,
    "totalRevenue": 47300.02,
    "totalOrders": 21,
    "avgRevenue": 328.47,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 144,
    "totalRevenue": 32428.11,
    "totalOrders": 14,
    "avgRevenue": 225.2,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 141,
    "totalRevenue": 7268.61,
    "totalOrders": 4,
    "avgRevenue": 51.55,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 141,
    "totalRevenue": 2706.62,
    "totalOrders": 1,
    "avgRevenue": 19.2,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 141,
    "totalRevenue": 2719.01,
    "totalOrders": 1,
    "avgRevenue": 19.28,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 141,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 141,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 141,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 7.91,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 141,
    "totalRevenue": 12699.16,
    "totalOrders": 5,
    "avgRevenue": 90.06,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 141,
    "totalRevenue": 32073.61,
    "totalOrders": 15,
    "avgRevenue": 227.47,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 141,
    "totalRevenue": 58296.71,
    "totalOrders": 29,
    "avgRevenue": 413.45,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 141,
    "totalRevenue": 70630.27,
    "totalOrders": 28,
    "avgRevenue": 500.92,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 141,
    "totalRevenue": 44601.97,
    "totalOrders": 21,
    "avgRevenue": 316.33,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 141,
    "totalRevenue": 70148.2,
    "totalOrders": 33,
    "avgRevenue": 497.5,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 141,
    "totalRevenue": 43314.91,
    "totalOrders": 24,
    "avgRevenue": 307.2,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 141,
    "totalRevenue": 44264.57,
    "totalOrders": 24,
    "avgRevenue": 313.93,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 141,
    "totalRevenue": 75707.6,
    "totalOrders": 37,
    "avgRevenue": 536.93,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 141,
    "totalRevenue": 45803.32,
    "totalOrders": 23,
    "avgRevenue": 324.85,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 141,
    "totalRevenue": 58698.44,
    "totalOrders": 31,
    "avgRevenue": 416.3,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 141,
    "totalRevenue": 51485.95,
    "totalOrders": 24,
    "avgRevenue": 365.15,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 141,
    "totalRevenue": 53193.46,
    "totalOrders": 30,
    "avgRevenue": 377.26,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 141,
    "totalRevenue": 55812.42,
    "totalOrders": 27,
    "avgRevenue": 395.83,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 141,
    "totalRevenue": 75255.41,
    "totalOrders": 35,
    "avgRevenue": 533.73,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 141,
    "totalRevenue": 68098.86,
    "totalOrders": 34,
    "avgRevenue": 482.97,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 141,
    "totalRevenue": 66056.36,
    "totalOrders": 36,
    "avgRevenue": 468.48,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 141,
    "totalRevenue": 32662.8,
    "totalOrders": 17,
    "avgRevenue": 231.65,
    "avgOrders": 0.12
  }
];
