// Auto-generated by scripts/updateData.js — last update: 2026-04-23
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 139,
    "totalRevenue": 8458.67,
    "totalOrders": 5,
    "avgRevenue": 60.85,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 139,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 139,
    "totalRevenue": 1652.07,
    "totalOrders": 1,
    "avgRevenue": 11.89,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 139,
    "totalRevenue": 4859.5,
    "totalOrders": 2,
    "avgRevenue": 34.96,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 139,
    "totalRevenue": 2542.15,
    "totalOrders": 3,
    "avgRevenue": 18.29,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 139,
    "totalRevenue": 4528.92,
    "totalOrders": 2,
    "avgRevenue": 32.58,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 139,
    "totalRevenue": 5252.07,
    "totalOrders": 4,
    "avgRevenue": 37.78,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 139,
    "totalRevenue": 26472.73,
    "totalOrders": 12,
    "avgRevenue": 190.45,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 139,
    "totalRevenue": 16876.06,
    "totalOrders": 11,
    "avgRevenue": 121.41,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 139,
    "totalRevenue": 43284.3,
    "totalOrders": 26,
    "avgRevenue": 311.4,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 139,
    "totalRevenue": 59923.16,
    "totalOrders": 33,
    "avgRevenue": 431.1,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 139,
    "totalRevenue": 63462.8,
    "totalOrders": 33,
    "avgRevenue": 456.57,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 139,
    "totalRevenue": 54343.84,
    "totalOrders": 27,
    "avgRevenue": 390.96,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 139,
    "totalRevenue": 64093.96,
    "totalOrders": 36,
    "avgRevenue": 461.11,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 139,
    "totalRevenue": 58452.08,
    "totalOrders": 29,
    "avgRevenue": 420.52,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 139,
    "totalRevenue": 54916.54,
    "totalOrders": 28,
    "avgRevenue": 395.08,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 139,
    "totalRevenue": 53588.44,
    "totalOrders": 25,
    "avgRevenue": 385.53,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 139,
    "totalRevenue": 70104.16,
    "totalOrders": 35,
    "avgRevenue": 504.35,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 139,
    "totalRevenue": 61617.41,
    "totalOrders": 30,
    "avgRevenue": 443.29,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 139,
    "totalRevenue": 83012.51,
    "totalOrders": 42,
    "avgRevenue": 597.21,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 139,
    "totalRevenue": 99300.86,
    "totalOrders": 50,
    "avgRevenue": 714.39,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 139,
    "totalRevenue": 91556.15,
    "totalOrders": 47,
    "avgRevenue": 658.68,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 139,
    "totalRevenue": 88281.8,
    "totalOrders": 41,
    "avgRevenue": 635.12,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 139,
    "totalRevenue": 32354.53,
    "totalOrders": 15,
    "avgRevenue": 232.77,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 140,
    "totalRevenue": 8342.98,
    "totalOrders": 4,
    "avgRevenue": 59.59,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 140,
    "totalRevenue": 3700,
    "totalOrders": 2,
    "avgRevenue": 26.43,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 140,
    "totalRevenue": 5479.34,
    "totalOrders": 2,
    "avgRevenue": 39.14,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 140,
    "totalRevenue": 958.68,
    "totalOrders": 1,
    "avgRevenue": 6.85,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 140,
    "totalRevenue": 2718.19,
    "totalOrders": 2,
    "avgRevenue": 19.42,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 140,
    "totalRevenue": 6618.18,
    "totalOrders": 2,
    "avgRevenue": 47.27,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 140,
    "totalRevenue": 19485.94,
    "totalOrders": 11,
    "avgRevenue": 139.19,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 140,
    "totalRevenue": 41173.54,
    "totalOrders": 23,
    "avgRevenue": 294.1,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 140,
    "totalRevenue": 47969.74,
    "totalOrders": 26,
    "avgRevenue": 342.64,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 140,
    "totalRevenue": 85057.99,
    "totalOrders": 47,
    "avgRevenue": 607.56,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 140,
    "totalRevenue": 69528.87,
    "totalOrders": 32,
    "avgRevenue": 496.63,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 140,
    "totalRevenue": 62352.4,
    "totalOrders": 32,
    "avgRevenue": 445.37,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 140,
    "totalRevenue": 97587.33,
    "totalOrders": 53,
    "avgRevenue": 697.05,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 140,
    "totalRevenue": 98369.36,
    "totalOrders": 46,
    "avgRevenue": 702.64,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 140,
    "totalRevenue": 76697.59,
    "totalOrders": 43,
    "avgRevenue": 547.84,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 140,
    "totalRevenue": 106439.92,
    "totalOrders": 51,
    "avgRevenue": 760.29,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 140,
    "totalRevenue": 62701.7,
    "totalOrders": 38,
    "avgRevenue": 447.87,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 140,
    "totalRevenue": 65731.47,
    "totalOrders": 35,
    "avgRevenue": 469.51,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 140,
    "totalRevenue": 76919.04,
    "totalOrders": 34,
    "avgRevenue": 549.42,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 140,
    "totalRevenue": 81216.55,
    "totalOrders": 39,
    "avgRevenue": 580.12,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 140,
    "totalRevenue": 107353.94,
    "totalOrders": 47,
    "avgRevenue": 766.81,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 140,
    "totalRevenue": 74384.44,
    "totalOrders": 37,
    "avgRevenue": 531.32,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 140,
    "totalRevenue": 67240.51,
    "totalOrders": 35,
    "avgRevenue": 480.29,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 140,
    "totalRevenue": 22455.47,
    "totalOrders": 13,
    "avgRevenue": 160.4,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 137,
    "totalRevenue": 13409.1,
    "totalOrders": 8,
    "avgRevenue": 97.88,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 137,
    "totalRevenue": 1954.55,
    "totalOrders": 1,
    "avgRevenue": 14.27,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 137,
    "totalRevenue": 2851.24,
    "totalOrders": 1,
    "avgRevenue": 20.81,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 137,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 137,
    "totalRevenue": 5533.88,
    "totalOrders": 2,
    "avgRevenue": 40.39,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 137,
    "totalRevenue": 2966.94,
    "totalOrders": 1,
    "avgRevenue": 21.66,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 137,
    "totalRevenue": 9047.94,
    "totalOrders": 5,
    "avgRevenue": 66.04,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 137,
    "totalRevenue": 26522.33,
    "totalOrders": 16,
    "avgRevenue": 193.59,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 137,
    "totalRevenue": 70416.57,
    "totalOrders": 32,
    "avgRevenue": 513.99,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 137,
    "totalRevenue": 87900.89,
    "totalOrders": 45,
    "avgRevenue": 641.61,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 137,
    "totalRevenue": 104798.85,
    "totalOrders": 53,
    "avgRevenue": 764.96,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 137,
    "totalRevenue": 97028.3,
    "totalOrders": 48,
    "avgRevenue": 708.24,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 137,
    "totalRevenue": 84854.68,
    "totalOrders": 41,
    "avgRevenue": 619.38,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 137,
    "totalRevenue": 79765.77,
    "totalOrders": 41,
    "avgRevenue": 582.23,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 137,
    "totalRevenue": 71124.8,
    "totalOrders": 36,
    "avgRevenue": 519.16,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 137,
    "totalRevenue": 88466.69,
    "totalOrders": 55,
    "avgRevenue": 645.74,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 137,
    "totalRevenue": 64272.57,
    "totalOrders": 35,
    "avgRevenue": 469.14,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 137,
    "totalRevenue": 54710.03,
    "totalOrders": 31,
    "avgRevenue": 399.34,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 137,
    "totalRevenue": 78035.93,
    "totalOrders": 43,
    "avgRevenue": 569.61,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 137,
    "totalRevenue": 84137.01,
    "totalOrders": 44,
    "avgRevenue": 614.14,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 137,
    "totalRevenue": 84230.6,
    "totalOrders": 44,
    "avgRevenue": 614.82,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 137,
    "totalRevenue": 92664.5,
    "totalOrders": 46,
    "avgRevenue": 676.38,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 137,
    "totalRevenue": 63923.17,
    "totalOrders": 31,
    "avgRevenue": 466.59,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 137,
    "totalRevenue": 29295.88,
    "totalOrders": 12,
    "avgRevenue": 213.84,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 141,
    "totalRevenue": 18128.1,
    "totalOrders": 10,
    "avgRevenue": 128.57,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 141,
    "totalRevenue": 8552.06,
    "totalOrders": 6,
    "avgRevenue": 60.65,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 141,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 9.91,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 141,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 141,
    "totalRevenue": 1817.36,
    "totalOrders": 1,
    "avgRevenue": 12.89,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 141,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 141,
    "totalRevenue": 27366.09,
    "totalOrders": 15,
    "avgRevenue": 194.09,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 141,
    "totalRevenue": 31508.27,
    "totalOrders": 19,
    "avgRevenue": 223.46,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 141,
    "totalRevenue": 47175.63,
    "totalOrders": 28,
    "avgRevenue": 334.58,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 141,
    "totalRevenue": 85193.89,
    "totalOrders": 46,
    "avgRevenue": 604.21,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 141,
    "totalRevenue": 110592.58,
    "totalOrders": 51,
    "avgRevenue": 784.34,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 141,
    "totalRevenue": 72813.28,
    "totalOrders": 43,
    "avgRevenue": 516.41,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 141,
    "totalRevenue": 88085.33,
    "totalOrders": 44,
    "avgRevenue": 624.72,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 141,
    "totalRevenue": 97305.58,
    "totalOrders": 49,
    "avgRevenue": 690.11,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 141,
    "totalRevenue": 94743.86,
    "totalOrders": 47,
    "avgRevenue": 671.94,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 141,
    "totalRevenue": 78390.13,
    "totalOrders": 42,
    "avgRevenue": 555.96,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 141,
    "totalRevenue": 80077.68,
    "totalOrders": 43,
    "avgRevenue": 567.93,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 141,
    "totalRevenue": 95831.05,
    "totalOrders": 46,
    "avgRevenue": 679.65,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 141,
    "totalRevenue": 51825.61,
    "totalOrders": 25,
    "avgRevenue": 367.56,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 141,
    "totalRevenue": 52518.19,
    "totalOrders": 29,
    "avgRevenue": 372.47,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 141,
    "totalRevenue": 70055.28,
    "totalOrders": 41,
    "avgRevenue": 496.85,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 141,
    "totalRevenue": 79966.06,
    "totalOrders": 35,
    "avgRevenue": 567.14,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 141,
    "totalRevenue": 67253.73,
    "totalOrders": 32,
    "avgRevenue": 476.98,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 141,
    "totalRevenue": 36630.59,
    "totalOrders": 18,
    "avgRevenue": 259.79,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 133,
    "totalRevenue": 22132.31,
    "totalOrders": 7,
    "avgRevenue": 166.41,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 133,
    "totalRevenue": 1503.3,
    "totalOrders": 1,
    "avgRevenue": 11.3,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 133,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 133,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 133,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 133,
    "totalRevenue": 3785.12,
    "totalOrders": 2,
    "avgRevenue": 28.46,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 133,
    "totalRevenue": 18628.09,
    "totalOrders": 8,
    "avgRevenue": 140.06,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 133,
    "totalRevenue": 37547.7,
    "totalOrders": 23,
    "avgRevenue": 282.31,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 133,
    "totalRevenue": 62147.14,
    "totalOrders": 32,
    "avgRevenue": 467.27,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 133,
    "totalRevenue": 81814.82,
    "totalOrders": 40,
    "avgRevenue": 615.15,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 133,
    "totalRevenue": 87975.93,
    "totalOrders": 48,
    "avgRevenue": 661.47,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 133,
    "totalRevenue": 89289.8,
    "totalOrders": 46,
    "avgRevenue": 671.35,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 133,
    "totalRevenue": 55538.02,
    "totalOrders": 29,
    "avgRevenue": 417.58,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 133,
    "totalRevenue": 78609.96,
    "totalOrders": 41,
    "avgRevenue": 591.05,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 133,
    "totalRevenue": 71771.52,
    "totalOrders": 38,
    "avgRevenue": 539.64,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 133,
    "totalRevenue": 76083.5,
    "totalOrders": 37,
    "avgRevenue": 572.06,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 133,
    "totalRevenue": 49468.65,
    "totalOrders": 32,
    "avgRevenue": 371.94,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 133,
    "totalRevenue": 42259.86,
    "totalOrders": 22,
    "avgRevenue": 317.74,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 133,
    "totalRevenue": 61134.39,
    "totalOrders": 31,
    "avgRevenue": 459.66,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 133,
    "totalRevenue": 49988.43,
    "totalOrders": 26,
    "avgRevenue": 375.85,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 133,
    "totalRevenue": 70194.24,
    "totalOrders": 40,
    "avgRevenue": 527.78,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 133,
    "totalRevenue": 64190.09,
    "totalOrders": 36,
    "avgRevenue": 482.63,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 133,
    "totalRevenue": 53173.74,
    "totalOrders": 28,
    "avgRevenue": 399.8,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 133,
    "totalRevenue": 24492.57,
    "totalOrders": 14,
    "avgRevenue": 184.15,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 128,
    "totalRevenue": 2833.06,
    "totalOrders": 2,
    "avgRevenue": 22.13,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 128,
    "totalRevenue": 3221.49,
    "totalOrders": 2,
    "avgRevenue": 25.17,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 128,
    "totalRevenue": 983.47,
    "totalOrders": 1,
    "avgRevenue": 7.68,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 128,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 128,
    "totalRevenue": 1238.84,
    "totalOrders": 1,
    "avgRevenue": 9.68,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 128,
    "totalRevenue": 8483.46,
    "totalOrders": 4,
    "avgRevenue": 66.28,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 128,
    "totalRevenue": 19181,
    "totalOrders": 8,
    "avgRevenue": 149.85,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 128,
    "totalRevenue": 40472.01,
    "totalOrders": 19,
    "avgRevenue": 316.19,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 128,
    "totalRevenue": 52679.47,
    "totalOrders": 28,
    "avgRevenue": 411.56,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 128,
    "totalRevenue": 51223.1,
    "totalOrders": 28,
    "avgRevenue": 400.18,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 128,
    "totalRevenue": 63232.26,
    "totalOrders": 33,
    "avgRevenue": 494,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 128,
    "totalRevenue": 83298.34,
    "totalOrders": 40,
    "avgRevenue": 650.77,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 128,
    "totalRevenue": 71172.9,
    "totalOrders": 36,
    "avgRevenue": 556.04,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 128,
    "totalRevenue": 93631.07,
    "totalOrders": 49,
    "avgRevenue": 731.49,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 128,
    "totalRevenue": 83695.06,
    "totalOrders": 37,
    "avgRevenue": 653.87,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 128,
    "totalRevenue": 80032.23,
    "totalOrders": 40,
    "avgRevenue": 625.25,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 128,
    "totalRevenue": 62642.41,
    "totalOrders": 32,
    "avgRevenue": 489.39,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 128,
    "totalRevenue": 59943.83,
    "totalOrders": 32,
    "avgRevenue": 468.31,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 128,
    "totalRevenue": 40071.91,
    "totalOrders": 20,
    "avgRevenue": 313.06,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 128,
    "totalRevenue": 38652.08,
    "totalOrders": 21,
    "avgRevenue": 301.97,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 128,
    "totalRevenue": 64502.48,
    "totalOrders": 26,
    "avgRevenue": 503.93,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 128,
    "totalRevenue": 55364.46,
    "totalOrders": 26,
    "avgRevenue": 432.53,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 128,
    "totalRevenue": 47300.02,
    "totalOrders": 21,
    "avgRevenue": 369.53,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 128,
    "totalRevenue": 29938.85,
    "totalOrders": 13,
    "avgRevenue": 233.9,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 124,
    "totalRevenue": 3466.95,
    "totalOrders": 2,
    "avgRevenue": 27.96,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 124,
    "totalRevenue": 2706.62,
    "totalOrders": 1,
    "avgRevenue": 21.83,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 124,
    "totalRevenue": 2719.01,
    "totalOrders": 1,
    "avgRevenue": 21.93,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 124,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 124,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 124,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 124,
    "totalRevenue": 7799.99,
    "totalOrders": 2,
    "avgRevenue": 62.9,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 124,
    "totalRevenue": 30415.75,
    "totalOrders": 14,
    "avgRevenue": 245.29,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 124,
    "totalRevenue": 48443.81,
    "totalOrders": 23,
    "avgRevenue": 390.68,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 124,
    "totalRevenue": 65241.84,
    "totalOrders": 25,
    "avgRevenue": 526.14,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 124,
    "totalRevenue": 42090.4,
    "totalOrders": 20,
    "avgRevenue": 339.44,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 124,
    "totalRevenue": 55185.38,
    "totalOrders": 26,
    "avgRevenue": 445.04,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 124,
    "totalRevenue": 41026.48,
    "totalOrders": 23,
    "avgRevenue": 330.86,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 124,
    "totalRevenue": 36750.52,
    "totalOrders": 20,
    "avgRevenue": 296.38,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 124,
    "totalRevenue": 75823.31,
    "totalOrders": 37,
    "avgRevenue": 611.48,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 124,
    "totalRevenue": 38847.95,
    "totalOrders": 19,
    "avgRevenue": 313.29,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 124,
    "totalRevenue": 52046.37,
    "totalOrders": 26,
    "avgRevenue": 419.73,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 124,
    "totalRevenue": 45956.19,
    "totalOrders": 21,
    "avgRevenue": 370.61,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 124,
    "totalRevenue": 43413.29,
    "totalOrders": 24,
    "avgRevenue": 350.11,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 124,
    "totalRevenue": 52514.9,
    "totalOrders": 26,
    "avgRevenue": 423.51,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 124,
    "totalRevenue": 62033.09,
    "totalOrders": 29,
    "avgRevenue": 500.27,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 124,
    "totalRevenue": 67550.91,
    "totalOrders": 31,
    "avgRevenue": 544.77,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 124,
    "totalRevenue": 61808.43,
    "totalOrders": 34,
    "avgRevenue": 498.46,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 124,
    "totalRevenue": 32662.8,
    "totalOrders": 17,
    "avgRevenue": 263.41,
    "avgOrders": 0.14
  }
];
