// Auto-generated by scripts/updateData.js — last update: 2026-09-25
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZProdejna: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 2,
    "totalRevenue": 1809.92,
    "totalOrders": 1,
    "avgRevenue": 904.96,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 2,
    "totalRevenue": 2388.43,
    "totalOrders": 1,
    "avgRevenue": 1194.21,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 2,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 31,
    "totalRevenue": 426.44,
    "totalOrders": 1,
    "avgRevenue": 13.76,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 31,
    "totalRevenue": 2447.11,
    "totalOrders": 1,
    "avgRevenue": 78.94,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 31,
    "totalRevenue": 2305.79,
    "totalOrders": 1,
    "avgRevenue": 74.38,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 31,
    "totalRevenue": 5074.38,
    "totalOrders": 3,
    "avgRevenue": 163.69,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 31,
    "totalRevenue": 37848.03,
    "totalOrders": 18,
    "avgRevenue": 1220.9,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 31,
    "totalRevenue": 28041.34,
    "totalOrders": 17,
    "avgRevenue": 904.56,
    "avgOrders": 0.55
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 31,
    "totalRevenue": 28632.25,
    "totalOrders": 13,
    "avgRevenue": 923.62,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 31,
    "totalRevenue": 1396.69,
    "totalOrders": 1,
    "avgRevenue": 45.05,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 46,
    "totalRevenue": 2437.19,
    "totalOrders": 1,
    "avgRevenue": 52.98,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 46,
    "totalRevenue": 17571.73,
    "totalOrders": 9,
    "avgRevenue": 381.99,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 46,
    "totalRevenue": 33890.11,
    "totalOrders": 14,
    "avgRevenue": 736.74,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 46,
    "totalRevenue": 26820.67,
    "totalOrders": 13,
    "avgRevenue": 583.06,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 46,
    "totalRevenue": 13238.51,
    "totalOrders": 6,
    "avgRevenue": 287.79,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 46,
    "totalRevenue": 19724.82,
    "totalOrders": 9,
    "avgRevenue": 428.8,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 46,
    "totalRevenue": 15527.28,
    "totalOrders": 8,
    "avgRevenue": 337.55,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 46,
    "totalRevenue": 44498.7,
    "totalOrders": 25,
    "avgRevenue": 967.36,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 46,
    "totalRevenue": 17875.2,
    "totalOrders": 10,
    "avgRevenue": 388.59,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 46,
    "totalRevenue": 1114.88,
    "totalOrders": 1,
    "avgRevenue": 24.24,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 58,
    "totalRevenue": 17821.48,
    "totalOrders": 9,
    "avgRevenue": 307.27,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 58,
    "totalRevenue": 27478.71,
    "totalOrders": 14,
    "avgRevenue": 473.77,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 58,
    "totalRevenue": 19866.63,
    "totalOrders": 11,
    "avgRevenue": 342.53,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 58,
    "totalRevenue": 11938.86,
    "totalOrders": 6,
    "avgRevenue": 205.84,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 58,
    "totalRevenue": 31786.3,
    "totalOrders": 15,
    "avgRevenue": 548.04,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 58,
    "totalRevenue": 57954.74,
    "totalOrders": 25,
    "avgRevenue": 999.22,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 58,
    "totalRevenue": 44335.74,
    "totalOrders": 21,
    "avgRevenue": 764.41,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 58,
    "totalRevenue": 43351.96,
    "totalOrders": 20,
    "avgRevenue": 747.45,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 58,
    "totalRevenue": 28801.67,
    "totalOrders": 11,
    "avgRevenue": 496.58,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 58,
    "totalRevenue": 2850.41,
    "totalOrders": 1,
    "avgRevenue": 49.15,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 58,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 48,
    "totalRevenue": 12973.55,
    "totalOrders": 6,
    "avgRevenue": 270.28,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 48,
    "totalRevenue": 35966.96,
    "totalOrders": 16,
    "avgRevenue": 749.31,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 48,
    "totalRevenue": 30633.09,
    "totalOrders": 11,
    "avgRevenue": 638.19,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 48,
    "totalRevenue": 3803.37,
    "totalOrders": 3,
    "avgRevenue": 79.24,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 48,
    "totalRevenue": 31255.38,
    "totalOrders": 14,
    "avgRevenue": 651.15,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 48,
    "totalRevenue": 20541.34,
    "totalOrders": 10,
    "avgRevenue": 427.94,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 48,
    "totalRevenue": 47968.63,
    "totalOrders": 22,
    "avgRevenue": 999.35,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 48,
    "totalRevenue": 2594.21,
    "totalOrders": 2,
    "avgRevenue": 54.05,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 55,
    "totalRevenue": 13481.81,
    "totalOrders": 8,
    "avgRevenue": 245.12,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 55,
    "totalRevenue": 36679.41,
    "totalOrders": 16,
    "avgRevenue": 666.9,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 55,
    "totalRevenue": 31043.26,
    "totalOrders": 14,
    "avgRevenue": 564.42,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 55,
    "totalRevenue": 14781.83,
    "totalOrders": 6,
    "avgRevenue": 268.76,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 55,
    "totalRevenue": 41186.86,
    "totalOrders": 19,
    "avgRevenue": 748.85,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 55,
    "totalRevenue": 31151.25,
    "totalOrders": 11,
    "avgRevenue": 566.39,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 55,
    "totalRevenue": 50081.84,
    "totalOrders": 24,
    "avgRevenue": 910.58,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 55,
    "totalRevenue": 36608.27,
    "totalOrders": 20,
    "avgRevenue": 665.6,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 55,
    "totalRevenue": 14684.31,
    "totalOrders": 8,
    "avgRevenue": 266.99,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 55,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 2075.21,
    "totalOrders": 1,
    "avgRevenue": 518.8,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 2040.5,
    "totalOrders": 2,
    "avgRevenue": 510.13,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 1479.34,
    "totalOrders": 1,
    "avgRevenue": 369.84,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  }
];
