// Auto-generated by scripts/updateData.js — last update: 2026-05-02
// CZ: daily margin data (CZK). purchaseCost = nákupní cena (buy_price × quantity), revenue = tržby bez DPH.

export interface MarginDailyRecord {
  date: string;
  purchaseCost: number;
  revenue: number;
}

export const marginDataCZ: MarginDailyRecord[] = [
  {
    "date": "2023-03-03",
    "purchaseCost": 3817,
    "revenue": 6363.28
  },
  {
    "date": "2023-03-06",
    "purchaseCost": 2428,
    "revenue": 4743.8
  },
  {
    "date": "2023-03-07",
    "purchaseCost": 561,
    "revenue": 990.91
  },
  {
    "date": "2023-03-12",
    "purchaseCost": 319,
    "revenue": 329.75
  },
  {
    "date": "2023-03-22",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-03-28",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-03-29",
    "purchaseCost": 626,
    "revenue": 1250.99
  },
  {
    "date": "2023-04-01",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-04-05",
    "purchaseCost": 133,
    "revenue": 214.05
  },
  {
    "date": "2023-04-10",
    "purchaseCost": 718,
    "revenue": 1467.23
  },
  {
    "date": "2023-04-12",
    "purchaseCost": 4153,
    "revenue": 5882.65
  },
  {
    "date": "2023-04-16",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-04-17",
    "purchaseCost": 1164,
    "revenue": 2181.82
  },
  {
    "date": "2023-04-20",
    "purchaseCost": 1252,
    "revenue": 1501.66
  },
  {
    "date": "2023-04-23",
    "purchaseCost": 4140,
    "revenue": 5750.41
  },
  {
    "date": "2023-04-26",
    "purchaseCost": 1876,
    "revenue": 2636.36
  },
  {
    "date": "2023-04-29",
    "purchaseCost": 3589,
    "revenue": 4577.68
  },
  {
    "date": "2023-04-30",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-05-01",
    "purchaseCost": 1499,
    "revenue": 1784.3
  },
  {
    "date": "2023-05-02",
    "purchaseCost": 1876,
    "revenue": 2636.36
  },
  {
    "date": "2023-05-03",
    "purchaseCost": 1876,
    "revenue": 2636.36
  },
  {
    "date": "2023-05-04",
    "purchaseCost": 2060,
    "revenue": 2875.21
  },
  {
    "date": "2023-05-06",
    "purchaseCost": 786,
    "revenue": 1560.33
  },
  {
    "date": "2023-05-08",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2023-05-09",
    "purchaseCost": 593,
    "revenue": 983.47
  },
  {
    "date": "2023-05-10",
    "purchaseCost": 1186,
    "revenue": 1153.72
  },
  {
    "date": "2023-05-11",
    "purchaseCost": 1473,
    "revenue": 2404.13
  },
  {
    "date": "2023-05-12",
    "purchaseCost": 2017,
    "revenue": 2809.09
  },
  {
    "date": "2023-05-13",
    "purchaseCost": 668,
    "revenue": 1240.55
  },
  {
    "date": "2023-05-14",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-05-15",
    "purchaseCost": 2578,
    "revenue": 3900
  },
  {
    "date": "2023-05-21",
    "purchaseCost": 1122,
    "revenue": 2181.82
  },
  {
    "date": "2023-05-22",
    "purchaseCost": 3204,
    "revenue": 5072.73
  },
  {
    "date": "2023-05-24",
    "purchaseCost": 1876,
    "revenue": 2478.51
  },
  {
    "date": "2023-05-26",
    "purchaseCost": 1122,
    "revenue": 2066.12
  },
  {
    "date": "2023-05-28",
    "purchaseCost": 561,
    "revenue": 1090.91
  },
  {
    "date": "2023-05-29",
    "purchaseCost": 561,
    "revenue": 1033.06
  },
  {
    "date": "2023-05-30",
    "purchaseCost": 1858,
    "revenue": 2850.42
  },
  {
    "date": "2023-06-01",
    "purchaseCost": 1297,
    "revenue": 1817.36
  },
  {
    "date": "2023-06-02",
    "purchaseCost": 1297,
    "revenue": 1817.36
  },
  {
    "date": "2023-06-04",
    "purchaseCost": 1122,
    "revenue": 1917.36
  },
  {
    "date": "2023-06-05",
    "purchaseCost": 2324,
    "revenue": 3970.37
  },
  {
    "date": "2023-06-06",
    "purchaseCost": 561,
    "revenue": 958.68
  },
  {
    "date": "2023-06-07",
    "purchaseCost": 3671,
    "revenue": 5582.65
  },
  {
    "date": "2023-06-08",
    "purchaseCost": 5712,
    "revenue": 8106.62
  },
  {
    "date": "2023-06-09",
    "purchaseCost": 1985,
    "revenue": 2776.04
  },
  {
    "date": "2023-06-10",
    "purchaseCost": 4746,
    "revenue": 7024.8
  },
  {
    "date": "2023-06-11",
    "purchaseCost": 5961,
    "revenue": 7129.78
  },
  {
    "date": "2023-06-12",
    "purchaseCost": 4106,
    "revenue": 5701.66
  },
  {
    "date": "2023-06-13",
    "purchaseCost": 6004,
    "revenue": 8503.31
  },
  {
    "date": "2023-06-14",
    "purchaseCost": 688,
    "revenue": 958.68
  },
  {
    "date": "2023-06-17",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-06-18",
    "purchaseCost": 2187,
    "revenue": 2627.27
  },
  {
    "date": "2023-06-19",
    "purchaseCost": 2064,
    "revenue": 2876.04
  },
  {
    "date": "2023-06-20",
    "purchaseCost": 1759,
    "revenue": 2114.88
  },
  {
    "date": "2023-06-21",
    "purchaseCost": 3440,
    "revenue": 4793.4
  },
  {
    "date": "2023-06-22",
    "purchaseCost": 3345,
    "revenue": 4595.05
  },
  {
    "date": "2023-06-24",
    "purchaseCost": 1987,
    "revenue": 2873.56
  },
  {
    "date": "2023-06-25",
    "purchaseCost": 2064,
    "revenue": 2876.04
  },
  {
    "date": "2023-06-26",
    "purchaseCost": 9166,
    "revenue": 12396.8
  },
  {
    "date": "2023-06-27",
    "purchaseCost": 3111,
    "revenue": 4270.45
  },
  {
    "date": "2023-06-28",
    "purchaseCost": 3393,
    "revenue": 4726.45
  },
  {
    "date": "2023-06-29",
    "purchaseCost": 2187,
    "revenue": 2528.1
  },
  {
    "date": "2023-06-30",
    "purchaseCost": 3468,
    "revenue": 4271.9
  },
  {
    "date": "2023-07-01",
    "purchaseCost": 1816,
    "revenue": 2079.34
  },
  {
    "date": "2023-07-02",
    "purchaseCost": 4721,
    "revenue": 6512.41
  },
  {
    "date": "2023-07-03",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-07-04",
    "purchaseCost": 1281,
    "revenue": 2110.31
  },
  {
    "date": "2023-07-05",
    "purchaseCost": 4386,
    "revenue": 5825.63
  },
  {
    "date": "2023-07-06",
    "purchaseCost": 3454,
    "revenue": 4685.12
  },
  {
    "date": "2023-07-07",
    "purchaseCost": 2766,
    "revenue": 3676.86
  },
  {
    "date": "2023-07-08",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-07-09",
    "purchaseCost": 4238,
    "revenue": 5379.37
  },
  {
    "date": "2023-07-10",
    "purchaseCost": 4033,
    "revenue": 5578.52
  },
  {
    "date": "2023-07-11",
    "purchaseCost": 6629,
    "revenue": 9173.6
  },
  {
    "date": "2023-07-12",
    "purchaseCost": 9090,
    "revenue": 11833.87
  },
  {
    "date": "2023-07-13",
    "purchaseCost": 7805,
    "revenue": 10223.25
  },
  {
    "date": "2023-07-14",
    "purchaseCost": 5648,
    "revenue": 7347.15
  },
  {
    "date": "2023-07-15",
    "purchaseCost": 2677,
    "revenue": 3616.72
  },
  {
    "date": "2023-07-16",
    "purchaseCost": 4647,
    "revenue": 6347.97
  },
  {
    "date": "2023-07-17",
    "purchaseCost": 6201,
    "revenue": 8060.48
  },
  {
    "date": "2023-07-18",
    "purchaseCost": 8613,
    "revenue": 10768.69
  },
  {
    "date": "2023-07-19",
    "purchaseCost": 8122,
    "revenue": 10105.78
  },
  {
    "date": "2023-07-20",
    "purchaseCost": 3786,
    "revenue": 4977.82
  },
  {
    "date": "2023-07-21",
    "purchaseCost": 2780,
    "revenue": 3288.43
  },
  {
    "date": "2023-07-22",
    "purchaseCost": 1281,
    "revenue": 1818.18
  },
  {
    "date": "2023-07-23",
    "purchaseCost": 8159,
    "revenue": 11035.29
  },
  {
    "date": "2023-07-24",
    "purchaseCost": 4112,
    "revenue": 5065.69
  },
  {
    "date": "2023-07-25",
    "purchaseCost": 645,
    "revenue": 866.94
  },
  {
    "date": "2023-07-26",
    "purchaseCost": 3768.96,
    "revenue": 3883.47
  },
  {
    "date": "2023-07-27",
    "purchaseCost": 6327,
    "revenue": 7112.4
  },
  {
    "date": "2023-07-28",
    "purchaseCost": 4561,
    "revenue": 5800.82
  },
  {
    "date": "2023-07-29",
    "purchaseCost": 5870,
    "revenue": 7459.81
  },
  {
    "date": "2023-07-30",
    "purchaseCost": 1311,
    "revenue": 1576.86
  },
  {
    "date": "2023-07-31",
    "purchaseCost": 6231,
    "revenue": 8709.9
  },
  {
    "date": "2023-08-01",
    "purchaseCost": 1855,
    "revenue": 2433.19
  },
  {
    "date": "2023-08-02",
    "purchaseCost": 6882,
    "revenue": 9137.19
  },
  {
    "date": "2023-08-03",
    "purchaseCost": 1334,
    "revenue": 1952.55
  },
  {
    "date": "2023-08-04",
    "purchaseCost": 4232,
    "revenue": 5746.42
  },
  {
    "date": "2023-08-05",
    "purchaseCost": 4417,
    "revenue": 6176.99
  },
  {
    "date": "2023-08-06",
    "purchaseCost": 1440,
    "revenue": 1983.47
  },
  {
    "date": "2023-08-07",
    "purchaseCost": 688,
    "revenue": 896.69
  },
  {
    "date": "2023-08-08",
    "purchaseCost": 4904,
    "revenue": 6742.14
  },
  {
    "date": "2023-08-09",
    "purchaseCost": 775,
    "revenue": 964.69
  },
  {
    "date": "2023-08-10",
    "purchaseCost": 644,
    "revenue": 858.68
  },
  {
    "date": "2023-08-12",
    "purchaseCost": 2017,
    "revenue": 2809.09
  },
  {
    "date": "2023-08-13",
    "purchaseCost": 2187,
    "revenue": 2701.65
  },
  {
    "date": "2023-08-14",
    "purchaseCost": 3230,
    "revenue": 4444.63
  },
  {
    "date": "2023-08-15",
    "purchaseCost": 2017,
    "revenue": 2809.09
  },
  {
    "date": "2023-08-16",
    "purchaseCost": 1946,
    "revenue": 2602.84
  },
  {
    "date": "2023-08-17",
    "purchaseCost": 688,
    "revenue": 1115.7
  },
  {
    "date": "2023-08-20",
    "purchaseCost": 3251,
    "revenue": 4702.49
  },
  {
    "date": "2023-08-21",
    "purchaseCost": 629,
    "revenue": 835.55
  },
  {
    "date": "2023-08-22",
    "purchaseCost": 2843,
    "revenue": 3912.41
  },
  {
    "date": "2023-08-23",
    "purchaseCost": 2092,
    "revenue": 2387.6
  },
  {
    "date": "2023-08-24",
    "purchaseCost": 2666,
    "revenue": 3957.03
  },
  {
    "date": "2023-08-25",
    "purchaseCost": 3811,
    "revenue": 4667.76
  },
  {
    "date": "2023-08-26",
    "purchaseCost": 1281,
    "revenue": 1867.77
  },
  {
    "date": "2023-08-27",
    "purchaseCost": 658,
    "revenue": 891.73
  },
  {
    "date": "2023-08-28",
    "purchaseCost": 2017,
    "revenue": 2809.09
  },
  {
    "date": "2023-08-29",
    "purchaseCost": 734,
    "revenue": 914.69
  },
  {
    "date": "2023-08-30",
    "purchaseCost": 1440,
    "revenue": 1983.47
  },
  {
    "date": "2023-08-31",
    "purchaseCost": 1836,
    "revenue": 1922.88
  },
  {
    "date": "2023-09-01",
    "purchaseCost": 1186,
    "revenue": 1553.72
  },
  {
    "date": "2023-09-02",
    "purchaseCost": 1779,
    "revenue": 2338.84
  },
  {
    "date": "2023-09-03",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2023-09-05",
    "purchaseCost": 4235,
    "revenue": 5991.75
  },
  {
    "date": "2023-09-06",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2023-09-07",
    "purchaseCost": 2255,
    "revenue": 2891.73
  },
  {
    "date": "2023-09-08",
    "purchaseCost": 1499,
    "revenue": 1569.42
  },
  {
    "date": "2023-09-10",
    "purchaseCost": 1803,
    "revenue": 2189.25
  },
  {
    "date": "2023-09-11",
    "purchaseCost": 1268,
    "revenue": 1648.07
  },
  {
    "date": "2023-09-12",
    "purchaseCost": 3699,
    "revenue": 4884.31
  },
  {
    "date": "2023-09-13",
    "purchaseCost": 2044,
    "revenue": 2559.51
  },
  {
    "date": "2023-09-14",
    "purchaseCost": 3218,
    "revenue": 4438.89
  },
  {
    "date": "2023-09-15",
    "purchaseCost": 593,
    "revenue": 785.12
  },
  {
    "date": "2023-09-17",
    "purchaseCost": 688,
    "revenue": 1090.91
  },
  {
    "date": "2023-09-18",
    "purchaseCost": 1876,
    "revenue": 2636.36
  },
  {
    "date": "2023-09-19",
    "purchaseCost": 688,
    "revenue": 1090.91
  },
  {
    "date": "2023-09-20",
    "purchaseCost": 1759,
    "revenue": 1817.36
  },
  {
    "date": "2023-09-21",
    "purchaseCost": 1304,
    "revenue": 1704.15
  },
  {
    "date": "2023-09-26",
    "purchaseCost": 688,
    "revenue": 1090.91
  },
  {
    "date": "2023-09-28",
    "purchaseCost": 102,
    "revenue": 196.69
  },
  {
    "date": "2023-10-04",
    "purchaseCost": 1186,
    "revenue": 1561.98
  },
  {
    "date": "2023-10-05",
    "purchaseCost": 1376,
    "revenue": 2181.82
  },
  {
    "date": "2023-10-08",
    "purchaseCost": 174,
    "revenue": 205.79
  },
  {
    "date": "2023-10-10",
    "purchaseCost": 593,
    "revenue": 785.12
  },
  {
    "date": "2023-10-12",
    "purchaseCost": 688,
    "revenue": 1090.91
  },
  {
    "date": "2023-10-13",
    "purchaseCost": 688,
    "revenue": 1090.91
  },
  {
    "date": "2023-10-18",
    "purchaseCost": 431,
    "revenue": 650.41
  },
  {
    "date": "2023-10-19",
    "purchaseCost": 3893,
    "revenue": 5122.32
  },
  {
    "date": "2023-10-20",
    "purchaseCost": 1499,
    "revenue": 1610.74
  },
  {
    "date": "2023-10-23",
    "purchaseCost": 2781,
    "revenue": 3470.25
  },
  {
    "date": "2023-10-24",
    "purchaseCost": 319,
    "revenue": 313.22
  },
  {
    "date": "2023-10-31",
    "purchaseCost": 1363,
    "revenue": 1854.68
  },
  {
    "date": "2023-11-01",
    "purchaseCost": 4837,
    "revenue": 6833.89
  },
  {
    "date": "2023-11-02",
    "purchaseCost": 2191,
    "revenue": 2758.68
  },
  {
    "date": "2023-11-04",
    "purchaseCost": 3527,
    "revenue": 4340.16
  },
  {
    "date": "2023-11-06",
    "purchaseCost": 1985,
    "revenue": 2776.04
  },
  {
    "date": "2023-11-07",
    "purchaseCost": 4706,
    "revenue": 6456.68
  },
  {
    "date": "2023-11-08",
    "purchaseCost": 2042,
    "revenue": 2627.28
  },
  {
    "date": "2023-11-10",
    "purchaseCost": 688,
    "revenue": 958.68
  },
  {
    "date": "2023-11-11",
    "purchaseCost": 2895,
    "revenue": 3517.21
  },
  {
    "date": "2023-11-12",
    "purchaseCost": 4910,
    "revenue": 6163.64
  },
  {
    "date": "2023-11-13",
    "purchaseCost": 1376,
    "revenue": 2049.59
  },
  {
    "date": "2023-11-14",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-11-15",
    "purchaseCost": 297,
    "revenue": 493.39
  },
  {
    "date": "2023-11-18",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-11-19",
    "purchaseCost": 1281,
    "revenue": 1735.54
  },
  {
    "date": "2023-11-20",
    "purchaseCost": 0,
    "revenue": 297.52
  },
  {
    "date": "2023-11-24",
    "purchaseCost": 688,
    "revenue": 958.68
  },
  {
    "date": "2023-11-27",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-11-28",
    "purchaseCost": 688,
    "revenue": 958.68
  },
  {
    "date": "2023-11-29",
    "purchaseCost": 133,
    "revenue": 238.84
  },
  {
    "date": "2023-11-30",
    "purchaseCost": 1898,
    "revenue": 2362.81
  },
  {
    "date": "2023-12-01",
    "purchaseCost": 2064,
    "revenue": 2876.04
  },
  {
    "date": "2023-12-03",
    "purchaseCost": 1376,
    "revenue": 1917.36
  },
  {
    "date": "2023-12-04",
    "purchaseCost": 2398,
    "revenue": 3328.1
  },
  {
    "date": "2023-12-05",
    "purchaseCost": 645,
    "revenue": 875.21
  },
  {
    "date": "2023-12-06",
    "purchaseCost": 2064,
    "revenue": 2876.04
  },
  {
    "date": "2023-12-08",
    "purchaseCost": 468,
    "revenue": 885.12
  },
  {
    "date": "2023-12-09",
    "purchaseCost": 2064,
    "revenue": 2876.04
  },
  {
    "date": "2023-12-10",
    "purchaseCost": 696,
    "revenue": 1166.13
  },
  {
    "date": "2023-12-11",
    "purchaseCost": 212,
    "revenue": 371.07
  },
  {
    "date": "2023-12-12",
    "purchaseCost": 3473,
    "revenue": 4146.28
  },
  {
    "date": "2023-12-13",
    "purchaseCost": 4015,
    "revenue": 5483.49
  },
  {
    "date": "2023-12-14",
    "purchaseCost": 3040,
    "revenue": 4064.47
  },
  {
    "date": "2023-12-15",
    "purchaseCost": 319,
    "revenue": 329.75
  },
  {
    "date": "2023-12-16",
    "purchaseCost": 319,
    "revenue": 329.75
  },
  {
    "date": "2023-12-17",
    "purchaseCost": 1874,
    "revenue": 2512.4
  },
  {
    "date": "2023-12-18",
    "purchaseCost": 2853.82,
    "revenue": 3766.48
  },
  {
    "date": "2023-12-21",
    "purchaseCost": 688,
    "revenue": 1090.91
  },
  {
    "date": "2023-12-26",
    "purchaseCost": 2017,
    "revenue": 2809.09
  },
  {
    "date": "2023-12-30",
    "purchaseCost": 847,
    "revenue": 1198.35
  },
  {
    "date": "2024-01-04",
    "purchaseCost": 174,
    "revenue": 205.79
  },
  {
    "date": "2024-01-05",
    "purchaseCost": 847,
    "revenue": 1198.35
  },
  {
    "date": "2024-01-08",
    "purchaseCost": 104,
    "revenue": 123.14
  },
  {
    "date": "2024-01-10",
    "purchaseCost": 1535,
    "revenue": 2289.26
  },
  {
    "date": "2024-01-15",
    "purchaseCost": 348,
    "revenue": 411.57
  },
  {
    "date": "2024-01-20",
    "purchaseCost": 354,
    "revenue": 395.04
  },
  {
    "date": "2024-01-22",
    "purchaseCost": 266,
    "revenue": 477.68
  },
  {
    "date": "2024-01-25",
    "purchaseCost": 717,
    "revenue": 857.05
  },
  {
    "date": "2024-01-28",
    "purchaseCost": 2817,
    "revenue": 3634.71
  },
  {
    "date": "2024-02-01",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-02-07",
    "purchaseCost": 382,
    "revenue": 488.39
  },
  {
    "date": "2024-02-08",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-02-11",
    "purchaseCost": 4510,
    "revenue": 5776.04
  },
  {
    "date": "2024-02-13",
    "purchaseCost": 2576,
    "revenue": 3504.14
  },
  {
    "date": "2024-02-16",
    "purchaseCost": 1482,
    "revenue": 2083.45
  },
  {
    "date": "2024-02-19",
    "purchaseCost": 3458,
    "revenue": 4611.58
  },
  {
    "date": "2024-02-23",
    "purchaseCost": 174,
    "revenue": 222.32
  },
  {
    "date": "2024-02-25",
    "purchaseCost": 1729,
    "revenue": 2305.79
  },
  {
    "date": "2024-02-26",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-02-27",
    "purchaseCost": 1803,
    "revenue": 2304.96
  },
  {
    "date": "2024-03-02",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-03-03",
    "purchaseCost": 1963,
    "revenue": 2642.97
  },
  {
    "date": "2024-03-05",
    "purchaseCost": 1689,
    "revenue": 1899.17
  },
  {
    "date": "2024-03-07",
    "purchaseCost": 3179,
    "revenue": 3547.82
  },
  {
    "date": "2024-03-08",
    "purchaseCost": 4820,
    "revenue": 6353.72
  },
  {
    "date": "2024-03-09",
    "purchaseCost": 1499,
    "revenue": 1610.74
  },
  {
    "date": "2024-03-11",
    "purchaseCost": 2170,
    "revenue": 3046.18
  },
  {
    "date": "2024-03-13",
    "purchaseCost": 1803,
    "revenue": 2304.96
  },
  {
    "date": "2024-03-16",
    "purchaseCost": 3086,
    "revenue": 3875.2
  },
  {
    "date": "2024-03-17",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-03-18",
    "purchaseCost": 3086,
    "revenue": 4040.49
  },
  {
    "date": "2024-03-19",
    "purchaseCost": 5927,
    "revenue": 6847.41
  },
  {
    "date": "2024-03-20",
    "purchaseCost": 2001,
    "revenue": 2883.41
  },
  {
    "date": "2024-03-21",
    "purchaseCost": 663,
    "revenue": 1238.84
  },
  {
    "date": "2024-03-22",
    "purchaseCost": 2889,
    "revenue": 4295.86
  },
  {
    "date": "2024-03-23",
    "purchaseCost": 1297,
    "revenue": 1569.42
  },
  {
    "date": "2024-03-24",
    "purchaseCost": 1876,
    "revenue": 2471.07
  },
  {
    "date": "2024-03-27",
    "purchaseCost": 2023,
    "revenue": 2350.45
  },
  {
    "date": "2024-03-29",
    "purchaseCost": 1734,
    "revenue": 2477.68
  },
  {
    "date": "2024-03-30",
    "purchaseCost": 1330,
    "revenue": 2256.2
  },
  {
    "date": "2024-03-31",
    "purchaseCost": 3546,
    "revenue": 6153.71
  },
  {
    "date": "2024-04-01",
    "purchaseCost": 5006,
    "revenue": 7204.13
  },
  {
    "date": "2024-04-02",
    "purchaseCost": 3013,
    "revenue": 3709.09
  },
  {
    "date": "2024-04-03",
    "purchaseCost": 2420,
    "revenue": 2808.26
  },
  {
    "date": "2024-04-04",
    "purchaseCost": 1330,
    "revenue": 2256.2
  },
  {
    "date": "2024-04-05",
    "purchaseCost": 6341,
    "revenue": 8724.79
  },
  {
    "date": "2024-04-06",
    "purchaseCost": 5321,
    "revenue": 7104.13
  },
  {
    "date": "2024-04-07",
    "purchaseCost": 8974,
    "revenue": 11796.7
  },
  {
    "date": "2024-04-08",
    "purchaseCost": 3962,
    "revenue": 5443.8
  },
  {
    "date": "2024-04-09",
    "purchaseCost": 13044.84,
    "revenue": 18599.18
  },
  {
    "date": "2024-04-10",
    "purchaseCost": 8149,
    "revenue": 10873.55
  },
  {
    "date": "2024-04-11",
    "purchaseCost": 4282,
    "revenue": 6262.82
  },
  {
    "date": "2024-04-12",
    "purchaseCost": 7234,
    "revenue": 10639.67
  },
  {
    "date": "2024-04-13",
    "purchaseCost": 9581,
    "revenue": 12610.78
  },
  {
    "date": "2024-04-14",
    "purchaseCost": 8698,
    "revenue": 12779.3
  },
  {
    "date": "2024-04-15",
    "purchaseCost": 1407,
    "revenue": 2336.37
  },
  {
    "date": "2024-04-17",
    "purchaseCost": 7478,
    "revenue": 10847.09
  },
  {
    "date": "2024-04-18",
    "purchaseCost": 6685,
    "revenue": 9195.87
  },
  {
    "date": "2024-04-19",
    "purchaseCost": 5644,
    "revenue": 7667.76
  },
  {
    "date": "2024-04-20",
    "purchaseCost": 2770,
    "revenue": 4338.02
  },
  {
    "date": "2024-04-21",
    "purchaseCost": 4717,
    "revenue": 5609.08
  },
  {
    "date": "2024-04-22",
    "purchaseCost": 6977,
    "revenue": 10304.14
  },
  {
    "date": "2024-04-23",
    "purchaseCost": 5490,
    "revenue": 8766.94
  },
  {
    "date": "2024-04-24",
    "purchaseCost": 9298,
    "revenue": 11152.05
  },
  {
    "date": "2024-04-25",
    "purchaseCost": 2200,
    "revenue": 3048.76
  },
  {
    "date": "2024-04-26",
    "purchaseCost": 3237,
    "revenue": 5288.43
  },
  {
    "date": "2024-04-27",
    "purchaseCost": 7558,
    "revenue": 10592.55
  },
  {
    "date": "2024-04-28",
    "purchaseCost": 5988,
    "revenue": 8163.63
  },
  {
    "date": "2024-04-29",
    "purchaseCost": 8696,
    "revenue": 12973.56
  },
  {
    "date": "2024-04-30",
    "purchaseCost": 3410,
    "revenue": 4642.97
  },
  {
    "date": "2024-05-01",
    "purchaseCost": 3369,
    "revenue": 5759.5
  },
  {
    "date": "2024-05-02",
    "purchaseCost": 8951,
    "revenue": 11533.05
  },
  {
    "date": "2024-05-03",
    "purchaseCost": 6580,
    "revenue": 9154.54
  },
  {
    "date": "2024-05-04",
    "purchaseCost": 4425,
    "revenue": 6229.87
  },
  {
    "date": "2024-05-05",
    "purchaseCost": 6303,
    "revenue": 8650.42
  },
  {
    "date": "2024-05-06",
    "purchaseCost": 7650,
    "revenue": 11345.47
  },
  {
    "date": "2024-05-07",
    "purchaseCost": 6058,
    "revenue": 8505.08
  },
  {
    "date": "2024-05-08",
    "purchaseCost": 5349,
    "revenue": 7089.26
  },
  {
    "date": "2024-05-09",
    "purchaseCost": 7823,
    "revenue": 11342.97
  },
  {
    "date": "2024-05-10",
    "purchaseCost": 10428,
    "revenue": 14342.15
  },
  {
    "date": "2024-05-11",
    "purchaseCost": 688,
    "revenue": 1132.23
  },
  {
    "date": "2024-05-12",
    "purchaseCost": 12438,
    "revenue": 17448.77
  },
  {
    "date": "2024-05-13",
    "purchaseCost": 2472,
    "revenue": 3360.37
  },
  {
    "date": "2024-05-14",
    "purchaseCost": 11779,
    "revenue": 16478.14
  },
  {
    "date": "2024-05-15",
    "purchaseCost": 4984,
    "revenue": 6333.84
  },
  {
    "date": "2024-05-16",
    "purchaseCost": 5935,
    "revenue": 7542.97
  },
  {
    "date": "2024-05-17",
    "purchaseCost": 11507,
    "revenue": 14309.08
  },
  {
    "date": "2024-05-18",
    "purchaseCost": 7117,
    "revenue": 10625.61
  },
  {
    "date": "2024-05-19",
    "purchaseCost": 3614,
    "revenue": 5771.9
  },
  {
    "date": "2024-05-20",
    "purchaseCost": 7300,
    "revenue": 9683.47
  },
  {
    "date": "2024-05-21",
    "purchaseCost": 1499,
    "revenue": 1569.42
  },
  {
    "date": "2024-05-23",
    "purchaseCost": 3471,
    "revenue": 4352.06
  },
  {
    "date": "2024-05-24",
    "purchaseCost": 4041,
    "revenue": 5991.15
  },
  {
    "date": "2024-05-25",
    "purchaseCost": 5166,
    "revenue": 6585.11
  },
  {
    "date": "2024-05-26",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-05-27",
    "purchaseCost": 6939,
    "revenue": 8798.34
  },
  {
    "date": "2024-05-28",
    "purchaseCost": 11797,
    "revenue": 16104.21
  },
  {
    "date": "2024-05-30",
    "purchaseCost": 1876,
    "revenue": 2471.07
  },
  {
    "date": "2024-05-31",
    "purchaseCost": 7131,
    "revenue": 10667.77
  },
  {
    "date": "2024-06-01",
    "purchaseCost": 1297,
    "revenue": 1817.36
  },
  {
    "date": "2024-06-02",
    "purchaseCost": 10162,
    "revenue": 14790.18
  },
  {
    "date": "2024-06-03",
    "purchaseCost": 1803,
    "revenue": 2386.77
  },
  {
    "date": "2024-06-04",
    "purchaseCost": 4036,
    "revenue": 5733.06
  },
  {
    "date": "2024-06-05",
    "purchaseCost": 4424,
    "revenue": 5348.75
  },
  {
    "date": "2024-06-06",
    "purchaseCost": 593,
    "revenue": 982.64
  },
  {
    "date": "2024-06-07",
    "purchaseCost": 3668,
    "revenue": 5288.43
  },
  {
    "date": "2024-06-09",
    "purchaseCost": 4499.4,
    "revenue": 6415.64
  },
  {
    "date": "2024-06-10",
    "purchaseCost": 3651,
    "revenue": 4874.38
  },
  {
    "date": "2024-06-11",
    "purchaseCost": 11223,
    "revenue": 15099.16
  },
  {
    "date": "2024-06-12",
    "purchaseCost": 3920,
    "revenue": 5288.44
  },
  {
    "date": "2024-06-13",
    "purchaseCost": 5536,
    "revenue": 7461.15
  },
  {
    "date": "2024-06-14",
    "purchaseCost": 4424,
    "revenue": 5699.99
  },
  {
    "date": "2024-06-15",
    "purchaseCost": 1989,
    "revenue": 2455.59
  },
  {
    "date": "2024-06-16",
    "purchaseCost": 5444,
    "revenue": 8113.23
  },
  {
    "date": "2024-06-17",
    "purchaseCost": 5617,
    "revenue": 9015.71
  },
  {
    "date": "2024-06-18",
    "purchaseCost": 3387,
    "revenue": 4858.68
  },
  {
    "date": "2024-06-19",
    "purchaseCost": 6960,
    "revenue": 10876.03
  },
  {
    "date": "2024-06-21",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2024-06-22",
    "purchaseCost": 5124,
    "revenue": 7113.24
  },
  {
    "date": "2024-06-23",
    "purchaseCost": 2829,
    "revenue": 3866.94
  },
  {
    "date": "2024-06-24",
    "purchaseCost": 3675,
    "revenue": 5104.96
  },
  {
    "date": "2024-06-25",
    "purchaseCost": 3457,
    "revenue": 5155.38
  },
  {
    "date": "2024-06-26",
    "purchaseCost": 5237,
    "revenue": 6360.32
  },
  {
    "date": "2024-06-27",
    "purchaseCost": 3050,
    "revenue": 5189.26
  },
  {
    "date": "2024-06-28",
    "purchaseCost": 2817,
    "revenue": 3552.06
  },
  {
    "date": "2024-06-29",
    "purchaseCost": 1896,
    "revenue": 3014.05
  },
  {
    "date": "2024-06-30",
    "purchaseCost": 847,
    "revenue": 1198.35
  },
  {
    "date": "2024-07-01",
    "purchaseCost": 3175,
    "revenue": 4611.51
  },
  {
    "date": "2024-07-02",
    "purchaseCost": 3860,
    "revenue": 5040.5
  },
  {
    "date": "2024-07-04",
    "purchaseCost": 5296,
    "revenue": 6178.51
  },
  {
    "date": "2024-07-07",
    "purchaseCost": 8800,
    "revenue": 12407.41
  },
  {
    "date": "2024-07-08",
    "purchaseCost": 5667,
    "revenue": 6890.09
  },
  {
    "date": "2024-07-09",
    "purchaseCost": 1792,
    "revenue": 2485.12
  },
  {
    "date": "2024-07-10",
    "purchaseCost": 3540,
    "revenue": 6683.47
  },
  {
    "date": "2024-07-11",
    "purchaseCost": 5236,
    "revenue": 6361.17
  },
  {
    "date": "2024-07-12",
    "purchaseCost": 7108,
    "revenue": 10564.46
  },
  {
    "date": "2024-07-14",
    "purchaseCost": 3963,
    "revenue": 5857.85
  },
  {
    "date": "2024-07-15",
    "purchaseCost": 4436,
    "revenue": 6517.36
  },
  {
    "date": "2024-07-16",
    "purchaseCost": 787,
    "revenue": 1116.53
  },
  {
    "date": "2024-07-17",
    "purchaseCost": 6183,
    "revenue": 7871.9
  },
  {
    "date": "2024-07-18",
    "purchaseCost": 3772,
    "revenue": 5111.57
  },
  {
    "date": "2024-07-19",
    "purchaseCost": 1976,
    "revenue": 3136.36
  },
  {
    "date": "2024-07-20",
    "purchaseCost": 4194,
    "revenue": 6065.29
  },
  {
    "date": "2024-07-21",
    "purchaseCost": 5614,
    "revenue": 8557.86
  },
  {
    "date": "2024-07-22",
    "purchaseCost": 12177,
    "revenue": 16244.68
  },
  {
    "date": "2024-07-23",
    "purchaseCost": 8194,
    "revenue": 10884.34
  },
  {
    "date": "2024-07-24",
    "purchaseCost": 5860,
    "revenue": 7972.74
  },
  {
    "date": "2024-07-25",
    "purchaseCost": 2147,
    "revenue": 3221.5
  },
  {
    "date": "2024-07-26",
    "purchaseCost": 3097,
    "revenue": 4798.45
  },
  {
    "date": "2024-07-27",
    "purchaseCost": 790,
    "revenue": 1569.42
  },
  {
    "date": "2024-07-28",
    "purchaseCost": 2333,
    "revenue": 3710.74
  },
  {
    "date": "2024-07-29",
    "purchaseCost": 6513,
    "revenue": 10453.94
  },
  {
    "date": "2024-07-30",
    "purchaseCost": 8392,
    "revenue": 11960.33
  },
  {
    "date": "2024-07-31",
    "purchaseCost": 5271,
    "revenue": 6838.84
  },
  {
    "date": "2024-08-01",
    "purchaseCost": 3831,
    "revenue": 4781.82
  },
  {
    "date": "2024-08-02",
    "purchaseCost": 4813,
    "revenue": 6278.52
  },
  {
    "date": "2024-08-03",
    "purchaseCost": 2849,
    "revenue": 2420.67
  },
  {
    "date": "2024-08-04",
    "purchaseCost": 2816,
    "revenue": 3626.44
  },
  {
    "date": "2024-08-05",
    "purchaseCost": 4495,
    "revenue": 7414.32
  },
  {
    "date": "2024-08-06",
    "purchaseCost": 3734,
    "revenue": 5891.74
  },
  {
    "date": "2024-08-07",
    "purchaseCost": 2333,
    "revenue": 3698.35
  },
  {
    "date": "2024-08-08",
    "purchaseCost": 2933,
    "revenue": 5261.16
  },
  {
    "date": "2024-08-09",
    "purchaseCost": 725,
    "revenue": 1227.27
  },
  {
    "date": "2024-08-10",
    "purchaseCost": 4454,
    "revenue": 6319.83
  },
  {
    "date": "2024-08-11",
    "purchaseCost": 6245,
    "revenue": 9011.58
  },
  {
    "date": "2024-08-12",
    "purchaseCost": 3274,
    "revenue": 4923.15
  },
  {
    "date": "2024-08-13",
    "purchaseCost": 3734,
    "revenue": 6189.26
  },
  {
    "date": "2024-08-14",
    "purchaseCost": 5884,
    "revenue": 10228.92
  },
  {
    "date": "2024-08-15",
    "purchaseCost": 6881,
    "revenue": 8632.23
  },
  {
    "date": "2024-08-16",
    "purchaseCost": 5586,
    "revenue": 9079.34
  },
  {
    "date": "2024-08-17",
    "purchaseCost": 5229,
    "revenue": 6266.11
  },
  {
    "date": "2024-08-18",
    "purchaseCost": 2997,
    "revenue": 4951.24
  },
  {
    "date": "2024-08-19",
    "purchaseCost": 7071,
    "revenue": 9088.43
  },
  {
    "date": "2024-08-20",
    "purchaseCost": 4648,
    "revenue": 6748.75
  },
  {
    "date": "2024-08-21",
    "purchaseCost": 7137,
    "revenue": 8417.34
  },
  {
    "date": "2024-08-22",
    "purchaseCost": 1170,
    "revenue": 1975.21
  },
  {
    "date": "2024-08-23",
    "purchaseCost": 2469,
    "revenue": 3222.31
  },
  {
    "date": "2024-08-24",
    "purchaseCost": 847,
    "revenue": 1198.35
  },
  {
    "date": "2024-08-25",
    "purchaseCost": 4724,
    "revenue": 5990.09
  },
  {
    "date": "2024-08-26",
    "purchaseCost": 7746,
    "revenue": 11215.69
  },
  {
    "date": "2024-08-27",
    "purchaseCost": 2634,
    "revenue": 4709.91
  },
  {
    "date": "2024-08-28",
    "purchaseCost": 6687,
    "revenue": 9203.31
  },
  {
    "date": "2024-08-29",
    "purchaseCost": 5729,
    "revenue": 8352.06
  },
  {
    "date": "2024-08-30",
    "purchaseCost": 2017,
    "revenue": 2223.14
  },
  {
    "date": "2024-09-01",
    "purchaseCost": 1981,
    "revenue": 2717.35
  },
  {
    "date": "2024-09-02",
    "purchaseCost": 5390,
    "revenue": 6600.82
  },
  {
    "date": "2024-09-03",
    "purchaseCost": 10925,
    "revenue": 16250.4
  },
  {
    "date": "2024-09-04",
    "purchaseCost": 6809,
    "revenue": 8485.12
  },
  {
    "date": "2024-09-05",
    "purchaseCost": 4494,
    "revenue": 5548.26
  },
  {
    "date": "2024-09-06",
    "purchaseCost": 6385,
    "revenue": 10270.35
  },
  {
    "date": "2024-09-07",
    "purchaseCost": 5378,
    "revenue": 7253.73
  },
  {
    "date": "2024-09-08",
    "purchaseCost": 2175,
    "revenue": 2950.41
  },
  {
    "date": "2024-09-09",
    "purchaseCost": 6099,
    "revenue": 7758.68
  },
  {
    "date": "2024-09-10",
    "purchaseCost": 7269,
    "revenue": 9343.8
  },
  {
    "date": "2024-09-11",
    "purchaseCost": 6783,
    "revenue": 9872.72
  },
  {
    "date": "2024-09-12",
    "purchaseCost": 6958,
    "revenue": 10020.65
  },
  {
    "date": "2024-09-13",
    "purchaseCost": 2017,
    "revenue": 2223.14
  },
  {
    "date": "2024-09-14",
    "purchaseCost": 3930,
    "revenue": 7255.37
  },
  {
    "date": "2024-09-15",
    "purchaseCost": 319,
    "revenue": 329.75
  },
  {
    "date": "2024-09-16",
    "purchaseCost": 5624,
    "revenue": 7344.62
  },
  {
    "date": "2024-09-17",
    "purchaseCost": 5088,
    "revenue": 8134.7
  },
  {
    "date": "2024-09-18",
    "purchaseCost": 3347,
    "revenue": 4479.34
  },
  {
    "date": "2024-09-20",
    "purchaseCost": 3837,
    "revenue": 5477.69
  },
  {
    "date": "2024-09-21",
    "purchaseCost": 4650,
    "revenue": 6345.45
  },
  {
    "date": "2024-09-22",
    "purchaseCost": 4954,
    "revenue": 6600.82
  },
  {
    "date": "2024-09-23",
    "purchaseCost": 9889,
    "revenue": 13498.34
  },
  {
    "date": "2024-09-24",
    "purchaseCost": 5445,
    "revenue": 8203.3
  },
  {
    "date": "2024-09-25",
    "purchaseCost": 1170,
    "revenue": 1975.21
  },
  {
    "date": "2024-09-26",
    "purchaseCost": 3328,
    "revenue": 4822.31
  },
  {
    "date": "2024-09-27",
    "purchaseCost": 212,
    "revenue": 371.07
  },
  {
    "date": "2024-09-28",
    "purchaseCost": 1330,
    "revenue": 2256.2
  },
  {
    "date": "2024-09-29",
    "purchaseCost": 9265,
    "revenue": 12881.81
  },
  {
    "date": "2024-09-30",
    "purchaseCost": 3484,
    "revenue": 5333.07
  },
  {
    "date": "2024-10-01",
    "purchaseCost": 10850,
    "revenue": 14635.78
  },
  {
    "date": "2024-10-02",
    "purchaseCost": 790,
    "revenue": 1569.42
  },
  {
    "date": "2024-10-03",
    "purchaseCost": 937,
    "revenue": 1404.13
  },
  {
    "date": "2024-10-06",
    "purchaseCost": 5295,
    "revenue": 8742.97
  },
  {
    "date": "2024-10-07",
    "purchaseCost": 1210,
    "revenue": 2471.07
  },
  {
    "date": "2024-10-08",
    "purchaseCost": 2954,
    "revenue": 3627.27
  },
  {
    "date": "2024-10-09",
    "purchaseCost": 4726,
    "revenue": 7923.65
  },
  {
    "date": "2024-10-10",
    "purchaseCost": 3567,
    "revenue": 4528.93
  },
  {
    "date": "2024-10-12",
    "purchaseCost": 11732,
    "revenue": 15741.98
  },
  {
    "date": "2024-10-13",
    "purchaseCost": 3170,
    "revenue": 5768.59
  },
  {
    "date": "2024-10-14",
    "purchaseCost": 2553,
    "revenue": 5180.98
  },
  {
    "date": "2024-10-15",
    "purchaseCost": 3880,
    "revenue": 6759.5
  },
  {
    "date": "2024-10-16",
    "purchaseCost": 6371,
    "revenue": 8552.2
  },
  {
    "date": "2024-10-17",
    "purchaseCost": 3448,
    "revenue": 6296.69
  },
  {
    "date": "2024-10-18",
    "purchaseCost": 4834,
    "revenue": 6842.14
  },
  {
    "date": "2024-10-19",
    "purchaseCost": 1949,
    "revenue": 2040.5
  },
  {
    "date": "2024-10-21",
    "purchaseCost": 6139,
    "revenue": 8524.79
  },
  {
    "date": "2024-10-22",
    "purchaseCost": 4509,
    "revenue": 6261.98
  },
  {
    "date": "2024-10-23",
    "purchaseCost": 1210,
    "revenue": 2471.07
  },
  {
    "date": "2024-10-24",
    "purchaseCost": 1210,
    "revenue": 2471.07
  },
  {
    "date": "2024-10-25",
    "purchaseCost": 1668,
    "revenue": 2700.84
  },
  {
    "date": "2024-10-26",
    "purchaseCost": 3305,
    "revenue": 4411.58
  },
  {
    "date": "2024-10-27",
    "purchaseCost": 3630,
    "revenue": 7165.28
  },
  {
    "date": "2024-10-29",
    "purchaseCost": 2386,
    "revenue": 2489.21
  },
  {
    "date": "2024-10-30",
    "purchaseCost": 1330,
    "revenue": 2256.2
  },
  {
    "date": "2024-11-03",
    "purchaseCost": 2511,
    "revenue": 4792.56
  },
  {
    "date": "2024-11-04",
    "purchaseCost": 4269,
    "revenue": 6940.49
  },
  {
    "date": "2024-11-06",
    "purchaseCost": 1275,
    "revenue": 2577.68
  },
  {
    "date": "2024-11-07",
    "purchaseCost": 4355,
    "revenue": 7453.72
  },
  {
    "date": "2024-11-08",
    "purchaseCost": 3275,
    "revenue": 4378.51
  },
  {
    "date": "2024-11-09",
    "purchaseCost": 4787,
    "revenue": 6800
  },
  {
    "date": "2024-11-10",
    "purchaseCost": 4477,
    "revenue": 6842.15
  },
  {
    "date": "2024-11-11",
    "purchaseCost": 1463,
    "revenue": 2847.94
  },
  {
    "date": "2024-11-12",
    "purchaseCost": 3220,
    "revenue": 4635.54
  },
  {
    "date": "2024-11-13",
    "purchaseCost": 3327,
    "revenue": 4032.21
  },
  {
    "date": "2024-11-14",
    "purchaseCost": 4425,
    "revenue": 6188.43
  },
  {
    "date": "2024-11-15",
    "purchaseCost": 8241,
    "revenue": 14197.52
  },
  {
    "date": "2024-11-16",
    "purchaseCost": 4779,
    "revenue": 6594.21
  },
  {
    "date": "2024-11-17",
    "purchaseCost": 2017,
    "revenue": 2223.14
  },
  {
    "date": "2024-11-18",
    "purchaseCost": 3290,
    "revenue": 6627.28
  },
  {
    "date": "2024-11-19",
    "purchaseCost": 5077,
    "revenue": 8512.4
  },
  {
    "date": "2024-11-20",
    "purchaseCost": 3492,
    "revenue": 6123.96
  },
  {
    "date": "2024-11-23",
    "purchaseCost": 266,
    "revenue": 477.68
  },
  {
    "date": "2024-11-24",
    "purchaseCost": 1607,
    "revenue": 2147.93
  },
  {
    "date": "2024-11-25",
    "purchaseCost": 2159,
    "revenue": 2230.58
  },
  {
    "date": "2024-11-26",
    "purchaseCost": 930,
    "revenue": 1569.42
  },
  {
    "date": "2024-11-27",
    "purchaseCost": 1386,
    "revenue": 2228.11
  },
  {
    "date": "2024-11-29",
    "purchaseCost": 1210,
    "revenue": 2471.07
  },
  {
    "date": "2024-11-30",
    "purchaseCost": 3491,
    "revenue": 4231.41
  },
  {
    "date": "2024-12-02",
    "purchaseCost": 940,
    "revenue": 2140.5
  },
  {
    "date": "2024-12-04",
    "purchaseCost": 7187,
    "revenue": 10733.88
  },
  {
    "date": "2024-12-05",
    "purchaseCost": 2249,
    "revenue": 3188.42
  },
  {
    "date": "2024-12-06",
    "purchaseCost": 940,
    "revenue": 2140.5
  },
  {
    "date": "2024-12-07",
    "purchaseCost": 2745,
    "revenue": 4882.64
  },
  {
    "date": "2024-12-08",
    "purchaseCost": 930,
    "revenue": 1569.42
  },
  {
    "date": "2024-12-10",
    "purchaseCost": 2757,
    "revenue": 3957.85
  },
  {
    "date": "2024-12-11",
    "purchaseCost": 2875,
    "revenue": 3304.96
  },
  {
    "date": "2024-12-13",
    "purchaseCost": 3612,
    "revenue": 5909.09
  },
  {
    "date": "2024-12-14",
    "purchaseCost": 3346,
    "revenue": 4975.21
  },
  {
    "date": "2024-12-15",
    "purchaseCost": 2481,
    "revenue": 3557.85
  },
  {
    "date": "2024-12-16",
    "purchaseCost": 3256,
    "revenue": 5119.83
  },
  {
    "date": "2024-12-17",
    "purchaseCost": 1321,
    "revenue": 1675.2
  },
  {
    "date": "2024-12-18",
    "purchaseCost": 1838.4,
    "revenue": 2309.87
  },
  {
    "date": "2024-12-19",
    "purchaseCost": 952,
    "revenue": 1396.69
  },
  {
    "date": "2024-12-20",
    "purchaseCost": 1138,
    "revenue": 1808.26
  },
  {
    "date": "2024-12-21",
    "purchaseCost": 750,
    "revenue": 1975.21
  },
  {
    "date": "2024-12-22",
    "purchaseCost": 1150,
    "revenue": 1809.92
  },
  {
    "date": "2024-12-24",
    "purchaseCost": 1729,
    "revenue": 2147.93
  },
  {
    "date": "2024-12-25",
    "purchaseCost": 1060,
    "revenue": 2305.79
  },
  {
    "date": "2024-12-27",
    "purchaseCost": 2102,
    "revenue": 3206.61
  },
  {
    "date": "2024-12-28",
    "purchaseCost": 1823,
    "revenue": 4354.55
  },
  {
    "date": "2024-12-29",
    "purchaseCost": 6674,
    "revenue": 7848.76
  },
  {
    "date": "2024-12-31",
    "purchaseCost": 1703,
    "revenue": 3371.9
  },
  {
    "date": "2025-01-01",
    "purchaseCost": 4086,
    "revenue": 6353.71
  },
  {
    "date": "2025-01-02",
    "purchaseCost": 4668,
    "revenue": 7165.29
  },
  {
    "date": "2025-01-03",
    "purchaseCost": 1556,
    "revenue": 2388.43
  },
  {
    "date": "2025-01-04",
    "purchaseCost": 7474,
    "revenue": 11776.86
  },
  {
    "date": "2025-01-05",
    "purchaseCost": 5788,
    "revenue": 9147.93
  },
  {
    "date": "2025-01-06",
    "purchaseCost": 15501,
    "revenue": 22908.27
  },
  {
    "date": "2025-01-07",
    "purchaseCost": 7161,
    "revenue": 10957.85
  },
  {
    "date": "2025-01-08",
    "purchaseCost": 1822,
    "revenue": 2866.12
  },
  {
    "date": "2025-01-09",
    "purchaseCost": 1556,
    "revenue": 2388.43
  },
  {
    "date": "2025-01-10",
    "purchaseCost": 5079,
    "revenue": 8164.47
  },
  {
    "date": "2025-01-11",
    "purchaseCost": 3112,
    "revenue": 4776.86
  },
  {
    "date": "2025-01-12",
    "purchaseCost": 6019,
    "revenue": 9479.35
  },
  {
    "date": "2025-01-13",
    "purchaseCost": 10740,
    "revenue": 17535.54
  },
  {
    "date": "2025-01-14",
    "purchaseCost": 6418,
    "revenue": 9866.94
  },
  {
    "date": "2025-01-15",
    "purchaseCost": 11493,
    "revenue": 17395.04
  },
  {
    "date": "2025-01-16",
    "purchaseCost": 13714,
    "revenue": 21840.5
  },
  {
    "date": "2025-01-17",
    "purchaseCost": 8274,
    "revenue": 11214.05
  },
  {
    "date": "2025-01-18",
    "purchaseCost": 9110,
    "revenue": 14585.95
  },
  {
    "date": "2025-01-19",
    "purchaseCost": 14285,
    "revenue": 18957.85
  },
  {
    "date": "2025-01-20",
    "purchaseCost": 5705,
    "revenue": 7578.51
  },
  {
    "date": "2025-01-21",
    "purchaseCost": 4837,
    "revenue": 7082.65
  },
  {
    "date": "2025-01-22",
    "purchaseCost": 1556,
    "revenue": 2388.43
  },
  {
    "date": "2025-01-23",
    "purchaseCost": 9548,
    "revenue": 13642.97
  },
  {
    "date": "2025-01-24",
    "purchaseCost": 1556,
    "revenue": 2388.43
  },
  {
    "date": "2025-01-25",
    "purchaseCost": 8565,
    "revenue": 12585.13
  },
  {
    "date": "2025-01-26",
    "purchaseCost": 4719,
    "revenue": 7082.65
  },
  {
    "date": "2025-01-27",
    "purchaseCost": 2246,
    "revenue": 3225.57
  },
  {
    "date": "2025-01-28",
    "purchaseCost": 3112,
    "revenue": 4776.86
  },
  {
    "date": "2025-01-29",
    "purchaseCost": 1900,
    "revenue": 3421.49
  },
  {
    "date": "2025-01-30",
    "purchaseCost": 4362,
    "revenue": 7000
  },
  {
    "date": "2025-01-31",
    "purchaseCost": 2017,
    "revenue": 2809.09
  },
  {
    "date": "2025-02-02",
    "purchaseCost": 5343,
    "revenue": 9223.15
  },
  {
    "date": "2025-02-05",
    "purchaseCost": 2493,
    "revenue": 3792.56
  },
  {
    "date": "2025-02-06",
    "purchaseCost": 650,
    "revenue": 1198.35
  },
  {
    "date": "2025-02-07",
    "purchaseCost": 6418,
    "revenue": 9866.94
  },
  {
    "date": "2025-02-09",
    "purchaseCost": 1250,
    "revenue": 2223.14
  },
  {
    "date": "2025-02-10",
    "purchaseCost": 3138,
    "revenue": 6104.97
  },
  {
    "date": "2025-02-11",
    "purchaseCost": 6423,
    "revenue": 9989.26
  },
  {
    "date": "2025-02-12",
    "purchaseCost": 2493,
    "revenue": 3792.56
  },
  {
    "date": "2025-02-13",
    "purchaseCost": 6469,
    "revenue": 9784.3
  },
  {
    "date": "2025-02-14",
    "purchaseCost": 4373,
    "revenue": 6098.35
  },
  {
    "date": "2025-02-15",
    "purchaseCost": 3112,
    "revenue": 4776.86
  },
  {
    "date": "2025-02-16",
    "purchaseCost": 5705,
    "revenue": 8247.11
  },
  {
    "date": "2025-02-17",
    "purchaseCost": 1556,
    "revenue": 2388.43
  },
  {
    "date": "2025-02-18",
    "purchaseCost": 4278,
    "revenue": 7386.78
  },
  {
    "date": "2025-02-19",
    "purchaseCost": 3706,
    "revenue": 8342.96
  },
  {
    "date": "2025-02-20",
    "purchaseCost": 2676,
    "revenue": 4371.07
  },
  {
    "date": "2025-02-21",
    "purchaseCost": 1210,
    "revenue": 1404.13
  },
  {
    "date": "2025-02-22",
    "purchaseCost": 1874,
    "revenue": 2808.26
  },
  {
    "date": "2025-02-24",
    "purchaseCost": 4362,
    "revenue": 7000
  },
  {
    "date": "2025-02-26",
    "purchaseCost": 1620,
    "revenue": 3123.97
  },
  {
    "date": "2025-02-27",
    "purchaseCost": 5186,
    "revenue": 7750.42
  },
  {
    "date": "2025-02-28",
    "purchaseCost": 1250,
    "revenue": 2223.14
  },
  {
    "date": "2025-03-01",
    "purchaseCost": 1556,
    "revenue": 2388.43
  },
  {
    "date": "2025-03-02",
    "purchaseCost": 4177,
    "revenue": 5652.89
  },
  {
    "date": "2025-03-03",
    "purchaseCost": 3254,
    "revenue": 5267.77
  },
  {
    "date": "2025-03-04",
    "purchaseCost": 937,
    "revenue": 1404.13
  },
  {
    "date": "2025-03-05",
    "purchaseCost": 2352,
    "revenue": 4425.63
  },
  {
    "date": "2025-03-06",
    "purchaseCost": 3055,
    "revenue": 4949.59
  },
  {
    "date": "2025-03-07",
    "purchaseCost": 2147,
    "revenue": 4288.43
  },
  {
    "date": "2025-03-09",
    "purchaseCost": 4233,
    "revenue": 6098.35
  },
  {
    "date": "2025-03-10",
    "purchaseCost": 1792,
    "revenue": 2817.36
  },
  {
    "date": "2025-03-11",
    "purchaseCost": 2187,
    "revenue": 3627.27
  },
  {
    "date": "2025-03-12",
    "purchaseCost": 2489,
    "revenue": 2917.36
  },
  {
    "date": "2025-03-14",
    "purchaseCost": 2016,
    "revenue": 2719.01
  },
  {
    "date": "2025-03-18",
    "purchaseCost": 1654,
    "revenue": 3114.06
  },
  {
    "date": "2025-03-20",
    "purchaseCost": 2614,
    "revenue": 3348.76
  },
  {
    "date": "2025-03-22",
    "purchaseCost": 1522,
    "revenue": 2245.45
  },
  {
    "date": "2025-03-23",
    "purchaseCost": 4581,
    "revenue": 6180.99
  },
  {
    "date": "2025-03-24",
    "purchaseCost": 5711,
    "revenue": 8577.69
  },
  {
    "date": "2025-03-25",
    "purchaseCost": 4148,
    "revenue": 6057.85
  },
  {
    "date": "2025-03-26",
    "purchaseCost": 2150,
    "revenue": 3279.35
  },
  {
    "date": "2025-03-27",
    "purchaseCost": 6228,
    "revenue": 7537.18
  },
  {
    "date": "2025-03-28",
    "purchaseCost": 1713,
    "revenue": 1941.32
  },
  {
    "date": "2025-03-29",
    "purchaseCost": 12419,
    "revenue": 18088.43
  },
  {
    "date": "2025-03-30",
    "purchaseCost": 4961,
    "revenue": 5923.96
  },
  {
    "date": "2025-03-31",
    "purchaseCost": 9629,
    "revenue": 14268.6
  },
  {
    "date": "2025-04-01",
    "purchaseCost": 11963,
    "revenue": 14007.44
  },
  {
    "date": "2025-04-02",
    "purchaseCost": 5825,
    "revenue": 8066.12
  },
  {
    "date": "2025-04-03",
    "purchaseCost": 6108.04,
    "revenue": 8400.83
  },
  {
    "date": "2025-04-04",
    "purchaseCost": 4797,
    "revenue": 7543.81
  },
  {
    "date": "2025-04-05",
    "purchaseCost": 4581,
    "revenue": 6256.2
  },
  {
    "date": "2025-04-06",
    "purchaseCost": 3803,
    "revenue": 5429.76
  },
  {
    "date": "2025-04-07",
    "purchaseCost": 7167.01,
    "revenue": 9352.08
  },
  {
    "date": "2025-04-08",
    "purchaseCost": 6634.12,
    "revenue": 8966.11
  },
  {
    "date": "2025-04-09",
    "purchaseCost": 7964.18,
    "revenue": 11114.87
  },
  {
    "date": "2025-04-10",
    "purchaseCost": 15335.04,
    "revenue": 20913.22
  },
  {
    "date": "2025-04-11",
    "purchaseCost": 10905.36,
    "revenue": 14923.98
  },
  {
    "date": "2025-04-12",
    "purchaseCost": 8932,
    "revenue": 12625.63
  },
  {
    "date": "2025-04-13",
    "purchaseCost": 4552,
    "revenue": 6361.16
  },
  {
    "date": "2025-04-14",
    "purchaseCost": 10303.1,
    "revenue": 14392.56
  },
  {
    "date": "2025-04-15",
    "purchaseCost": 10505,
    "revenue": 16146.29
  },
  {
    "date": "2025-04-16",
    "purchaseCost": 11439,
    "revenue": 16122.32
  },
  {
    "date": "2025-04-17",
    "purchaseCost": 16767.74,
    "revenue": 25024.83
  },
  {
    "date": "2025-04-18",
    "purchaseCost": 6800,
    "revenue": 9445.46
  },
  {
    "date": "2025-04-19",
    "purchaseCost": 8118.82,
    "revenue": 11923.13
  },
  {
    "date": "2025-04-20",
    "purchaseCost": 2795,
    "revenue": 4000
  },
  {
    "date": "2025-04-21",
    "purchaseCost": 6530,
    "revenue": 9063.64
  },
  {
    "date": "2025-04-22",
    "purchaseCost": 14120,
    "revenue": 20361.99
  },
  {
    "date": "2025-04-23",
    "purchaseCost": 8301.69,
    "revenue": 11128.93
  },
  {
    "date": "2025-04-24",
    "purchaseCost": 10463,
    "revenue": 14460.33
  },
  {
    "date": "2025-04-25",
    "purchaseCost": 21454.4,
    "revenue": 28835.54
  },
  {
    "date": "2025-04-26",
    "purchaseCost": 6624.71,
    "revenue": 8667.79
  },
  {
    "date": "2025-04-27",
    "purchaseCost": 7044.44,
    "revenue": 9161.17
  },
  {
    "date": "2025-04-28",
    "purchaseCost": 9000,
    "revenue": 12790.09
  },
  {
    "date": "2025-04-29",
    "purchaseCost": 7032.17,
    "revenue": 10125.65
  },
  {
    "date": "2025-04-30",
    "purchaseCost": 16708.52,
    "revenue": 23968
  },
  {
    "date": "2025-05-01",
    "purchaseCost": 2420,
    "revenue": 3500.84
  },
  {
    "date": "2025-05-02",
    "purchaseCost": 8067,
    "revenue": 11394.22
  },
  {
    "date": "2025-05-03",
    "purchaseCost": 9419.53,
    "revenue": 12493.39
  },
  {
    "date": "2025-05-04",
    "purchaseCost": 10576.36,
    "revenue": 14128.11
  },
  {
    "date": "2025-05-05",
    "purchaseCost": 4783.07,
    "revenue": 6643.8
  },
  {
    "date": "2025-05-06",
    "purchaseCost": 11235.49,
    "revenue": 15178.52
  },
  {
    "date": "2025-05-07",
    "purchaseCost": 8340.36,
    "revenue": 11311.58
  },
  {
    "date": "2025-05-08",
    "purchaseCost": 4471.56,
    "revenue": 7352.9
  },
  {
    "date": "2025-05-09",
    "purchaseCost": 12701.55,
    "revenue": 17269.42
  },
  {
    "date": "2025-05-10",
    "purchaseCost": 5820,
    "revenue": 7991.74
  },
  {
    "date": "2025-05-11",
    "purchaseCost": 7895.36,
    "revenue": 10906.61
  },
  {
    "date": "2025-05-12",
    "purchaseCost": 11490,
    "revenue": 15871.9
  },
  {
    "date": "2025-05-13",
    "purchaseCost": 14035.85,
    "revenue": 18469.43
  },
  {
    "date": "2025-05-14",
    "purchaseCost": 4606.2,
    "revenue": 6631.41
  },
  {
    "date": "2025-05-15",
    "purchaseCost": 15768.18,
    "revenue": 22761.97
  },
  {
    "date": "2025-05-16",
    "purchaseCost": 10006,
    "revenue": 13958.68
  },
  {
    "date": "2025-05-17",
    "purchaseCost": 5510,
    "revenue": 7097.53
  },
  {
    "date": "2025-05-18",
    "purchaseCost": 5790.85,
    "revenue": 8385.14
  },
  {
    "date": "2025-05-19",
    "purchaseCost": 11511.96,
    "revenue": 17787.61
  },
  {
    "date": "2025-05-20",
    "purchaseCost": 7786,
    "revenue": 11138.02
  },
  {
    "date": "2025-05-21",
    "purchaseCost": 12236.84,
    "revenue": 20306.64
  },
  {
    "date": "2025-05-22",
    "purchaseCost": 4230.1,
    "revenue": 5724.79
  },
  {
    "date": "2025-05-23",
    "purchaseCost": 1728.6,
    "revenue": 2899.18
  },
  {
    "date": "2025-05-24",
    "purchaseCost": 7370.52,
    "revenue": 10956.2
  },
  {
    "date": "2025-05-25",
    "purchaseCost": 9651.2,
    "revenue": 12891.73
  },
  {
    "date": "2025-05-26",
    "purchaseCost": 16056.96,
    "revenue": 22518.18
  },
  {
    "date": "2025-05-27",
    "purchaseCost": 7628.57,
    "revenue": 10345.47
  },
  {
    "date": "2025-05-28",
    "purchaseCost": 12117.81,
    "revenue": 15960.34
  },
  {
    "date": "2025-05-29",
    "purchaseCost": 6649.86,
    "revenue": 8977.35
  },
  {
    "date": "2025-05-30",
    "purchaseCost": 5445,
    "revenue": 7964.46
  },
  {
    "date": "2025-05-31",
    "purchaseCost": 1152.4,
    "revenue": 1734.71
  },
  {
    "date": "2025-06-01",
    "purchaseCost": 8240.52,
    "revenue": 11377.69
  },
  {
    "date": "2025-06-02",
    "purchaseCost": 6152.92,
    "revenue": 8638.02
  },
  {
    "date": "2025-06-03",
    "purchaseCost": 7818.05,
    "revenue": 11789.25
  },
  {
    "date": "2025-06-04",
    "purchaseCost": 10260.93,
    "revenue": 15328.11
  },
  {
    "date": "2025-06-05",
    "purchaseCost": 14600.6,
    "revenue": 20489.27
  },
  {
    "date": "2025-06-06",
    "purchaseCost": 4724.63,
    "revenue": 6165.28
  },
  {
    "date": "2025-06-07",
    "purchaseCost": 3658.73,
    "revenue": 5173.56
  },
  {
    "date": "2025-06-08",
    "purchaseCost": 3226.46,
    "revenue": 4595.04
  },
  {
    "date": "2025-06-09",
    "purchaseCost": 11545.58,
    "revenue": 16907.45
  },
  {
    "date": "2025-06-10",
    "purchaseCost": 14981.31,
    "revenue": 23168.59
  },
  {
    "date": "2025-06-11",
    "purchaseCost": 12891.95,
    "revenue": 19119.84
  },
  {
    "date": "2025-06-12",
    "purchaseCost": 8326.13,
    "revenue": 11900
  },
  {
    "date": "2025-06-13",
    "purchaseCost": 15196.12,
    "revenue": 21666.11
  },
  {
    "date": "2025-06-14",
    "purchaseCost": 4274.1,
    "revenue": 5924.8
  },
  {
    "date": "2025-06-15",
    "purchaseCost": 15125.54,
    "revenue": 22254.56
  },
  {
    "date": "2025-06-16",
    "purchaseCost": 15240.79,
    "revenue": 22204.14
  },
  {
    "date": "2025-06-17",
    "purchaseCost": 10132.46,
    "revenue": 13790.92
  },
  {
    "date": "2025-06-18",
    "purchaseCost": 15853.49,
    "revenue": 22946.31
  },
  {
    "date": "2025-06-19",
    "purchaseCost": 10298.06,
    "revenue": 13741.33
  },
  {
    "date": "2025-06-20",
    "purchaseCost": 7784.96,
    "revenue": 11015.7
  },
  {
    "date": "2025-06-21",
    "purchaseCost": 9996.85,
    "revenue": 13791.74
  },
  {
    "date": "2025-06-22",
    "purchaseCost": 4609.5,
    "revenue": 6727.29
  },
  {
    "date": "2025-06-23",
    "purchaseCost": 10805.2,
    "revenue": 16813.27
  },
  {
    "date": "2025-06-24",
    "purchaseCost": 6177.31,
    "revenue": 8040.5
  },
  {
    "date": "2025-06-25",
    "purchaseCost": 13619,
    "revenue": 19586.8
  },
  {
    "date": "2025-06-26",
    "purchaseCost": 6031.08,
    "revenue": 7307.03
  },
  {
    "date": "2025-06-27",
    "purchaseCost": 4983.93,
    "revenue": 7297.53
  },
  {
    "date": "2025-06-28",
    "purchaseCost": 4119.63,
    "revenue": 5916.54
  },
  {
    "date": "2025-06-29",
    "purchaseCost": 5761.66,
    "revenue": 8066.11
  },
  {
    "date": "2025-06-30",
    "purchaseCost": 11735.8,
    "revenue": 16522.35
  },
  {
    "date": "2025-07-01",
    "purchaseCost": 13594.05,
    "revenue": 19212.42
  },
  {
    "date": "2025-07-02",
    "purchaseCost": 10621.93,
    "revenue": 15716.54
  },
  {
    "date": "2025-07-03",
    "purchaseCost": 15053.28,
    "revenue": 21276.9
  },
  {
    "date": "2025-07-04",
    "purchaseCost": 5372.63,
    "revenue": 7592.57
  },
  {
    "date": "2025-07-05",
    "purchaseCost": 5445,
    "revenue": 7884.32
  },
  {
    "date": "2025-07-06",
    "purchaseCost": 9603.69,
    "revenue": 12634.71
  },
  {
    "date": "2025-07-07",
    "purchaseCost": 4027,
    "revenue": 5909.11
  },
  {
    "date": "2025-07-08",
    "purchaseCost": 11872.41,
    "revenue": 18659.52
  },
  {
    "date": "2025-07-09",
    "purchaseCost": 12089.53,
    "revenue": 18370.26
  },
  {
    "date": "2025-07-10",
    "purchaseCost": 7951.5,
    "revenue": 11256.21
  },
  {
    "date": "2025-07-11",
    "purchaseCost": 15111.38,
    "revenue": 21879.35
  },
  {
    "date": "2025-07-12",
    "purchaseCost": 5237.25,
    "revenue": 7462
  },
  {
    "date": "2025-07-13",
    "purchaseCost": 8095.5,
    "revenue": 11280.99
  },
  {
    "date": "2025-07-14",
    "purchaseCost": 11138.15,
    "revenue": 15543.81
  },
  {
    "date": "2025-07-15",
    "purchaseCost": 19156.58,
    "revenue": 27237.18
  },
  {
    "date": "2025-07-16",
    "purchaseCost": 19096.78,
    "revenue": 28173.57
  },
  {
    "date": "2025-07-17",
    "purchaseCost": 9052.83,
    "revenue": 12487.61
  },
  {
    "date": "2025-07-18",
    "purchaseCost": 11357.59,
    "revenue": 16301.68
  },
  {
    "date": "2025-07-19",
    "purchaseCost": 8365.89,
    "revenue": 11444.64
  },
  {
    "date": "2025-07-20",
    "purchaseCost": 4299.23,
    "revenue": 5785.12
  },
  {
    "date": "2025-07-21",
    "purchaseCost": 9995.19,
    "revenue": 13918.2
  },
  {
    "date": "2025-07-22",
    "purchaseCost": 9645.55,
    "revenue": 13589.23
  },
  {
    "date": "2025-07-23",
    "purchaseCost": 12144.34,
    "revenue": 17384.33
  },
  {
    "date": "2025-07-24",
    "purchaseCost": 11722.06,
    "revenue": 15285.96
  },
  {
    "date": "2025-07-25",
    "purchaseCost": 10680.02,
    "revenue": 15262.83
  },
  {
    "date": "2025-07-26",
    "purchaseCost": 6989.63,
    "revenue": 10544.64
  },
  {
    "date": "2025-07-27",
    "purchaseCost": 7094.77,
    "revenue": 10552.89
  },
  {
    "date": "2025-07-28",
    "purchaseCost": 11732.19,
    "revenue": 17008.27
  },
  {
    "date": "2025-07-29",
    "purchaseCost": 12130.56,
    "revenue": 17385.97
  },
  {
    "date": "2025-07-30",
    "purchaseCost": 6540.34,
    "revenue": 8873.57
  },
  {
    "date": "2025-07-31",
    "purchaseCost": 8412.4,
    "revenue": 11776.03
  },
  {
    "date": "2025-08-01",
    "purchaseCost": 16882.16,
    "revenue": 23594.23
  },
  {
    "date": "2025-08-02",
    "purchaseCost": 5404.1,
    "revenue": 7553.73
  },
  {
    "date": "2025-08-03",
    "purchaseCost": 8470.13,
    "revenue": 12238.02
  },
  {
    "date": "2025-08-04",
    "purchaseCost": 8787.31,
    "revenue": 12462.81
  },
  {
    "date": "2025-08-05",
    "purchaseCost": 12118.2,
    "revenue": 17766.95
  },
  {
    "date": "2025-08-06",
    "purchaseCost": 6122.04,
    "revenue": 8404.13
  },
  {
    "date": "2025-08-07",
    "purchaseCost": 5358.6,
    "revenue": 7396.71
  },
  {
    "date": "2025-08-08",
    "purchaseCost": 8878.06,
    "revenue": 15176.85
  },
  {
    "date": "2025-08-09",
    "purchaseCost": 2977.88,
    "revenue": 4394.22
  },
  {
    "date": "2025-08-10",
    "purchaseCost": 5375.06,
    "revenue": 7667.78
  },
  {
    "date": "2025-08-11",
    "purchaseCost": 13770.08,
    "revenue": 21219.86
  },
  {
    "date": "2025-08-12",
    "purchaseCost": 14107.64,
    "revenue": 20144.65
  },
  {
    "date": "2025-08-13",
    "purchaseCost": 12404.31,
    "revenue": 17094.23
  },
  {
    "date": "2025-08-14",
    "purchaseCost": 8340.16,
    "revenue": 12190.08
  },
  {
    "date": "2025-08-15",
    "purchaseCost": 3111.52,
    "revenue": 4395.88
  },
  {
    "date": "2025-08-16",
    "purchaseCost": 8729.32,
    "revenue": 13066.12
  },
  {
    "date": "2025-08-17",
    "purchaseCost": 605,
    "revenue": 900.83
  },
  {
    "date": "2025-08-18",
    "purchaseCost": 9837.47,
    "revenue": 14085.95
  },
  {
    "date": "2025-08-19",
    "purchaseCost": 8672.67,
    "revenue": 12089.27
  },
  {
    "date": "2025-08-20",
    "purchaseCost": 11138.99,
    "revenue": 15147.11
  },
  {
    "date": "2025-08-21",
    "purchaseCost": 9550.6,
    "revenue": 14411.56
  },
  {
    "date": "2025-08-22",
    "purchaseCost": 4695.66,
    "revenue": 7066.12
  },
  {
    "date": "2025-08-23",
    "purchaseCost": 3472.67,
    "revenue": 5047.11
  },
  {
    "date": "2025-08-24",
    "purchaseCost": 5877.1,
    "revenue": 8066.11
  },
  {
    "date": "2025-08-25",
    "purchaseCost": 5367.26,
    "revenue": 7651.25
  },
  {
    "date": "2025-08-26",
    "purchaseCost": 5963.43,
    "revenue": 8271.91
  },
  {
    "date": "2025-08-27",
    "purchaseCost": 7865.1,
    "revenue": 11512.41
  },
  {
    "date": "2025-08-28",
    "purchaseCost": 7815,
    "revenue": 10781.81
  },
  {
    "date": "2025-08-29",
    "purchaseCost": 5660.43,
    "revenue": 8318.18
  },
  {
    "date": "2025-08-30",
    "purchaseCost": 7605.77,
    "revenue": 10519
  },
  {
    "date": "2025-08-31",
    "purchaseCost": 8959.8,
    "revenue": 12024.79
  },
  {
    "date": "2025-09-01",
    "purchaseCost": 1681.44,
    "revenue": 2492.56
  },
  {
    "date": "2025-09-02",
    "purchaseCost": 2377.19,
    "revenue": 4661.16
  },
  {
    "date": "2025-09-03",
    "purchaseCost": 14713.84,
    "revenue": 20584.28
  },
  {
    "date": "2025-09-04",
    "purchaseCost": 6526.56,
    "revenue": 8486.78
  },
  {
    "date": "2025-09-05",
    "purchaseCost": 8096.69,
    "revenue": 11254.55
  },
  {
    "date": "2025-09-06",
    "purchaseCost": 3673.2,
    "revenue": 5099.17
  },
  {
    "date": "2025-09-07",
    "purchaseCost": 3802.9,
    "revenue": 4942.15
  },
  {
    "date": "2025-09-08",
    "purchaseCost": 5649.36,
    "revenue": 7230.58
  },
  {
    "date": "2025-09-09",
    "purchaseCost": 10492.48,
    "revenue": 15535.53
  },
  {
    "date": "2025-09-10",
    "purchaseCost": 16284.06,
    "revenue": 23590.07
  },
  {
    "date": "2025-09-11",
    "purchaseCost": 15003.69,
    "revenue": 21328.09
  },
  {
    "date": "2025-09-12",
    "purchaseCost": 15254.66,
    "revenue": 21727.27
  },
  {
    "date": "2025-09-13",
    "purchaseCost": 21911.76,
    "revenue": 32203.28
  },
  {
    "date": "2025-09-14",
    "purchaseCost": 11749.16,
    "revenue": 18087.6
  },
  {
    "date": "2025-09-15",
    "purchaseCost": 21220.46,
    "revenue": 29633.88
  },
  {
    "date": "2025-09-16",
    "purchaseCost": 12635.35,
    "revenue": 18271.9
  },
  {
    "date": "2025-09-17",
    "purchaseCost": 12450.44,
    "revenue": 18258.67
  },
  {
    "date": "2025-09-18",
    "purchaseCost": 18137.77,
    "revenue": 27101.65
  },
  {
    "date": "2025-09-19",
    "purchaseCost": 6899.88,
    "revenue": 9719
  },
  {
    "date": "2025-09-20",
    "purchaseCost": 7306.4,
    "revenue": 11310.74
  },
  {
    "date": "2025-09-21",
    "purchaseCost": 907.5,
    "revenue": 1561.98
  },
  {
    "date": "2025-09-22",
    "purchaseCost": 14880.12,
    "revenue": 21848.75
  },
  {
    "date": "2025-09-23",
    "purchaseCost": 10544.29,
    "revenue": 13686.77
  },
  {
    "date": "2025-09-24",
    "purchaseCost": 10832.38,
    "revenue": 15976.04
  },
  {
    "date": "2025-09-25",
    "purchaseCost": 23812.06,
    "revenue": 34090.08
  },
  {
    "date": "2025-09-26",
    "purchaseCost": 12895.72,
    "revenue": 19106.61
  },
  {
    "date": "2025-09-27",
    "purchaseCost": 7913.9,
    "revenue": 11851.25
  },
  {
    "date": "2025-09-28",
    "purchaseCost": 13863.6,
    "revenue": 20988.43
  },
  {
    "date": "2025-09-29",
    "purchaseCost": 11854.4,
    "revenue": 16742.99
  },
  {
    "date": "2025-09-30",
    "purchaseCost": 14062.22,
    "revenue": 20721.48
  },
  {
    "date": "2025-10-01",
    "purchaseCost": 8647.85,
    "revenue": 12868.6
  },
  {
    "date": "2025-10-02",
    "purchaseCost": 12189.54,
    "revenue": 18383.47
  },
  {
    "date": "2025-10-03",
    "purchaseCost": 6721.9,
    "revenue": 10271.89
  },
  {
    "date": "2025-10-04",
    "purchaseCost": 16436.52,
    "revenue": 24204.13
  },
  {
    "date": "2025-10-05",
    "purchaseCost": 12353.3,
    "revenue": 19352.88
  },
  {
    "date": "2025-10-06",
    "purchaseCost": 8268.33,
    "revenue": 12809.08
  },
  {
    "date": "2025-10-07",
    "purchaseCost": 24713.55,
    "revenue": 35723.97
  },
  {
    "date": "2025-10-08",
    "purchaseCost": 9574.04,
    "revenue": 14436.36
  },
  {
    "date": "2025-10-09",
    "purchaseCost": 20035.27,
    "revenue": 29156.19
  },
  {
    "date": "2025-10-10",
    "purchaseCost": 8974.17,
    "revenue": 13884.29
  },
  {
    "date": "2025-10-11",
    "purchaseCost": 4811.19,
    "revenue": 6966.12
  },
  {
    "date": "2025-10-12",
    "purchaseCost": 8176.83,
    "revenue": 11988.43
  },
  {
    "date": "2025-10-13",
    "purchaseCost": 6988.14,
    "revenue": 10367.78
  },
  {
    "date": "2025-10-14",
    "purchaseCost": 17626.04,
    "revenue": 26610.74
  },
  {
    "date": "2025-10-15",
    "purchaseCost": 10777.65,
    "revenue": 15422.31
  },
  {
    "date": "2025-10-16",
    "purchaseCost": 16816.97,
    "revenue": 23276.04
  },
  {
    "date": "2025-10-17",
    "purchaseCost": 15581.65,
    "revenue": 23085.96
  },
  {
    "date": "2025-10-18",
    "purchaseCost": 7857.6,
    "revenue": 12184.3
  },
  {
    "date": "2025-10-19",
    "purchaseCost": 7299.97,
    "revenue": 11701.65
  },
  {
    "date": "2025-10-20",
    "purchaseCost": 9161.45,
    "revenue": 13016.54
  },
  {
    "date": "2025-10-21",
    "purchaseCost": 13445.62,
    "revenue": 20248.75
  },
  {
    "date": "2025-10-22",
    "purchaseCost": 22462.65,
    "revenue": 32736.37
  },
  {
    "date": "2025-10-23",
    "purchaseCost": 7965.93,
    "revenue": 11448.76
  },
  {
    "date": "2025-10-24",
    "purchaseCost": 4788.3,
    "revenue": 6768.6
  },
  {
    "date": "2025-10-25",
    "purchaseCost": 1613.33,
    "revenue": 2388.43
  },
  {
    "date": "2025-10-26",
    "purchaseCost": 12762.62,
    "revenue": 19545.46
  },
  {
    "date": "2025-10-27",
    "purchaseCost": 6107.62,
    "revenue": 9891.73
  },
  {
    "date": "2025-10-28",
    "purchaseCost": 10883.29,
    "revenue": 15868.59
  },
  {
    "date": "2025-10-29",
    "purchaseCost": 6943.13,
    "revenue": 9636.37
  },
  {
    "date": "2025-10-30",
    "purchaseCost": 8207.47,
    "revenue": 12354.55
  },
  {
    "date": "2025-10-31",
    "purchaseCost": 4812.93,
    "revenue": 8074.38
  },
  {
    "date": "2025-11-01",
    "purchaseCost": 3546.84,
    "revenue": 5335.54
  },
  {
    "date": "2025-11-02",
    "purchaseCost": 8210.71,
    "revenue": 12114.88
  },
  {
    "date": "2025-11-03",
    "purchaseCost": 11163.69,
    "revenue": 16903.3
  },
  {
    "date": "2025-11-04",
    "purchaseCost": 12857.35,
    "revenue": 18792.57
  },
  {
    "date": "2025-11-05",
    "purchaseCost": 7620.12,
    "revenue": 12569.42
  },
  {
    "date": "2025-11-06",
    "purchaseCost": 8815.71,
    "revenue": 13718.18
  },
  {
    "date": "2025-11-07",
    "purchaseCost": 6993.7,
    "revenue": 8421.5
  },
  {
    "date": "2025-11-08",
    "purchaseCost": 8574.7,
    "revenue": 11739.68
  },
  {
    "date": "2025-11-09",
    "purchaseCost": 7672.09,
    "revenue": 11600.82
  },
  {
    "date": "2025-11-10",
    "purchaseCost": 18050.87,
    "revenue": 27029.75
  },
  {
    "date": "2025-11-11",
    "purchaseCost": 16212.9,
    "revenue": 21271.9
  },
  {
    "date": "2025-11-12",
    "purchaseCost": 25846.32,
    "revenue": 33919.86
  },
  {
    "date": "2025-11-13",
    "purchaseCost": 9687.03,
    "revenue": 11314.88
  },
  {
    "date": "2025-11-14",
    "purchaseCost": 13144.18,
    "revenue": 15652.9
  },
  {
    "date": "2025-11-15",
    "purchaseCost": 5630.53,
    "revenue": 8833.05
  },
  {
    "date": "2025-11-16",
    "purchaseCost": 10278.78,
    "revenue": 14919.84
  },
  {
    "date": "2025-11-17",
    "purchaseCost": 17031.62,
    "revenue": 25295.86
  },
  {
    "date": "2025-11-18",
    "purchaseCost": 16241.89,
    "revenue": 23549.6
  },
  {
    "date": "2025-11-19",
    "purchaseCost": 10058.19,
    "revenue": 14214.89
  },
  {
    "date": "2025-11-20",
    "purchaseCost": 3986.43,
    "revenue": 4247.11
  },
  {
    "date": "2025-11-21",
    "purchaseCost": 6632.95,
    "revenue": 10064.46
  },
  {
    "date": "2025-11-22",
    "purchaseCost": 3972.03,
    "revenue": 4048.76
  },
  {
    "date": "2025-11-23",
    "purchaseCost": 14880.42,
    "revenue": 20343.81
  },
  {
    "date": "2025-11-24",
    "purchaseCost": 12175.35,
    "revenue": 16949.59
  },
  {
    "date": "2025-11-25",
    "purchaseCost": 5381.41,
    "revenue": 7915.7
  },
  {
    "date": "2025-11-26",
    "purchaseCost": 12438.99,
    "revenue": 17635.54
  },
  {
    "date": "2025-11-27",
    "purchaseCost": 11710.99,
    "revenue": 15336.38
  },
  {
    "date": "2025-11-28",
    "purchaseCost": 19042.3,
    "revenue": 23967.78
  },
  {
    "date": "2025-11-29",
    "purchaseCost": 12507.53,
    "revenue": 17678.52
  },
  {
    "date": "2025-11-30",
    "purchaseCost": 5445,
    "revenue": 7549.6
  },
  {
    "date": "2025-12-01",
    "purchaseCost": 5800.27,
    "revenue": 7736.37
  },
  {
    "date": "2025-12-02",
    "purchaseCost": 6214.05,
    "revenue": 10867.76
  },
  {
    "date": "2025-12-03",
    "purchaseCost": 3327.5,
    "revenue": 5453.72
  },
  {
    "date": "2025-12-04",
    "purchaseCost": 6519.09,
    "revenue": 9932.24
  },
  {
    "date": "2025-12-05",
    "purchaseCost": 11423.77,
    "revenue": 15594.23
  },
  {
    "date": "2025-12-06",
    "purchaseCost": 1815,
    "revenue": 2966.94
  },
  {
    "date": "2025-12-07",
    "purchaseCost": 3378.9,
    "revenue": 4734.72
  },
  {
    "date": "2025-12-08",
    "purchaseCost": 6675.97,
    "revenue": 9499.19
  },
  {
    "date": "2025-12-09",
    "purchaseCost": 7036.87,
    "revenue": 11239.67
  },
  {
    "date": "2025-12-10",
    "purchaseCost": 14469.83,
    "revenue": 20822.31
  },
  {
    "date": "2025-12-11",
    "purchaseCost": 3235.37,
    "revenue": 4565.29
  },
  {
    "date": "2025-12-12",
    "purchaseCost": 5341.5,
    "revenue": 8702.48
  },
  {
    "date": "2025-12-13",
    "purchaseCost": 5440.97,
    "revenue": 7898.36
  },
  {
    "date": "2025-12-14",
    "purchaseCost": 2832.61,
    "revenue": 4520.66
  },
  {
    "date": "2025-12-15",
    "purchaseCost": 12512.53,
    "revenue": 17975.22
  },
  {
    "date": "2025-12-16",
    "purchaseCost": 6789.13,
    "revenue": 12047.93
  },
  {
    "date": "2025-12-17",
    "purchaseCost": 12584.56,
    "revenue": 17900
  },
  {
    "date": "2025-12-18",
    "purchaseCost": 3347.5,
    "revenue": 6892.56
  },
  {
    "date": "2025-12-21",
    "purchaseCost": 1310.73,
    "revenue": 2057.85
  },
  {
    "date": "2025-12-22",
    "purchaseCost": 1815,
    "revenue": 2603.31
  },
  {
    "date": "2025-12-24",
    "purchaseCost": 4263.81,
    "revenue": 5786.78
  },
  {
    "date": "2025-12-25",
    "purchaseCost": 3975.71,
    "revenue": 5851.24
  },
  {
    "date": "2025-12-26",
    "purchaseCost": 11099.72,
    "revenue": 15232.22
  },
  {
    "date": "2025-12-27",
    "purchaseCost": 9500.94,
    "revenue": 13381.82
  },
  {
    "date": "2025-12-28",
    "purchaseCost": 6912.73,
    "revenue": 10068.6
  },
  {
    "date": "2025-12-29",
    "purchaseCost": 1584.52,
    "revenue": 1975.21
  },
  {
    "date": "2025-12-30",
    "purchaseCost": 7090.6,
    "revenue": 10555.37
  },
  {
    "date": "2025-12-31",
    "purchaseCost": 1815,
    "revenue": 2603.31
  },
  {
    "date": "2026-01-01",
    "purchaseCost": 1815,
    "revenue": 2603.31
  },
  {
    "date": "2026-01-02",
    "purchaseCost": 10950.81,
    "revenue": 15732.24
  },
  {
    "date": "2026-01-03",
    "purchaseCost": 3876.84,
    "revenue": 5882.65
  },
  {
    "date": "2026-01-04",
    "purchaseCost": 10523.46,
    "revenue": 14952.9
  },
  {
    "date": "2026-01-05",
    "purchaseCost": 4515.12,
    "revenue": 7203.3
  },
  {
    "date": "2026-01-06",
    "purchaseCost": 266.2,
    "revenue": 303.31
  },
  {
    "date": "2026-01-07",
    "purchaseCost": 6895.02,
    "revenue": 8904.13
  },
  {
    "date": "2026-01-08",
    "purchaseCost": 1382.73,
    "revenue": 2057.85
  },
  {
    "date": "2026-01-09",
    "purchaseCost": 7605,
    "revenue": 12121.49
  },
  {
    "date": "2026-01-10",
    "purchaseCost": 1815,
    "revenue": 2603.31
  },
  {
    "date": "2026-01-11",
    "purchaseCost": 15657.42,
    "revenue": 20442.16
  },
  {
    "date": "2026-01-12",
    "purchaseCost": 5065.7,
    "revenue": 7132.23
  },
  {
    "date": "2026-01-13",
    "purchaseCost": 6952.42,
    "revenue": 9723.13
  },
  {
    "date": "2026-01-14",
    "purchaseCost": 6570.05,
    "revenue": 8404.13
  },
  {
    "date": "2026-01-15",
    "purchaseCost": 8037.86,
    "revenue": 10673.55
  },
  {
    "date": "2026-01-16",
    "purchaseCost": 9910.57,
    "revenue": 13025.61
  },
  {
    "date": "2026-01-17",
    "purchaseCost": 5012.73,
    "revenue": 7264.47
  },
  {
    "date": "2026-01-18",
    "purchaseCost": 9834.96,
    "revenue": 13420.67
  },
  {
    "date": "2026-01-19",
    "purchaseCost": 13072.58,
    "revenue": 17097.54
  },
  {
    "date": "2026-01-20",
    "purchaseCost": 902.42,
    "revenue": 1321.49
  },
  {
    "date": "2026-01-21",
    "purchaseCost": 6685.36,
    "revenue": 8685.12
  },
  {
    "date": "2026-01-22",
    "purchaseCost": 3226.67,
    "revenue": 5652.06
  },
  {
    "date": "2026-01-23",
    "purchaseCost": 7718.57,
    "revenue": 11107.44
  },
  {
    "date": "2026-01-24",
    "purchaseCost": 5156.9,
    "revenue": 7002.47
  },
  {
    "date": "2026-01-25",
    "purchaseCost": 1008.33,
    "revenue": 1479.34
  },
  {
    "date": "2026-01-26",
    "purchaseCost": 10597.25,
    "revenue": 14579.34
  },
  {
    "date": "2026-01-27",
    "purchaseCost": 1815,
    "revenue": 2628.09
  },
  {
    "date": "2026-01-28",
    "purchaseCost": 12110.74,
    "revenue": 17185.15
  },
  {
    "date": "2026-01-29",
    "purchaseCost": 1872.62,
    "revenue": 2528.1
  },
  {
    "date": "2026-01-30",
    "purchaseCost": 12873.8,
    "revenue": 18871.07
  },
  {
    "date": "2026-01-31",
    "purchaseCost": 11539.53,
    "revenue": 15998.36
  },
  {
    "date": "2026-02-01",
    "purchaseCost": 10201.9,
    "revenue": 13985.13
  },
  {
    "date": "2026-02-02",
    "purchaseCost": 6784.64,
    "revenue": 9209.09
  },
  {
    "date": "2026-02-03",
    "purchaseCost": 3125.83,
    "revenue": 4955.37
  },
  {
    "date": "2026-02-04",
    "purchaseCost": 2448.81,
    "revenue": 2967.77
  },
  {
    "date": "2026-02-05",
    "purchaseCost": 3177.28,
    "revenue": 4552.9
  },
  {
    "date": "2026-02-06",
    "purchaseCost": 6035.51,
    "revenue": 8321.5
  },
  {
    "date": "2026-02-07",
    "purchaseCost": 5185.83,
    "revenue": 7982.64
  },
  {
    "date": "2026-02-08",
    "purchaseCost": 13842.72,
    "revenue": 18639.68
  },
  {
    "date": "2026-02-09",
    "purchaseCost": 2823.33,
    "revenue": 3952.89
  },
  {
    "date": "2026-02-10",
    "purchaseCost": 11150.54,
    "revenue": 14610.75
  },
  {
    "date": "2026-02-11",
    "purchaseCost": 9539.38,
    "revenue": 12357.87
  },
  {
    "date": "2026-02-12",
    "purchaseCost": 12557.34,
    "revenue": 16966.12
  },
  {
    "date": "2026-02-13",
    "purchaseCost": 705.83,
    "revenue": 1396.69
  },
  {
    "date": "2026-02-14",
    "purchaseCost": 2304.76,
    "revenue": 3049.59
  },
  {
    "date": "2026-02-15",
    "purchaseCost": 8780.68,
    "revenue": 12163.64
  },
  {
    "date": "2026-02-16",
    "purchaseCost": 6814.26,
    "revenue": 9608.27
  },
  {
    "date": "2026-02-17",
    "purchaseCost": 11070.2,
    "revenue": 19335.54
  },
  {
    "date": "2026-02-18",
    "purchaseCost": 6199.37,
    "revenue": 8628.1
  },
  {
    "date": "2026-02-19",
    "purchaseCost": 7585.73,
    "revenue": 10793.38
  },
  {
    "date": "2026-02-20",
    "purchaseCost": 3563.35,
    "revenue": 4919.01
  },
  {
    "date": "2026-02-21",
    "purchaseCost": 5870.92,
    "revenue": 7995.05
  },
  {
    "date": "2026-02-22",
    "purchaseCost": 6239.23,
    "revenue": 7662.81
  },
  {
    "date": "2026-02-23",
    "purchaseCost": 15240.23,
    "revenue": 23256.21
  },
  {
    "date": "2026-02-24",
    "purchaseCost": 12062.34,
    "revenue": 15704.96
  },
  {
    "date": "2026-02-25",
    "purchaseCost": 13918.63,
    "revenue": 17988.44
  },
  {
    "date": "2026-02-26",
    "purchaseCost": 5668.57,
    "revenue": 7926.45
  },
  {
    "date": "2026-02-27",
    "purchaseCost": 14905.54,
    "revenue": 19885.14
  },
  {
    "date": "2026-02-28",
    "purchaseCost": 11031.87,
    "revenue": 15001.65
  },
  {
    "date": "2026-03-01",
    "purchaseCost": 8285.37,
    "revenue": 10819.02
  },
  {
    "date": "2026-03-02",
    "purchaseCost": 10961.82,
    "revenue": 14588.43
  },
  {
    "date": "2026-03-03",
    "purchaseCost": 14043.73,
    "revenue": 18687.58
  },
  {
    "date": "2026-03-04",
    "purchaseCost": 19479.08,
    "revenue": 28317.37
  },
  {
    "date": "2026-03-05",
    "purchaseCost": 18183.24,
    "revenue": 23421.51
  },
  {
    "date": "2026-03-06",
    "purchaseCost": 13881.16,
    "revenue": 18364.47
  },
  {
    "date": "2026-03-07",
    "purchaseCost": 7992.89,
    "revenue": 9565.31
  },
  {
    "date": "2026-03-08",
    "purchaseCost": 4940.83,
    "revenue": 6273.55
  },
  {
    "date": "2026-03-09",
    "purchaseCost": 11327.87,
    "revenue": 14454.54
  },
  {
    "date": "2026-03-10",
    "purchaseCost": 11251.25,
    "revenue": 15320.68
  },
  {
    "date": "2026-03-11",
    "purchaseCost": 14406,
    "revenue": 19056.22
  },
  {
    "date": "2026-03-12",
    "purchaseCost": 7317.62,
    "revenue": 10222.32
  },
  {
    "date": "2026-03-13",
    "purchaseCost": 13396.33,
    "revenue": 17518.2
  },
  {
    "date": "2026-03-14",
    "purchaseCost": 9905.4,
    "revenue": 11533.06
  },
  {
    "date": "2026-03-15",
    "purchaseCost": 14231.72,
    "revenue": 18230.58
  },
  {
    "date": "2026-03-16",
    "purchaseCost": 17724.26,
    "revenue": 22445.46
  },
  {
    "date": "2026-03-17",
    "purchaseCost": 22519.85,
    "revenue": 27089.28
  },
  {
    "date": "2026-03-18",
    "purchaseCost": 12358.21,
    "revenue": 15513.23
  },
  {
    "date": "2026-03-19",
    "purchaseCost": 23745.36,
    "revenue": 27901.66
  },
  {
    "date": "2026-03-20",
    "purchaseCost": 11245.48,
    "revenue": 14082.65
  },
  {
    "date": "2026-03-21",
    "purchaseCost": 16737.21,
    "revenue": 22179.35
  },
  {
    "date": "2026-03-22",
    "purchaseCost": 15056.83,
    "revenue": 19329.74
  },
  {
    "date": "2026-03-23",
    "purchaseCost": 20408.66,
    "revenue": 25699.19
  },
  {
    "date": "2026-03-24",
    "purchaseCost": 17758.41,
    "revenue": 23249.19
  },
  {
    "date": "2026-03-25",
    "purchaseCost": 25728.79,
    "revenue": 32793.4
  },
  {
    "date": "2026-03-26",
    "purchaseCost": 11009.06,
    "revenue": 15330.57
  },
  {
    "date": "2026-03-27",
    "purchaseCost": 7931.69,
    "revenue": 10788.43
  },
  {
    "date": "2026-03-28",
    "purchaseCost": 12331.74,
    "revenue": 15718.19
  },
  {
    "date": "2026-03-29",
    "purchaseCost": 10382.56,
    "revenue": 14542.14
  },
  {
    "date": "2026-03-30",
    "purchaseCost": 12795.49,
    "revenue": 17430.5
  },
  {
    "date": "2026-03-31",
    "purchaseCost": 13893.34,
    "revenue": 19123.15
  },
  {
    "date": "2026-04-01",
    "purchaseCost": 12650.12,
    "revenue": 18197.51
  },
  {
    "date": "2026-04-02",
    "purchaseCost": 20316.19,
    "revenue": 23692.59
  },
  {
    "date": "2026-04-03",
    "purchaseCost": 6437.29,
    "revenue": 9343.79
  },
  {
    "date": "2026-04-04",
    "purchaseCost": 5102.78,
    "revenue": 6669.42
  },
  {
    "date": "2026-04-05",
    "purchaseCost": 3257.62,
    "revenue": 4618.19
  },
  {
    "date": "2026-04-06",
    "purchaseCost": 20685.23,
    "revenue": 28787.61
  },
  {
    "date": "2026-04-07",
    "purchaseCost": 15561.92,
    "revenue": 19986.79
  },
  {
    "date": "2026-04-08",
    "purchaseCost": 12958.13,
    "revenue": 16911.58
  },
  {
    "date": "2026-04-09",
    "purchaseCost": 8853.16,
    "revenue": 12142.16
  },
  {
    "date": "2026-04-10",
    "purchaseCost": 12567.14,
    "revenue": 16251.25
  },
  {
    "date": "2026-04-11",
    "purchaseCost": 9035.02,
    "revenue": 11733.9
  },
  {
    "date": "2026-04-12",
    "purchaseCost": 3363.51,
    "revenue": 3785.13
  },
  {
    "date": "2026-04-13",
    "purchaseCost": 19029.77,
    "revenue": 26084.3
  },
  {
    "date": "2026-04-14",
    "purchaseCost": 19787.02,
    "revenue": 26576.9
  },
  {
    "date": "2026-04-15",
    "purchaseCost": 14043.77,
    "revenue": 19285.15
  },
  {
    "date": "2026-04-16",
    "purchaseCost": 6950.51,
    "revenue": 8761.16
  },
  {
    "date": "2026-04-17",
    "purchaseCost": 15737,
    "revenue": 18662.83
  },
  {
    "date": "2026-04-18",
    "purchaseCost": 18878.05,
    "revenue": 25020.69
  },
  {
    "date": "2026-04-19",
    "purchaseCost": 21766.69,
    "revenue": 29706.62
  },
  {
    "date": "2026-04-20",
    "purchaseCost": 11862.16,
    "revenue": 18956.12
  },
  {
    "date": "2026-04-21",
    "purchaseCost": 6263.77,
    "revenue": 9216.53
  },
  {
    "date": "2026-04-22",
    "purchaseCost": 14231.37,
    "revenue": 17999.18
  },
  {
    "date": "2026-04-23",
    "purchaseCost": 14547.47,
    "revenue": 20219.86
  },
  {
    "date": "2026-04-24",
    "purchaseCost": 6189.06,
    "revenue": 7962.81
  },
  {
    "date": "2026-04-25",
    "purchaseCost": 12262.18,
    "revenue": 15170.24
  },
  {
    "date": "2026-04-26",
    "purchaseCost": 5763.31,
    "revenue": 7644.63
  },
  {
    "date": "2026-04-27",
    "purchaseCost": 9591.83,
    "revenue": 11926.45
  },
  {
    "date": "2026-04-28",
    "purchaseCost": 11335.34,
    "revenue": 15507.43
  },
  {
    "date": "2026-04-29",
    "purchaseCost": 11665.86,
    "revenue": 14928.09
  },
  {
    "date": "2026-04-30",
    "purchaseCost": 18444.6,
    "revenue": 24714.07
  },
  {
    "date": "2026-05-01",
    "purchaseCost": 11732.53,
    "revenue": 14398.36
  },
  {
    "date": "2026-05-02",
    "purchaseCost": 2880.95,
    "revenue": 3420.66
  }
];
