// Auto-generated by scripts/updateData.js — last update: 2026-08-07
// CZ: daily margin data (CZK). purchaseCost = nákupní cena bez DPH (buy_price přepočten přes vatRate × quantity), revenue = tržby bez DPH.

export interface MarginDailyRecord {
  date: string;
  purchaseCost: number;
  revenue: number;
}

export const prodejnaMarginDataCZ: MarginDailyRecord[] = [
  {
    "date": "2025-04-03",
    "purchaseCost": 833.06,
    "revenue": 1528.1
  },
  {
    "date": "2025-04-07",
    "purchaseCost": 1416,
    "revenue": 2065.29
  },
  {
    "date": "2025-04-09",
    "purchaseCost": 1416,
    "revenue": 2230.58
  },
  {
    "date": "2025-04-10",
    "purchaseCost": 3552.93,
    "revenue": 5328.93
  },
  {
    "date": "2025-04-11",
    "purchaseCost": 1416,
    "revenue": 1941.32
  },
  {
    "date": "2025-04-15",
    "purchaseCost": 1000,
    "revenue": 3098.35
  },
  {
    "date": "2025-04-16",
    "purchaseCost": 1666.94,
    "revenue": 3098.35
  },
  {
    "date": "2025-04-17",
    "purchaseCost": 2041.78,
    "revenue": 4212.4
  },
  {
    "date": "2025-04-24",
    "purchaseCost": 689.26,
    "revenue": 1032.23
  },
  {
    "date": "2025-04-25",
    "purchaseCost": 3853.79,
    "revenue": 5965.29
  },
  {
    "date": "2025-04-26",
    "purchaseCost": 260,
    "revenue": 380.17
  },
  {
    "date": "2025-04-27",
    "purchaseCost": 1142.98,
    "revenue": 1809.92
  },
  {
    "date": "2025-04-28",
    "purchaseCost": 1318.18,
    "revenue": 2023.97
  },
  {
    "date": "2025-04-30",
    "purchaseCost": 3750.71,
    "revenue": 7063.64
  },
  {
    "date": "2025-05-02",
    "purchaseCost": 1904.96,
    "revenue": 3304.96
  },
  {
    "date": "2025-05-06",
    "purchaseCost": 1239,
    "revenue": 1734.71
  },
  {
    "date": "2025-05-07",
    "purchaseCost": 1416,
    "revenue": 2230.58
  },
  {
    "date": "2025-05-09",
    "purchaseCost": 4062.28,
    "revenue": 6733.06
  },
  {
    "date": "2025-05-12",
    "purchaseCost": 809.92,
    "revenue": 2023.97
  },
  {
    "date": "2025-05-15",
    "purchaseCost": 3928.34,
    "revenue": 7311.58
  },
  {
    "date": "2025-05-19",
    "purchaseCost": 0,
    "revenue": 2230.58
  },
  {
    "date": "2025-05-21",
    "purchaseCost": 3649.94,
    "revenue": 9244.64
  },
  {
    "date": "2025-05-23",
    "purchaseCost": 928.6,
    "revenue": 2023.97
  },
  {
    "date": "2025-05-27",
    "purchaseCost": 1327.51,
    "revenue": 2354.55
  },
  {
    "date": "2025-05-28",
    "purchaseCost": 2464.96,
    "revenue": 3371.9
  },
  {
    "date": "2025-06-02",
    "purchaseCost": 197.2,
    "revenue": 426.44
  },
  {
    "date": "2025-06-03",
    "purchaseCost": 1309.5,
    "revenue": 2437.19
  },
  {
    "date": "2025-06-04",
    "purchaseCost": 2071.49,
    "revenue": 4378.51
  },
  {
    "date": "2025-06-05",
    "purchaseCost": 1069.8,
    "revenue": 2335.54
  },
  {
    "date": "2025-06-06",
    "purchaseCost": 500,
    "revenue": 900.83
  },
  {
    "date": "2025-06-09",
    "purchaseCost": 1327.51,
    "revenue": 2354.55
  },
  {
    "date": "2025-06-10",
    "purchaseCost": 3256.1,
    "revenue": 7476.87
  },
  {
    "date": "2025-06-13",
    "purchaseCost": 2368.4,
    "revenue": 4089.26
  },
  {
    "date": "2025-06-17",
    "purchaseCost": 719.83,
    "revenue": 1032.23
  },
  {
    "date": "2025-06-18",
    "purchaseCost": 2976.2,
    "revenue": 4990.91
  },
  {
    "date": "2025-06-24",
    "purchaseCost": 719.83,
    "revenue": 892.56
  },
  {
    "date": "2025-06-30",
    "purchaseCost": 1071.4,
    "revenue": 1941.32
  },
  {
    "date": "2025-07-01",
    "purchaseCost": 2881.91,
    "revenue": 5114.05
  },
  {
    "date": "2025-07-02",
    "purchaseCost": 2478,
    "revenue": 4047.94
  },
  {
    "date": "2025-07-03",
    "purchaseCost": 5017.28,
    "revenue": 8054.55
  },
  {
    "date": "2025-07-04",
    "purchaseCost": 1239,
    "revenue": 2023.97
  },
  {
    "date": "2025-07-08",
    "purchaseCost": 719.83,
    "revenue": 892.56
  },
  {
    "date": "2025-07-09",
    "purchaseCost": 2809.45,
    "revenue": 5107.44
  },
  {
    "date": "2025-07-11",
    "purchaseCost": 5977.1,
    "revenue": 10525.62
  },
  {
    "date": "2025-07-14",
    "purchaseCost": 952.4,
    "revenue": 1858.68
  },
  {
    "date": "2025-07-15",
    "purchaseCost": 3427.35,
    "revenue": 5635.53
  },
  {
    "date": "2025-07-16",
    "purchaseCost": 5268.73,
    "revenue": 9820.66
  },
  {
    "date": "2025-07-18",
    "purchaseCost": 3600.75,
    "revenue": 5668.6
  },
  {
    "date": "2025-07-21",
    "purchaseCost": 2854.9,
    "revenue": 4857.03
  },
  {
    "date": "2025-07-22",
    "purchaseCost": 2095.46,
    "revenue": 3676.04
  },
  {
    "date": "2025-07-23",
    "purchaseCost": 4202.61,
    "revenue": 6948.77
  },
  {
    "date": "2025-07-24",
    "purchaseCost": 2368.39,
    "revenue": 3676.03
  },
  {
    "date": "2025-07-25",
    "purchaseCost": 1189.26,
    "revenue": 1793.39
  },
  {
    "date": "2025-07-29",
    "purchaseCost": 719.83,
    "revenue": 892.56
  },
  {
    "date": "2025-08-05",
    "purchaseCost": 2928.84,
    "revenue": 5106.61
  },
  {
    "date": "2025-08-06",
    "purchaseCost": 719.83,
    "revenue": 892.56
  },
  {
    "date": "2025-08-07",
    "purchaseCost": 1785.7,
    "revenue": 2884.3
  },
  {
    "date": "2025-08-08",
    "purchaseCost": 512.59,
    "revenue": 1485.12
  },
  {
    "date": "2025-08-11",
    "purchaseCost": 3119.01,
    "revenue": 5486.78
  },
  {
    "date": "2025-08-12",
    "purchaseCost": 714.21,
    "revenue": 1231.4
  },
  {
    "date": "2025-08-13",
    "purchaseCost": 3357.35,
    "revenue": 5677.68
  },
  {
    "date": "2025-08-14",
    "purchaseCost": 4154.1,
    "revenue": 7000
  },
  {
    "date": "2025-08-15",
    "purchaseCost": 500,
    "revenue": 900.83
  },
  {
    "date": "2025-08-18",
    "purchaseCost": 2255.53,
    "revenue": 3965.29
  },
  {
    "date": "2025-08-19",
    "purchaseCost": 4334.21,
    "revenue": 7345.46
  },
  {
    "date": "2025-08-20",
    "purchaseCost": 4438.4,
    "revenue": 7081.82
  },
  {
    "date": "2025-08-21",
    "purchaseCost": 654.71,
    "revenue": 1131.4
  },
  {
    "date": "2025-08-22",
    "purchaseCost": 2166.41,
    "revenue": 3785.12
  },
  {
    "date": "2025-08-25",
    "purchaseCost": 2602.51,
    "revenue": 4452.9
  },
  {
    "date": "2025-08-26",
    "purchaseCost": 2285.7,
    "revenue": 3537.19
  },
  {
    "date": "2025-08-28",
    "purchaseCost": 2357.19,
    "revenue": 3923.96
  },
  {
    "date": "2025-08-29",
    "purchaseCost": 1428.6,
    "revenue": 2816.53
  },
  {
    "date": "2025-09-01",
    "purchaseCost": 428.5,
    "revenue": 793.39
  },
  {
    "date": "2025-09-03",
    "purchaseCost": 1666.69,
    "revenue": 2685.12
  },
  {
    "date": "2025-09-04",
    "purchaseCost": 1239,
    "revenue": 1975.21
  },
  {
    "date": "2025-09-05",
    "purchaseCost": 2191.4,
    "revenue": 3537.19
  },
  {
    "date": "2025-09-08",
    "purchaseCost": 1416,
    "revenue": 2223.14
  },
  {
    "date": "2025-09-10",
    "purchaseCost": 4677.69,
    "revenue": 8358.68
  },
  {
    "date": "2025-09-11",
    "purchaseCost": 500,
    "revenue": 875.21
  },
  {
    "date": "2025-09-12",
    "purchaseCost": 654.76,
    "revenue": 1131.4
  },
  {
    "date": "2025-09-16",
    "purchaseCost": 1666.66,
    "revenue": 2801.65
  },
  {
    "date": "2025-09-17",
    "purchaseCost": 1309.53,
    "revenue": 1975.21
  },
  {
    "date": "2025-09-18",
    "purchaseCost": 2185.56,
    "revenue": 5024.8
  },
  {
    "date": "2025-09-19",
    "purchaseCost": 1309.52,
    "revenue": 1892.56
  },
  {
    "date": "2025-09-23",
    "purchaseCost": 1166.66,
    "revenue": 1727.27
  },
  {
    "date": "2025-09-25",
    "purchaseCost": 2572.24,
    "revenue": 4998.34
  },
  {
    "date": "2025-09-26",
    "purchaseCost": 916.66,
    "revenue": 1396.69
  },
  {
    "date": "2025-10-01",
    "purchaseCost": 616.37,
    "revenue": 1628.93
  },
  {
    "date": "2025-10-02",
    "purchaseCost": 1775.67,
    "revenue": 3007.44
  },
  {
    "date": "2025-10-03",
    "purchaseCost": 1519.57,
    "revenue": 2776.03
  },
  {
    "date": "2025-10-08",
    "purchaseCost": 1309.52,
    "revenue": 2223.14
  },
  {
    "date": "2025-10-09",
    "purchaseCost": 1879.5,
    "revenue": 3545.45
  },
  {
    "date": "2025-10-13",
    "purchaseCost": 2838.8,
    "revenue": 5082.65
  },
  {
    "date": "2025-10-14",
    "purchaseCost": 1250,
    "revenue": 2565.29
  },
  {
    "date": "2025-10-15",
    "purchaseCost": 1312.48,
    "revenue": 1608.26
  },
  {
    "date": "2025-10-16",
    "purchaseCost": 3838.8,
    "revenue": 6613.23
  },
  {
    "date": "2025-10-17",
    "purchaseCost": 6058.66,
    "revenue": 10674.39
  },
  {
    "date": "2025-10-21",
    "purchaseCost": 1428.57,
    "revenue": 2471.07
  },
  {
    "date": "2025-10-22",
    "purchaseCost": 1414.46,
    "revenue": 2803.31
  },
  {
    "date": "2025-10-23",
    "purchaseCost": 916.66,
    "revenue": 1561.98
  },
  {
    "date": "2025-10-29",
    "purchaseCost": 3214.32,
    "revenue": 5438.02
  },
  {
    "date": "2025-10-31",
    "purchaseCost": 876.03,
    "revenue": 2719.01
  },
  {
    "date": "2025-11-03",
    "purchaseCost": 1500,
    "revenue": 2851.24
  },
  {
    "date": "2025-11-04",
    "purchaseCost": 2778.12,
    "revenue": 4486.78
  },
  {
    "date": "2025-11-07",
    "purchaseCost": 2640.18,
    "revenue": 4040.5
  },
  {
    "date": "2025-11-10",
    "purchaseCost": 1768.26,
    "revenue": 3297.52
  },
  {
    "date": "2025-11-11",
    "purchaseCost": 3226.94,
    "revenue": 4909.09
  },
  {
    "date": "2025-11-12",
    "purchaseCost": 5921.68,
    "revenue": 8976.04
  },
  {
    "date": "2025-11-13",
    "purchaseCost": 2211.24,
    "revenue": 2305.79
  },
  {
    "date": "2025-11-14",
    "purchaseCost": 3711.24,
    "revenue": 4405.79
  },
  {
    "date": "2025-11-16",
    "purchaseCost": 1333.33,
    "revenue": 2388.43
  },
  {
    "date": "2025-11-21",
    "purchaseCost": 2815.7,
    "revenue": 5272.73
  },
  {
    "date": "2025-11-26",
    "purchaseCost": 1879.5,
    "revenue": 2471.07
  },
  {
    "date": "2025-11-28",
    "purchaseCost": 102,
    "revenue": 140.5
  },
  {
    "date": "2025-12-05",
    "purchaseCost": 2768.67,
    "revenue": 5098.35
  },
  {
    "date": "2025-12-09",
    "purchaseCost": 1315.7,
    "revenue": 3545.45
  },
  {
    "date": "2025-12-11",
    "purchaseCost": 440,
    "revenue": 955.37
  },
  {
    "date": "2025-12-12",
    "purchaseCost": 1414.46,
    "revenue": 3132.23
  },
  {
    "date": "2025-12-17",
    "purchaseCost": 1309.52,
    "revenue": 2057.85
  },
  {
    "date": "2025-12-18",
    "purchaseCost": 16.53,
    "revenue": 1652.89
  },
  {
    "date": "2026-01-05",
    "purchaseCost": 1981.5,
    "revenue": 3701.65
  },
  {
    "date": "2026-01-09",
    "purchaseCost": 160,
    "revenue": 239.67
  },
  {
    "date": "2026-01-14",
    "purchaseCost": 1144.28,
    "revenue": 2040.49
  },
  {
    "date": "2026-01-16",
    "purchaseCost": 2142.85,
    "revenue": 2731.4
  },
  {
    "date": "2026-01-19",
    "purchaseCost": 1988.76,
    "revenue": 2884.3
  },
  {
    "date": "2026-01-21",
    "purchaseCost": 719.83,
    "revenue": 1032.23
  },
  {
    "date": "2026-01-23",
    "purchaseCost": 3712.32,
    "revenue": 6658.68
  },
  {
    "date": "2026-01-28",
    "purchaseCost": 916.67,
    "revenue": 1644.63
  },
  {
    "date": "2026-01-30",
    "purchaseCost": 6532.94,
    "revenue": 11423.97
  },
  {
    "date": "2026-01-31",
    "purchaseCost": 958.67,
    "revenue": 1660.33
  },
  {
    "date": "2026-02-04",
    "purchaseCost": 2023.81,
    "revenue": 2967.77
  },
  {
    "date": "2026-02-12",
    "purchaseCost": 1428.57,
    "revenue": 1892.56
  },
  {
    "date": "2026-02-17",
    "purchaseCost": 1333.33,
    "revenue": 2388.43
  },
  {
    "date": "2026-02-19",
    "purchaseCost": 719.83,
    "revenue": 1032.23
  },
  {
    "date": "2026-02-25",
    "purchaseCost": 1547.62,
    "revenue": 2447.11
  },
  {
    "date": "2026-02-27",
    "purchaseCost": 5318.96,
    "revenue": 8069.44
  },
  {
    "date": "2026-03-04",
    "purchaseCost": 3353.44,
    "revenue": 5271.08
  },
  {
    "date": "2026-03-05",
    "purchaseCost": 6193.35,
    "revenue": 9550.43
  },
  {
    "date": "2026-03-06",
    "purchaseCost": 6359.03,
    "revenue": 10142.99
  },
  {
    "date": "2026-03-09",
    "purchaseCost": 2742.83,
    "revenue": 4433.88
  },
  {
    "date": "2026-03-11",
    "purchaseCost": 6899.93,
    "revenue": 11071.09
  },
  {
    "date": "2026-03-13",
    "purchaseCost": 5452.47,
    "revenue": 8404.96
  },
  {
    "date": "2026-03-16",
    "purchaseCost": 5396.39,
    "revenue": 7946.29
  },
  {
    "date": "2026-03-17",
    "purchaseCost": 3627.79,
    "revenue": 5826.46
  },
  {
    "date": "2026-03-18",
    "purchaseCost": 1926.04,
    "revenue": 3215.71
  },
  {
    "date": "2026-03-19",
    "purchaseCost": 5172.27,
    "revenue": 7485.13
  },
  {
    "date": "2026-03-20",
    "purchaseCost": 4309.53,
    "revenue": 6857.03
  },
  {
    "date": "2026-03-23",
    "purchaseCost": 3658.65,
    "revenue": 5833.06
  },
  {
    "date": "2026-03-24",
    "purchaseCost": 2029.36,
    "revenue": 2700.41
  },
  {
    "date": "2026-03-25",
    "purchaseCost": 3615.52,
    "revenue": 4776.86
  },
  {
    "date": "2026-03-26",
    "purchaseCost": 5818.64,
    "revenue": 9238.84
  },
  {
    "date": "2026-03-27",
    "purchaseCost": 2382.59,
    "revenue": 3722.32
  },
  {
    "date": "2026-03-30",
    "purchaseCost": 2664.24,
    "revenue": 4708.18
  },
  {
    "date": "2026-03-31",
    "purchaseCost": 1916.5,
    "revenue": 2968.6
  },
  {
    "date": "2026-04-07",
    "purchaseCost": 3192.31,
    "revenue": 4586.78
  },
  {
    "date": "2026-04-08",
    "purchaseCost": 3501.53,
    "revenue": 6165.3
  },
  {
    "date": "2026-04-10",
    "purchaseCost": 3435.26,
    "revenue": 5025.62
  },
  {
    "date": "2026-04-14",
    "purchaseCost": 4766.04,
    "revenue": 7705.8
  },
  {
    "date": "2026-04-15",
    "purchaseCost": 2664.58,
    "revenue": 4729.76
  },
  {
    "date": "2026-04-16",
    "purchaseCost": 1783.03,
    "revenue": 3034.71
  },
  {
    "date": "2026-04-17",
    "purchaseCost": 3095.24,
    "revenue": 4671.08
  },
  {
    "date": "2026-04-18",
    "purchaseCost": 1309.53,
    "revenue": 2075.21
  },
  {
    "date": "2026-04-20",
    "purchaseCost": 2368.39,
    "revenue": 5041.33
  },
  {
    "date": "2026-04-22",
    "purchaseCost": 5214.42,
    "revenue": 8735.54
  },
  {
    "date": "2026-04-23",
    "purchaseCost": 2578.14,
    "revenue": 3744.63
  },
  {
    "date": "2026-04-24",
    "purchaseCost": 958.25,
    "revenue": 1484.3
  },
  {
    "date": "2026-04-29",
    "purchaseCost": 2889.14,
    "revenue": 4351.24
  },
  {
    "date": "2026-04-30",
    "purchaseCost": 4542.29,
    "revenue": 7077.7
  },
  {
    "date": "2026-05-05",
    "purchaseCost": 2252.86,
    "revenue": 3338.02
  },
  {
    "date": "2026-05-06",
    "purchaseCost": 3344.51,
    "revenue": 6009.1
  },
  {
    "date": "2026-05-07",
    "purchaseCost": 3154.77,
    "revenue": 4589.26
  },
  {
    "date": "2026-05-09",
    "purchaseCost": 875,
    "revenue": 1479.34
  },
  {
    "date": "2026-05-12",
    "purchaseCost": 4746.64,
    "revenue": 7161.17
  },
  {
    "date": "2026-05-13",
    "purchaseCost": 1910.65,
    "revenue": 3010.75
  },
  {
    "date": "2026-05-14",
    "purchaseCost": 2922.34,
    "revenue": 4372.73
  },
  {
    "date": "2026-05-15",
    "purchaseCost": 855.81,
    "revenue": 1843.81
  },
  {
    "date": "2026-05-18",
    "purchaseCost": 1547.62,
    "revenue": 2039.67
  },
  {
    "date": "2026-05-19",
    "purchaseCost": 4265.27,
    "revenue": 6211.58
  },
  {
    "date": "2026-05-20",
    "purchaseCost": 8041.21,
    "revenue": 12346.34
  },
  {
    "date": "2026-05-21",
    "purchaseCost": 2763.64,
    "revenue": 4894.22
  },
  {
    "date": "2026-05-22",
    "purchaseCost": 3850.28,
    "revenue": 6424.79
  },
  {
    "date": "2026-05-26",
    "purchaseCost": 5335.33,
    "revenue": 7763.63
  },
  {
    "date": "2026-05-27",
    "purchaseCost": 9909.89,
    "revenue": 13735.06
  },
  {
    "date": "2026-05-29",
    "purchaseCost": 5035.73,
    "revenue": 7394.3
  },
  {
    "date": "2026-06-01",
    "purchaseCost": 2721.67,
    "revenue": 4194.21
  },
  {
    "date": "2026-06-02",
    "purchaseCost": 4036.04,
    "revenue": 6458.03
  },
  {
    "date": "2026-06-03",
    "purchaseCost": 1958.84,
    "revenue": 2293.39
  },
  {
    "date": "2026-06-04",
    "purchaseCost": 4966.8,
    "revenue": 6917.84
  },
  {
    "date": "2026-06-05",
    "purchaseCost": 6179.25,
    "revenue": 10458.7
  },
  {
    "date": "2026-06-09",
    "purchaseCost": 2042,
    "revenue": 3978.52
  },
  {
    "date": "2026-06-10",
    "purchaseCost": 3360.63,
    "revenue": 6021.5
  },
  {
    "date": "2026-06-11",
    "purchaseCost": 2764.58,
    "revenue": 5488.44
  },
  {
    "date": "2026-06-12",
    "purchaseCost": 958.26,
    "revenue": 1562.81
  },
  {
    "date": "2026-06-15",
    "purchaseCost": 7669.22,
    "revenue": 11764.47
  },
  {
    "date": "2026-06-16",
    "purchaseCost": 1895.01,
    "revenue": 2471.91
  },
  {
    "date": "2026-06-17",
    "purchaseCost": 2023.81,
    "revenue": 3378.52
  },
  {
    "date": "2026-06-18",
    "purchaseCost": 3197.24,
    "revenue": 4743.81
  },
  {
    "date": "2026-06-19",
    "purchaseCost": 11405.91,
    "revenue": 19633.07
  },
  {
    "date": "2026-06-23",
    "purchaseCost": 5222.51,
    "revenue": 8185.14
  },
  {
    "date": "2026-06-24",
    "purchaseCost": 1650.76,
    "revenue": 3264.47
  },
  {
    "date": "2026-06-25",
    "purchaseCost": 956.2,
    "revenue": 1479.34
  },
  {
    "date": "2026-06-26",
    "purchaseCost": 1619.26,
    "revenue": 2594.22
  },
  {
    "date": "2026-07-01",
    "purchaseCost": 904.96,
    "revenue": 1377.36
  },
  {
    "date": "2026-07-02",
    "purchaseCost": 1904.76,
    "revenue": 2744.63
  },
  {
    "date": "2026-07-03",
    "purchaseCost": 3333.34,
    "revenue": 4982.41
  },
  {
    "date": "2026-07-07",
    "purchaseCost": 958.25,
    "revenue": 1484.3
  },
  {
    "date": "2026-07-15",
    "purchaseCost": 904.96,
    "revenue": 1518.36
  },
  {
    "date": "2026-07-16",
    "purchaseCost": 1309.53,
    "revenue": 1798.35
  },
  {
    "date": "2026-07-17",
    "purchaseCost": 2567,
    "revenue": 2381
  },
  {
    "date": "2026-07-20",
    "purchaseCost": 958.25,
    "revenue": -1234.71
  },
  {
    "date": "2026-07-21",
    "purchaseCost": 1547.62,
    "revenue": 2447.11
  },
  {
    "date": "2026-07-22",
    "purchaseCost": 1190.48,
    "revenue": 1757.85
  },
  {
    "date": "2026-07-28",
    "purchaseCost": 4413.43,
    "revenue": 6439.99
  },
  {
    "date": "2026-07-29",
    "purchaseCost": 745.8,
    "revenue": 1147.93
  },
  {
    "date": "2026-07-30",
    "purchaseCost": 567,
    "revenue": 788.5
  },
  {
    "date": "2026-07-31",
    "purchaseCost": 5221.26,
    "revenue": 7901.65
  },
  {
    "date": "2026-08-04",
    "purchaseCost": 2857.14,
    "revenue": 3702.72
  },
  {
    "date": "2026-08-06",
    "purchaseCost": 1785.72,
    "revenue": 2670.25
  }
];
