// Auto-generated by scripts/updateData.js — last update: 2026-04-24
// CZ: daily margin data (CZK). purchaseCost = nákupní cena (buy_price × quantity), revenue = tržby bez DPH.

export interface MarginDailyRecord {
  date: string;
  purchaseCost: number;
  revenue: number;
}

export const prodejnaMarginDataCZ: MarginDailyRecord[] = [
  {
    "date": "2025-04-03",
    "purchaseCost": 1008,
    "revenue": 1528.1
  },
  {
    "date": "2025-04-07",
    "purchaseCost": 1713.36,
    "revenue": 2065.29
  },
  {
    "date": "2025-04-09",
    "purchaseCost": 1713.36,
    "revenue": 2230.58
  },
  {
    "date": "2025-04-10",
    "purchaseCost": 4299.04,
    "revenue": 5328.93
  },
  {
    "date": "2025-04-11",
    "purchaseCost": 1713.36,
    "revenue": 1941.32
  },
  {
    "date": "2025-04-15",
    "purchaseCost": 1210,
    "revenue": 3098.35
  },
  {
    "date": "2025-04-16",
    "purchaseCost": 2017,
    "revenue": 3098.35
  },
  {
    "date": "2025-04-17",
    "purchaseCost": 2470.55,
    "revenue": 4212.4
  },
  {
    "date": "2025-04-24",
    "purchaseCost": 834,
    "revenue": 1032.23
  },
  {
    "date": "2025-04-25",
    "purchaseCost": 4663.08,
    "revenue": 5965.29
  },
  {
    "date": "2025-04-26",
    "purchaseCost": 314.6,
    "revenue": 380.17
  },
  {
    "date": "2025-04-27",
    "purchaseCost": 1383,
    "revenue": 1809.92
  },
  {
    "date": "2025-04-28",
    "purchaseCost": 1595,
    "revenue": 2023.97
  },
  {
    "date": "2025-04-30",
    "purchaseCost": 4538.36,
    "revenue": 7063.64
  },
  {
    "date": "2025-05-02",
    "purchaseCost": 2305,
    "revenue": 3304.96
  },
  {
    "date": "2025-05-06",
    "purchaseCost": 1499.19,
    "revenue": 1734.71
  },
  {
    "date": "2025-05-07",
    "purchaseCost": 1713.36,
    "revenue": 2230.58
  },
  {
    "date": "2025-05-09",
    "purchaseCost": 4915.36,
    "revenue": 6733.06
  },
  {
    "date": "2025-05-12",
    "purchaseCost": 980,
    "revenue": 2023.97
  },
  {
    "date": "2025-05-15",
    "purchaseCost": 4753.28,
    "revenue": 7311.58
  },
  {
    "date": "2025-05-19",
    "purchaseCost": 0,
    "revenue": 2230.58
  },
  {
    "date": "2025-05-21",
    "purchaseCost": 4416.42,
    "revenue": 9244.64
  },
  {
    "date": "2025-05-23",
    "purchaseCost": 1123.6,
    "revenue": 2023.97
  },
  {
    "date": "2025-05-27",
    "purchaseCost": 1606.28,
    "revenue": 2354.55
  },
  {
    "date": "2025-05-28",
    "purchaseCost": 2982.6,
    "revenue": 3371.9
  },
  {
    "date": "2025-06-02",
    "purchaseCost": 238.62,
    "revenue": 426.44
  },
  {
    "date": "2025-06-03",
    "purchaseCost": 1584.5,
    "revenue": 2437.19
  },
  {
    "date": "2025-06-04",
    "purchaseCost": 2506.5,
    "revenue": 4378.51
  },
  {
    "date": "2025-06-05",
    "purchaseCost": 1294.46,
    "revenue": 2335.54
  },
  {
    "date": "2025-06-06",
    "purchaseCost": 605,
    "revenue": 900.83
  },
  {
    "date": "2025-06-09",
    "purchaseCost": 1606.28,
    "revenue": 2354.55
  },
  {
    "date": "2025-06-10",
    "purchaseCost": 3939.88,
    "revenue": 7476.87
  },
  {
    "date": "2025-06-13",
    "purchaseCost": 2865.76,
    "revenue": 4089.26
  },
  {
    "date": "2025-06-17",
    "purchaseCost": 871,
    "revenue": 1032.23
  },
  {
    "date": "2025-06-18",
    "purchaseCost": 3601.2,
    "revenue": 4990.91
  },
  {
    "date": "2025-06-24",
    "purchaseCost": 871,
    "revenue": 892.56
  },
  {
    "date": "2025-06-30",
    "purchaseCost": 1296.4,
    "revenue": 1941.32
  },
  {
    "date": "2025-07-01",
    "purchaseCost": 3487.11,
    "revenue": 5114.05
  },
  {
    "date": "2025-07-02",
    "purchaseCost": 2998.38,
    "revenue": 4047.94
  },
  {
    "date": "2025-07-03",
    "purchaseCost": 6070.9,
    "revenue": 8054.55
  },
  {
    "date": "2025-07-04",
    "purchaseCost": 1499.19,
    "revenue": 2023.97
  },
  {
    "date": "2025-07-08",
    "purchaseCost": 871,
    "revenue": 892.56
  },
  {
    "date": "2025-07-09",
    "purchaseCost": 3399.43,
    "revenue": 5107.44
  },
  {
    "date": "2025-07-11",
    "purchaseCost": 7232.29,
    "revenue": 10525.62
  },
  {
    "date": "2025-07-14",
    "purchaseCost": 1152.4,
    "revenue": 1858.68
  },
  {
    "date": "2025-07-15",
    "purchaseCost": 4147.1,
    "revenue": 5635.53
  },
  {
    "date": "2025-07-16",
    "purchaseCost": 6375.16,
    "revenue": 9820.66
  },
  {
    "date": "2025-07-18",
    "purchaseCost": 4356.9,
    "revenue": 5668.6
  },
  {
    "date": "2025-07-21",
    "purchaseCost": 3454.42,
    "revenue": 4857.03
  },
  {
    "date": "2025-07-22",
    "purchaseCost": 2535.5,
    "revenue": 3676.04
  },
  {
    "date": "2025-07-23",
    "purchaseCost": 5085.15,
    "revenue": 6948.77
  },
  {
    "date": "2025-07-24",
    "purchaseCost": 2865.76,
    "revenue": 3676.03
  },
  {
    "date": "2025-07-25",
    "purchaseCost": 2821.73,
    "revenue": 3603.31
  },
  {
    "date": "2025-07-29",
    "purchaseCost": 871,
    "revenue": 892.56
  },
  {
    "date": "2025-08-05",
    "purchaseCost": 3543.9,
    "revenue": 5106.61
  },
  {
    "date": "2025-08-06",
    "purchaseCost": 871,
    "revenue": 892.56
  },
  {
    "date": "2025-08-07",
    "purchaseCost": 2160.7,
    "revenue": 2884.3
  },
  {
    "date": "2025-08-08",
    "purchaseCost": 620.24,
    "revenue": 1485.12
  },
  {
    "date": "2025-08-11",
    "purchaseCost": 3774,
    "revenue": 5486.78
  },
  {
    "date": "2025-08-12",
    "purchaseCost": 864.2,
    "revenue": 1231.4
  },
  {
    "date": "2025-08-13",
    "purchaseCost": 4062.4,
    "revenue": 5677.68
  },
  {
    "date": "2025-08-14",
    "purchaseCost": 5026.46,
    "revenue": 7000
  },
  {
    "date": "2025-08-15",
    "purchaseCost": 605,
    "revenue": 900.83
  },
  {
    "date": "2025-08-18",
    "purchaseCost": 2729.19,
    "revenue": 3965.29
  },
  {
    "date": "2025-08-19",
    "purchaseCost": 5244.39,
    "revenue": 7345.46
  },
  {
    "date": "2025-08-20",
    "purchaseCost": 5370.46,
    "revenue": 7081.82
  },
  {
    "date": "2025-08-21",
    "purchaseCost": 792.2,
    "revenue": 1131.4
  },
  {
    "date": "2025-08-22",
    "purchaseCost": 2621.36,
    "revenue": 3785.12
  },
  {
    "date": "2025-08-25",
    "purchaseCost": 3149.03,
    "revenue": 4452.9
  },
  {
    "date": "2025-08-26",
    "purchaseCost": 2765.7,
    "revenue": 3537.19
  },
  {
    "date": "2025-08-28",
    "purchaseCost": 2852.2,
    "revenue": 3923.96
  },
  {
    "date": "2025-08-29",
    "purchaseCost": 1728.6,
    "revenue": 2816.53
  },
  {
    "date": "2025-09-01",
    "purchaseCost": 518.49,
    "revenue": 793.39
  },
  {
    "date": "2025-09-03",
    "purchaseCost": 2016.7,
    "revenue": 2685.12
  },
  {
    "date": "2025-09-04",
    "purchaseCost": 1499.19,
    "revenue": 1975.21
  },
  {
    "date": "2025-09-05",
    "purchaseCost": 2651.59,
    "revenue": 3537.19
  },
  {
    "date": "2025-09-08",
    "purchaseCost": 1713.36,
    "revenue": 2223.14
  },
  {
    "date": "2025-09-10",
    "purchaseCost": 5660,
    "revenue": 8358.68
  },
  {
    "date": "2025-09-11",
    "purchaseCost": 605,
    "revenue": 875.21
  },
  {
    "date": "2025-09-12",
    "purchaseCost": 792.26,
    "revenue": 1131.4
  },
  {
    "date": "2025-09-16",
    "purchaseCost": 2016.67,
    "revenue": 2801.65
  },
  {
    "date": "2025-09-17",
    "purchaseCost": 1584.52,
    "revenue": 1975.21
  },
  {
    "date": "2025-09-18",
    "purchaseCost": 2644.52,
    "revenue": 5024.8
  },
  {
    "date": "2025-09-19",
    "purchaseCost": 1584.52,
    "revenue": 1892.56
  },
  {
    "date": "2025-09-23",
    "purchaseCost": 1411.67,
    "revenue": 1727.27
  },
  {
    "date": "2025-09-25",
    "purchaseCost": 3112.42,
    "revenue": 4998.34
  },
  {
    "date": "2025-09-26",
    "purchaseCost": 1109.17,
    "revenue": 1396.69
  },
  {
    "date": "2025-10-01",
    "purchaseCost": 745.8,
    "revenue": 1628.93
  },
  {
    "date": "2025-10-02",
    "purchaseCost": 2148.56,
    "revenue": 3007.44
  },
  {
    "date": "2025-10-03",
    "purchaseCost": 1838.68,
    "revenue": 2776.03
  },
  {
    "date": "2025-10-08",
    "purchaseCost": 1584.52,
    "revenue": 2223.14
  },
  {
    "date": "2025-10-09",
    "purchaseCost": 2274.2,
    "revenue": 3545.45
  },
  {
    "date": "2025-10-13",
    "purchaseCost": 3434.94,
    "revenue": 5082.65
  },
  {
    "date": "2025-10-14",
    "purchaseCost": 1512.5,
    "revenue": 2565.29
  },
  {
    "date": "2025-10-15",
    "purchaseCost": 1588.1,
    "revenue": 1608.26
  },
  {
    "date": "2025-10-16",
    "purchaseCost": 4644.94,
    "revenue": 6613.23
  },
  {
    "date": "2025-10-17",
    "purchaseCost": 7330.97,
    "revenue": 10674.39
  },
  {
    "date": "2025-10-21",
    "purchaseCost": 1728.57,
    "revenue": 2471.07
  },
  {
    "date": "2025-10-22",
    "purchaseCost": 1711.5,
    "revenue": 2803.31
  },
  {
    "date": "2025-10-23",
    "purchaseCost": 1109.17,
    "revenue": 1561.98
  },
  {
    "date": "2025-10-29",
    "purchaseCost": 3889.32,
    "revenue": 5438.02
  },
  {
    "date": "2025-10-31",
    "purchaseCost": 1060,
    "revenue": 2719.01
  },
  {
    "date": "2025-11-03",
    "purchaseCost": 1815,
    "revenue": 2851.24
  },
  {
    "date": "2025-11-04",
    "purchaseCost": 3361.52,
    "revenue": 4486.78
  },
  {
    "date": "2025-11-07",
    "purchaseCost": 3194.61,
    "revenue": 4040.5
  },
  {
    "date": "2025-11-10",
    "purchaseCost": 2139.6,
    "revenue": 3297.52
  },
  {
    "date": "2025-11-11",
    "purchaseCost": 3904.6,
    "revenue": 4909.09
  },
  {
    "date": "2025-11-12",
    "purchaseCost": 7165.22,
    "revenue": 8976.04
  },
  {
    "date": "2025-11-13",
    "purchaseCost": 2675.6,
    "revenue": 2305.79
  },
  {
    "date": "2025-11-14",
    "purchaseCost": 4490.6,
    "revenue": 4405.79
  },
  {
    "date": "2025-11-16",
    "purchaseCost": 1613.33,
    "revenue": 2388.43
  },
  {
    "date": "2025-11-21",
    "purchaseCost": 3407,
    "revenue": 5272.73
  },
  {
    "date": "2025-11-26",
    "purchaseCost": 2274.2,
    "revenue": 2471.07
  },
  {
    "date": "2025-11-28",
    "purchaseCost": 123.42,
    "revenue": 140.5
  },
  {
    "date": "2025-12-05",
    "purchaseCost": 3350.09,
    "revenue": 5098.35
  },
  {
    "date": "2025-12-09",
    "purchaseCost": 1592,
    "revenue": 3545.45
  },
  {
    "date": "2025-12-11",
    "purchaseCost": 532.4,
    "revenue": 955.37
  },
  {
    "date": "2025-12-12",
    "purchaseCost": 1711.5,
    "revenue": 3132.23
  },
  {
    "date": "2025-12-17",
    "purchaseCost": 1584.52,
    "revenue": 2057.85
  },
  {
    "date": "2025-12-18",
    "purchaseCost": 20,
    "revenue": 1652.89
  },
  {
    "date": "2026-01-05",
    "purchaseCost": 2397.62,
    "revenue": 3701.65
  },
  {
    "date": "2026-01-09",
    "purchaseCost": 193.6,
    "revenue": 239.67
  },
  {
    "date": "2026-01-14",
    "purchaseCost": 1384.59,
    "revenue": 2040.49
  },
  {
    "date": "2026-01-16",
    "purchaseCost": 2592.86,
    "revenue": 2731.4
  },
  {
    "date": "2026-01-19",
    "purchaseCost": 2406.4,
    "revenue": 2884.3
  },
  {
    "date": "2026-01-21",
    "purchaseCost": 871,
    "revenue": 1032.23
  },
  {
    "date": "2026-01-23",
    "purchaseCost": 4491.91,
    "revenue": 6658.68
  },
  {
    "date": "2026-01-28",
    "purchaseCost": 1109.17,
    "revenue": 1644.63
  },
  {
    "date": "2026-01-30",
    "purchaseCost": 7904.85,
    "revenue": 11423.97
  },
  {
    "date": "2026-01-31",
    "purchaseCost": 1159.99,
    "revenue": 1660.33
  },
  {
    "date": "2026-02-04",
    "purchaseCost": 2448.81,
    "revenue": 2967.77
  },
  {
    "date": "2026-02-12",
    "purchaseCost": 1728.57,
    "revenue": 1892.56
  },
  {
    "date": "2026-02-17",
    "purchaseCost": 1613.33,
    "revenue": 2388.43
  },
  {
    "date": "2026-02-19",
    "purchaseCost": 871,
    "revenue": 1032.23
  },
  {
    "date": "2026-02-25",
    "purchaseCost": 1872.62,
    "revenue": 2447.11
  },
  {
    "date": "2026-02-27",
    "purchaseCost": 6435.93,
    "revenue": 8069.44
  },
  {
    "date": "2026-03-04",
    "purchaseCost": 4057.66,
    "revenue": 5271.08
  },
  {
    "date": "2026-03-05",
    "purchaseCost": 7493.94,
    "revenue": 9550.43
  },
  {
    "date": "2026-03-06",
    "purchaseCost": 7694.41,
    "revenue": 10142.99
  },
  {
    "date": "2026-03-09",
    "purchaseCost": 3318.82,
    "revenue": 4433.88
  },
  {
    "date": "2026-03-11",
    "purchaseCost": 8348.9,
    "revenue": 11071.09
  },
  {
    "date": "2026-03-13",
    "purchaseCost": 4580.82,
    "revenue": 5883.47
  },
  {
    "date": "2026-03-16",
    "purchaseCost": 6529.63,
    "revenue": 7946.29
  },
  {
    "date": "2026-03-17",
    "purchaseCost": 4389.61,
    "revenue": 5826.46
  },
  {
    "date": "2026-03-18",
    "purchaseCost": 2330.5,
    "revenue": 3215.71
  },
  {
    "date": "2026-03-19",
    "purchaseCost": 6258.45,
    "revenue": 7485.13
  },
  {
    "date": "2026-03-20",
    "purchaseCost": 5214.52,
    "revenue": 6857.03
  },
  {
    "date": "2026-03-23",
    "purchaseCost": 4426.97,
    "revenue": 5833.06
  },
  {
    "date": "2026-03-24",
    "purchaseCost": 2455.52,
    "revenue": 2700.41
  },
  {
    "date": "2026-03-25",
    "purchaseCost": 4374.78,
    "revenue": 4776.86
  },
  {
    "date": "2026-03-26",
    "purchaseCost": 7040.56,
    "revenue": 9238.84
  },
  {
    "date": "2026-03-27",
    "purchaseCost": 2882.92,
    "revenue": 3722.32
  },
  {
    "date": "2026-03-30",
    "purchaseCost": 3223.73,
    "revenue": 4708.18
  },
  {
    "date": "2026-03-31",
    "purchaseCost": 2318.96,
    "revenue": 2968.6
  },
  {
    "date": "2026-04-07",
    "purchaseCost": 3862.69,
    "revenue": 4586.78
  },
  {
    "date": "2026-04-08",
    "purchaseCost": 2904.3,
    "revenue": 4529.76
  },
  {
    "date": "2026-04-10",
    "purchaseCost": 4156.67,
    "revenue": 5025.62
  },
  {
    "date": "2026-04-13",
    "purchaseCost": 1584.52,
    "revenue": 2305.79
  },
  {
    "date": "2026-04-14",
    "purchaseCost": 5766.89,
    "revenue": 7705.8
  },
  {
    "date": "2026-04-15",
    "purchaseCost": 3224.13,
    "revenue": 4729.76
  },
  {
    "date": "2026-04-16",
    "purchaseCost": 2157.47,
    "revenue": 3034.71
  },
  {
    "date": "2026-04-17",
    "purchaseCost": 3745.24,
    "revenue": 4671.08
  },
  {
    "date": "2026-04-18",
    "purchaseCost": 1584.52,
    "revenue": 2075.21
  },
  {
    "date": "2026-04-20",
    "purchaseCost": 6338.65,
    "revenue": 10549.52
  },
  {
    "date": "2026-04-22",
    "purchaseCost": 6309.44,
    "revenue": 8735.54
  },
  {
    "date": "2026-04-23",
    "purchaseCost": 3119.55,
    "revenue": 3744.63
  }
];
