// Auto-generated by scripts/updateData.js — last update: 2026-08-05
// CZ: prodejna orders (status 19 + 21) in CZK

export interface ProdejnaRecord {
  date: string;
  orders: number;
  revenue_vat: number;
  revenue: number;
}

export const prodejnaDataCZ: ProdejnaRecord[] = [
  {
    "date": "2025-04-03",
    "orders": 1,
    "revenue_vat": 1849,
    "revenue": 1528.1
  },
  {
    "date": "2025-04-07",
    "orders": 1,
    "revenue_vat": 2499,
    "revenue": 2065.29
  },
  {
    "date": "2025-04-09",
    "orders": 1,
    "revenue_vat": 2699,
    "revenue": 2230.58
  },
  {
    "date": "2025-04-10",
    "orders": 2,
    "revenue_vat": 6448,
    "revenue": 5328.93
  },
  {
    "date": "2025-04-11",
    "orders": 1,
    "revenue_vat": 2349,
    "revenue": 1941.32
  },
  {
    "date": "2025-04-15",
    "orders": 1,
    "revenue_vat": 3749,
    "revenue": 3098.35
  },
  {
    "date": "2025-04-16",
    "orders": 1,
    "revenue_vat": 3749,
    "revenue": 3098.35
  },
  {
    "date": "2025-04-17",
    "orders": 2,
    "revenue_vat": 5097,
    "revenue": 4212.4
  },
  {
    "date": "2025-04-24",
    "orders": 1,
    "revenue_vat": 1249,
    "revenue": 1032.23
  },
  {
    "date": "2025-04-25",
    "orders": 2,
    "revenue_vat": 7218,
    "revenue": 5965.29
  },
  {
    "date": "2025-04-26",
    "orders": 1,
    "revenue_vat": 460,
    "revenue": 380.17
  },
  {
    "date": "2025-04-27",
    "orders": 1,
    "revenue_vat": 2190,
    "revenue": 1809.92
  },
  {
    "date": "2025-04-28",
    "orders": 1,
    "revenue_vat": 2449,
    "revenue": 2023.97
  },
  {
    "date": "2025-04-30",
    "orders": 3,
    "revenue_vat": 8547,
    "revenue": 7063.64
  },
  {
    "date": "2025-05-02",
    "orders": 1,
    "revenue_vat": 3999,
    "revenue": 3304.96
  },
  {
    "date": "2025-05-06",
    "orders": 1,
    "revenue_vat": 2099,
    "revenue": 1734.71
  },
  {
    "date": "2025-05-07",
    "orders": 1,
    "revenue_vat": 2699,
    "revenue": 2230.58
  },
  {
    "date": "2025-05-09",
    "orders": 2,
    "revenue_vat": 8147,
    "revenue": 6733.06
  },
  {
    "date": "2025-05-12",
    "orders": 1,
    "revenue_vat": 2449,
    "revenue": 2023.97
  },
  {
    "date": "2025-05-15",
    "orders": 2,
    "revenue_vat": 8847,
    "revenue": 7311.58
  },
  {
    "date": "2025-05-19",
    "orders": 1,
    "revenue_vat": 2699,
    "revenue": 2230.58
  },
  {
    "date": "2025-05-21",
    "orders": 3,
    "revenue_vat": 11186,
    "revenue": 9244.64
  },
  {
    "date": "2025-05-23",
    "orders": 1,
    "revenue_vat": 2449,
    "revenue": 2023.97
  },
  {
    "date": "2025-05-27",
    "orders": 1,
    "revenue_vat": 2849,
    "revenue": 2354.55
  },
  {
    "date": "2025-05-28",
    "orders": 2,
    "revenue_vat": 4080,
    "revenue": 3371.9
  },
  {
    "date": "2025-06-02",
    "orders": 1,
    "revenue_vat": 516,
    "revenue": 426.44
  },
  {
    "date": "2025-06-03",
    "orders": 1,
    "revenue_vat": 2949,
    "revenue": 2437.19
  },
  {
    "date": "2025-06-04",
    "orders": 2,
    "revenue_vat": 5298,
    "revenue": 4378.51
  },
  {
    "date": "2025-06-05",
    "orders": 1,
    "revenue_vat": 2826,
    "revenue": 2335.54
  },
  {
    "date": "2025-06-06",
    "orders": 1,
    "revenue_vat": 1090,
    "revenue": 900.83
  },
  {
    "date": "2025-06-09",
    "orders": 1,
    "revenue_vat": 2849,
    "revenue": 2354.55
  },
  {
    "date": "2025-06-10",
    "orders": 3,
    "revenue_vat": 9047,
    "revenue": 7476.87
  },
  {
    "date": "2025-06-13",
    "orders": 2,
    "revenue_vat": 4948,
    "revenue": 4089.26
  },
  {
    "date": "2025-06-17",
    "orders": 1,
    "revenue_vat": 1249,
    "revenue": 1032.23
  },
  {
    "date": "2025-06-18",
    "orders": 2,
    "revenue_vat": 6039,
    "revenue": 4990.91
  },
  {
    "date": "2025-06-24",
    "orders": 1,
    "revenue_vat": 1080,
    "revenue": 892.56
  },
  {
    "date": "2025-06-30",
    "orders": 1,
    "revenue_vat": 2349,
    "revenue": 1941.32
  },
  {
    "date": "2025-07-01",
    "orders": 2,
    "revenue_vat": 6188,
    "revenue": 5114.05
  },
  {
    "date": "2025-07-02",
    "orders": 2,
    "revenue_vat": 4898,
    "revenue": 4047.94
  },
  {
    "date": "2025-07-03",
    "orders": 3,
    "revenue_vat": 9746,
    "revenue": 8054.55
  },
  {
    "date": "2025-07-04",
    "orders": 1,
    "revenue_vat": 2449,
    "revenue": 2023.97
  },
  {
    "date": "2025-07-08",
    "orders": 1,
    "revenue_vat": 1080,
    "revenue": 892.56
  },
  {
    "date": "2025-07-09",
    "orders": 2,
    "revenue_vat": 6180,
    "revenue": 5107.44
  },
  {
    "date": "2025-07-11",
    "orders": 5,
    "revenue_vat": 12736,
    "revenue": 10525.62
  },
  {
    "date": "2025-07-14",
    "orders": 1,
    "revenue_vat": 2249,
    "revenue": 1858.68
  },
  {
    "date": "2025-07-15",
    "orders": 3,
    "revenue_vat": 6819,
    "revenue": 5635.53
  },
  {
    "date": "2025-07-16",
    "orders": 6,
    "revenue_vat": 11883,
    "revenue": 9820.66
  },
  {
    "date": "2025-07-18",
    "orders": 4,
    "revenue_vat": 6859,
    "revenue": 5668.6
  },
  {
    "date": "2025-07-21",
    "orders": 4,
    "revenue_vat": 5877,
    "revenue": 4857.03
  },
  {
    "date": "2025-07-22",
    "orders": 2,
    "revenue_vat": 4448,
    "revenue": 3676.04
  },
  {
    "date": "2025-07-23",
    "orders": 1,
    "revenue_vat": 8408,
    "revenue": 6948.77
  },
  {
    "date": "2025-07-24",
    "orders": 2,
    "revenue_vat": 4448,
    "revenue": 3676.03
  },
  {
    "date": "2025-07-25",
    "orders": 2,
    "revenue_vat": 2170,
    "revenue": 1793.39
  },
  {
    "date": "2025-07-29",
    "orders": 1,
    "revenue_vat": 1080,
    "revenue": 892.56
  },
  {
    "date": "2025-08-05",
    "orders": 3,
    "revenue_vat": 6179,
    "revenue": 5106.61
  },
  {
    "date": "2025-08-06",
    "orders": 1,
    "revenue_vat": 1080,
    "revenue": 892.56
  },
  {
    "date": "2025-08-07",
    "orders": 1,
    "revenue_vat": 3490,
    "revenue": 2884.3
  },
  {
    "date": "2025-08-08",
    "orders": 1,
    "revenue_vat": 1797,
    "revenue": 1485.12
  },
  {
    "date": "2025-08-11",
    "orders": 2,
    "revenue_vat": 6639,
    "revenue": 5486.78
  },
  {
    "date": "2025-08-12",
    "orders": 1,
    "revenue_vat": 1490,
    "revenue": 1231.4
  },
  {
    "date": "2025-08-13",
    "orders": 3,
    "revenue_vat": 6870,
    "revenue": 5677.68
  },
  {
    "date": "2025-08-14",
    "orders": 3,
    "revenue_vat": 8470,
    "revenue": 7000
  },
  {
    "date": "2025-08-15",
    "orders": 1,
    "revenue_vat": 1090,
    "revenue": 900.83
  },
  {
    "date": "2025-08-18",
    "orders": 2,
    "revenue_vat": 4798,
    "revenue": 3965.29
  },
  {
    "date": "2025-08-19",
    "orders": 2,
    "revenue_vat": 8888,
    "revenue": 7345.46
  },
  {
    "date": "2025-08-20",
    "orders": 4,
    "revenue_vat": 8569,
    "revenue": 7081.82
  },
  {
    "date": "2025-08-21",
    "orders": 1,
    "revenue_vat": 1369,
    "revenue": 1131.4
  },
  {
    "date": "2025-08-22",
    "orders": 2,
    "revenue_vat": 4580,
    "revenue": 3785.12
  },
  {
    "date": "2025-08-25",
    "orders": 2,
    "revenue_vat": 5388,
    "revenue": 4452.9
  },
  {
    "date": "2025-08-26",
    "orders": 2,
    "revenue_vat": 4280,
    "revenue": 3537.19
  },
  {
    "date": "2025-08-28",
    "orders": 2,
    "revenue_vat": 4748,
    "revenue": 3923.96
  },
  {
    "date": "2025-08-29",
    "orders": 1,
    "revenue_vat": 3408,
    "revenue": 2816.53
  },
  {
    "date": "2025-09-01",
    "orders": 1,
    "revenue_vat": 960,
    "revenue": 793.39
  },
  {
    "date": "2025-09-03",
    "orders": 1,
    "revenue_vat": 3249,
    "revenue": 2685.12
  },
  {
    "date": "2025-09-04",
    "orders": 1,
    "revenue_vat": 2390,
    "revenue": 1975.21
  },
  {
    "date": "2025-09-05",
    "orders": 2,
    "revenue_vat": 4280,
    "revenue": 3537.19
  },
  {
    "date": "2025-09-08",
    "orders": 1,
    "revenue_vat": 2690,
    "revenue": 2223.14
  },
  {
    "date": "2025-09-10",
    "orders": 4,
    "revenue_vat": 10114,
    "revenue": 8358.68
  },
  {
    "date": "2025-09-11",
    "orders": 1,
    "revenue_vat": 1059,
    "revenue": 875.21
  },
  {
    "date": "2025-09-12",
    "orders": 1,
    "revenue_vat": 1369,
    "revenue": 1131.4
  },
  {
    "date": "2025-09-16",
    "orders": 1,
    "revenue_vat": 3390,
    "revenue": 2801.65
  },
  {
    "date": "2025-09-17",
    "orders": 1,
    "revenue_vat": 2390,
    "revenue": 1975.21
  },
  {
    "date": "2025-09-18",
    "orders": 2,
    "revenue_vat": 6080,
    "revenue": 5024.8
  },
  {
    "date": "2025-09-19",
    "orders": 1,
    "revenue_vat": 2290,
    "revenue": 1892.56
  },
  {
    "date": "2025-09-23",
    "orders": 1,
    "revenue_vat": 2090,
    "revenue": 1727.27
  },
  {
    "date": "2025-09-25",
    "orders": 2,
    "revenue_vat": 6048,
    "revenue": 4998.34
  },
  {
    "date": "2025-09-26",
    "orders": 1,
    "revenue_vat": 1690,
    "revenue": 1396.69
  },
  {
    "date": "2025-10-01",
    "orders": 1,
    "revenue_vat": 1971,
    "revenue": 1628.93
  },
  {
    "date": "2025-10-02",
    "orders": 1,
    "revenue_vat": 3639,
    "revenue": 3007.44
  },
  {
    "date": "2025-10-03",
    "orders": 2,
    "revenue_vat": 3359,
    "revenue": 2776.03
  },
  {
    "date": "2025-10-08",
    "orders": 1,
    "revenue_vat": 2690,
    "revenue": 2223.14
  },
  {
    "date": "2025-10-09",
    "orders": 1,
    "revenue_vat": 4290,
    "revenue": 3545.45
  },
  {
    "date": "2025-10-13",
    "orders": 2,
    "revenue_vat": 6150,
    "revenue": 5082.65
  },
  {
    "date": "2025-10-14",
    "orders": 1,
    "revenue_vat": 3104,
    "revenue": 2565.29
  },
  {
    "date": "2025-10-15",
    "orders": 1,
    "revenue_vat": 1946,
    "revenue": 1608.26
  },
  {
    "date": "2025-10-16",
    "orders": 2,
    "revenue_vat": 8002,
    "revenue": 6613.23
  },
  {
    "date": "2025-10-17",
    "orders": 3,
    "revenue_vat": 12916,
    "revenue": 10674.39
  },
  {
    "date": "2025-10-21",
    "orders": 1,
    "revenue_vat": 2990,
    "revenue": 2471.07
  },
  {
    "date": "2025-10-22",
    "orders": 1,
    "revenue_vat": 3392,
    "revenue": 2803.31
  },
  {
    "date": "2025-10-23",
    "orders": 1,
    "revenue_vat": 1890,
    "revenue": 1561.98
  },
  {
    "date": "2025-10-29",
    "orders": 1,
    "revenue_vat": 6580,
    "revenue": 5438.02
  },
  {
    "date": "2025-10-31",
    "orders": 1,
    "revenue_vat": 3290,
    "revenue": 2719.01
  },
  {
    "date": "2025-11-03",
    "orders": 1,
    "revenue_vat": 3450,
    "revenue": 2851.24
  },
  {
    "date": "2025-11-04",
    "orders": 2,
    "revenue_vat": 5429,
    "revenue": 4486.78
  },
  {
    "date": "2025-11-07",
    "orders": 2,
    "revenue_vat": 4889,
    "revenue": 4040.5
  },
  {
    "date": "2025-11-10",
    "orders": 1,
    "revenue_vat": 3990,
    "revenue": 3297.52
  },
  {
    "date": "2025-11-11",
    "orders": 3,
    "revenue_vat": 5940,
    "revenue": 4909.09
  },
  {
    "date": "2025-11-12",
    "orders": 4,
    "revenue_vat": 10861,
    "revenue": 8976.04
  },
  {
    "date": "2025-11-13",
    "orders": 1,
    "revenue_vat": 2790,
    "revenue": 2305.79
  },
  {
    "date": "2025-11-14",
    "orders": 1,
    "revenue_vat": 5331,
    "revenue": 4405.79
  },
  {
    "date": "2025-11-16",
    "orders": 1,
    "revenue_vat": 2890,
    "revenue": 2388.43
  },
  {
    "date": "2025-11-21",
    "orders": 2,
    "revenue_vat": 6380,
    "revenue": 5272.73
  },
  {
    "date": "2025-11-26",
    "orders": 1,
    "revenue_vat": 2990,
    "revenue": 2471.07
  },
  {
    "date": "2025-11-28",
    "orders": 1,
    "revenue_vat": 170,
    "revenue": 140.5
  },
  {
    "date": "2025-12-05",
    "orders": 1,
    "revenue_vat": 6169,
    "revenue": 5098.35
  },
  {
    "date": "2025-12-09",
    "orders": 1,
    "revenue_vat": 4290,
    "revenue": 3545.45
  },
  {
    "date": "2025-12-11",
    "orders": 1,
    "revenue_vat": 1156,
    "revenue": 955.37
  },
  {
    "date": "2025-12-12",
    "orders": 1,
    "revenue_vat": 3790,
    "revenue": 3132.23
  },
  {
    "date": "2025-12-17",
    "orders": 1,
    "revenue_vat": 2490,
    "revenue": 2057.85
  },
  {
    "date": "2025-12-18",
    "orders": 1,
    "revenue_vat": 2000,
    "revenue": 1652.89
  },
  {
    "date": "2026-01-05",
    "orders": 2,
    "revenue_vat": 4479,
    "revenue": 3701.65
  },
  {
    "date": "2026-01-09",
    "orders": 1,
    "revenue_vat": 290,
    "revenue": 239.67
  },
  {
    "date": "2026-01-14",
    "orders": 3,
    "revenue_vat": 2469,
    "revenue": 2040.49
  },
  {
    "date": "2026-01-16",
    "orders": 1,
    "revenue_vat": 3305,
    "revenue": 2731.4
  },
  {
    "date": "2026-01-19",
    "orders": 1,
    "revenue_vat": 3490,
    "revenue": 2884.3
  },
  {
    "date": "2026-01-21",
    "orders": 1,
    "revenue_vat": 1249,
    "revenue": 1032.23
  },
  {
    "date": "2026-01-23",
    "orders": 2,
    "revenue_vat": 8057,
    "revenue": 6658.68
  },
  {
    "date": "2026-01-28",
    "orders": 1,
    "revenue_vat": 1990,
    "revenue": 1644.63
  },
  {
    "date": "2026-01-30",
    "orders": 5,
    "revenue_vat": 13823,
    "revenue": 11423.97
  },
  {
    "date": "2026-01-31",
    "orders": 1,
    "revenue_vat": 2009,
    "revenue": 1660.33
  },
  {
    "date": "2026-02-04",
    "orders": 1,
    "revenue_vat": 3591,
    "revenue": 2967.77
  },
  {
    "date": "2026-02-12",
    "orders": 1,
    "revenue_vat": 2290,
    "revenue": 1892.56
  },
  {
    "date": "2026-02-17",
    "orders": 1,
    "revenue_vat": 2890,
    "revenue": 2388.43
  },
  {
    "date": "2026-02-19",
    "orders": 1,
    "revenue_vat": 1249,
    "revenue": 1032.23
  },
  {
    "date": "2026-02-25",
    "orders": 1,
    "revenue_vat": 2961,
    "revenue": 2447.11
  },
  {
    "date": "2026-02-27",
    "orders": 3,
    "revenue_vat": 9764,
    "revenue": 8069.44
  },
  {
    "date": "2026-03-04",
    "orders": 2,
    "revenue_vat": 6378,
    "revenue": 5271.08
  },
  {
    "date": "2026-03-05",
    "orders": 3,
    "revenue_vat": 11556,
    "revenue": 9550.43
  },
  {
    "date": "2026-03-06",
    "orders": 5,
    "revenue_vat": 12273,
    "revenue": 10142.99
  },
  {
    "date": "2026-03-09",
    "orders": 2,
    "revenue_vat": 5365,
    "revenue": 4433.88
  },
  {
    "date": "2026-03-11",
    "orders": 7,
    "revenue_vat": 13396,
    "revenue": 11071.09
  },
  {
    "date": "2026-03-13",
    "orders": 4,
    "revenue_vat": 10170,
    "revenue": 8404.96
  },
  {
    "date": "2026-03-16",
    "orders": 3,
    "revenue_vat": 9615,
    "revenue": 7946.29
  },
  {
    "date": "2026-03-17",
    "orders": 4,
    "revenue_vat": 7050,
    "revenue": 5826.46
  },
  {
    "date": "2026-03-18",
    "orders": 2,
    "revenue_vat": 3891,
    "revenue": 3215.71
  },
  {
    "date": "2026-03-19",
    "orders": 2,
    "revenue_vat": 9057,
    "revenue": 7485.13
  },
  {
    "date": "2026-03-20",
    "orders": 3,
    "revenue_vat": 8297,
    "revenue": 6857.03
  },
  {
    "date": "2026-03-23",
    "orders": 4,
    "revenue_vat": 7058,
    "revenue": 5833.06
  },
  {
    "date": "2026-03-24",
    "orders": 1,
    "revenue_vat": 3320,
    "revenue": 2700.41
  },
  {
    "date": "2026-03-25",
    "orders": 2,
    "revenue_vat": 5780,
    "revenue": 4776.86
  },
  {
    "date": "2026-03-26",
    "orders": 5,
    "revenue_vat": 11179,
    "revenue": 9238.84
  },
  {
    "date": "2026-03-27",
    "orders": 2,
    "revenue_vat": 4504,
    "revenue": 3722.32
  },
  {
    "date": "2026-03-30",
    "orders": 2,
    "revenue_vat": 5737,
    "revenue": 4708.18
  },
  {
    "date": "2026-03-31",
    "orders": 1,
    "revenue_vat": 3592,
    "revenue": 2968.6
  },
  {
    "date": "2026-04-07",
    "orders": 3,
    "revenue_vat": 5550,
    "revenue": 4586.78
  },
  {
    "date": "2026-04-08",
    "orders": 3,
    "revenue_vat": 7460,
    "revenue": 6165.3
  },
  {
    "date": "2026-04-10",
    "orders": 2,
    "revenue_vat": 6081,
    "revenue": 5025.62
  },
  {
    "date": "2026-04-14",
    "orders": 3,
    "revenue_vat": 9324,
    "revenue": 7705.8
  },
  {
    "date": "2026-04-15",
    "orders": 2,
    "revenue_vat": 5723,
    "revenue": 4729.76
  },
  {
    "date": "2026-04-16",
    "orders": 2,
    "revenue_vat": 3672,
    "revenue": 3034.71
  },
  {
    "date": "2026-04-17",
    "orders": 2,
    "revenue_vat": 5652,
    "revenue": 4671.08
  },
  {
    "date": "2026-04-18",
    "orders": 1,
    "revenue_vat": 2511,
    "revenue": 2075.21
  },
  {
    "date": "2026-04-20",
    "orders": 3,
    "revenue_vat": 6100,
    "revenue": 5041.33
  },
  {
    "date": "2026-04-22",
    "orders": 2,
    "revenue_vat": 10570,
    "revenue": 8735.54
  },
  {
    "date": "2026-04-23",
    "orders": 3,
    "revenue_vat": 4531,
    "revenue": 3744.63
  },
  {
    "date": "2026-04-24",
    "orders": 1,
    "revenue_vat": 1796,
    "revenue": 1484.3
  },
  {
    "date": "2026-04-29",
    "orders": 2,
    "revenue_vat": 5265,
    "revenue": 4351.24
  },
  {
    "date": "2026-04-30",
    "orders": 3,
    "revenue_vat": 8564,
    "revenue": 7077.7
  },
  {
    "date": "2026-05-05",
    "orders": 1,
    "revenue_vat": 4039,
    "revenue": 3338.02
  },
  {
    "date": "2026-05-06",
    "orders": 2,
    "revenue_vat": 7271,
    "revenue": 6009.1
  },
  {
    "date": "2026-05-07",
    "orders": 2,
    "revenue_vat": 5553,
    "revenue": 4589.26
  },
  {
    "date": "2026-05-09",
    "orders": 1,
    "revenue_vat": 1790,
    "revenue": 1479.34
  },
  {
    "date": "2026-05-12",
    "orders": 3,
    "revenue_vat": 8665,
    "revenue": 7161.17
  },
  {
    "date": "2026-05-13",
    "orders": 2,
    "revenue_vat": 3643,
    "revenue": 3010.75
  },
  {
    "date": "2026-05-14",
    "orders": 2,
    "revenue_vat": 5291,
    "revenue": 4372.73
  },
  {
    "date": "2026-05-15",
    "orders": 1,
    "revenue_vat": 2231,
    "revenue": 1843.81
  },
  {
    "date": "2026-05-18",
    "orders": 1,
    "revenue_vat": 2468,
    "revenue": 2039.67
  },
  {
    "date": "2026-05-19",
    "orders": 4,
    "revenue_vat": 7516,
    "revenue": 6211.58
  },
  {
    "date": "2026-05-20",
    "orders": 5,
    "revenue_vat": 15173,
    "revenue": 12346.34
  },
  {
    "date": "2026-05-21",
    "orders": 1,
    "revenue_vat": 5922,
    "revenue": 4894.22
  },
  {
    "date": "2026-05-22",
    "orders": 3,
    "revenue_vat": 7984,
    "revenue": 6424.79
  },
  {
    "date": "2026-05-26",
    "orders": 5,
    "revenue_vat": 9394,
    "revenue": 7763.63
  },
  {
    "date": "2026-05-27",
    "orders": 6,
    "revenue_vat": 16976,
    "revenue": 13735.06
  },
  {
    "date": "2026-05-29",
    "orders": 4,
    "revenue_vat": 9197,
    "revenue": 7394.3
  },
  {
    "date": "2026-06-01",
    "orders": 2,
    "revenue_vat": 5075,
    "revenue": 4194.21
  },
  {
    "date": "2026-06-02",
    "orders": 3,
    "revenue_vat": 7898,
    "revenue": 6458.03
  },
  {
    "date": "2026-06-03",
    "orders": 1,
    "revenue_vat": 2880,
    "revenue": 2293.39
  },
  {
    "date": "2026-06-04",
    "orders": 3,
    "revenue_vat": 8560,
    "revenue": 6917.84
  },
  {
    "date": "2026-06-05",
    "orders": 7,
    "revenue_vat": 12655,
    "revenue": 10458.7
  },
  {
    "date": "2026-06-09",
    "orders": 1,
    "revenue_vat": 4814,
    "revenue": 3978.52
  },
  {
    "date": "2026-06-10",
    "orders": 3,
    "revenue_vat": 7286,
    "revenue": 6021.5
  },
  {
    "date": "2026-06-11",
    "orders": 3,
    "revenue_vat": 6641,
    "revenue": 5488.44
  },
  {
    "date": "2026-06-12",
    "orders": 1,
    "revenue_vat": 1891,
    "revenue": 1562.81
  },
  {
    "date": "2026-06-15",
    "orders": 5,
    "revenue_vat": 14235,
    "revenue": 11764.47
  },
  {
    "date": "2026-06-16",
    "orders": 2,
    "revenue_vat": 3180,
    "revenue": 2471.91
  },
  {
    "date": "2026-06-17",
    "orders": 2,
    "revenue_vat": 4088,
    "revenue": 3378.52
  },
  {
    "date": "2026-06-18",
    "orders": 2,
    "revenue_vat": 5740,
    "revenue": 4743.81
  },
  {
    "date": "2026-06-19",
    "orders": 7,
    "revenue_vat": 23756,
    "revenue": 19633.07
  },
  {
    "date": "2026-06-23",
    "orders": 5,
    "revenue_vat": 9904,
    "revenue": 8185.14
  },
  {
    "date": "2026-06-24",
    "orders": 2,
    "revenue_vat": 3950,
    "revenue": 3264.47
  },
  {
    "date": "2026-06-25",
    "orders": 1,
    "revenue_vat": 1790,
    "revenue": 1479.34
  },
  {
    "date": "2026-06-26",
    "orders": 2,
    "revenue_vat": 3139,
    "revenue": 2594.22
  },
  {
    "date": "2026-07-01",
    "orders": 1,
    "revenue_vat": 1759,
    "revenue": 1377.36
  },
  {
    "date": "2026-07-02",
    "orders": 1,
    "revenue_vat": 3321,
    "revenue": 2744.63
  },
  {
    "date": "2026-07-03",
    "orders": 2,
    "revenue_vat": 6102,
    "revenue": 4982.41
  },
  {
    "date": "2026-07-07",
    "orders": 1,
    "revenue_vat": 1796,
    "revenue": 1484.3
  },
  {
    "date": "2026-07-15",
    "orders": 1,
    "revenue_vat": 1900,
    "revenue": 1518.36
  },
  {
    "date": "2026-07-16",
    "orders": 1,
    "revenue_vat": 2176,
    "revenue": 1798.35
  },
  {
    "date": "2026-07-17",
    "orders": 2,
    "revenue_vat": 3280,
    "revenue": 2381
  },
  {
    "date": "2026-07-20",
    "orders": 2,
    "revenue_vat": -1494,
    "revenue": -1234.71
  },
  {
    "date": "2026-07-21",
    "orders": 1,
    "revenue_vat": 2961,
    "revenue": 2447.11
  },
  {
    "date": "2026-07-22",
    "orders": 1,
    "revenue_vat": 2190,
    "revenue": 1757.85
  },
  {
    "date": "2026-07-28",
    "orders": 4,
    "revenue_vat": 7801,
    "revenue": 6439.99
  },
  {
    "date": "2026-07-29",
    "orders": 1,
    "revenue_vat": 1490,
    "revenue": 1147.93
  },
  {
    "date": "2026-07-30",
    "orders": 1,
    "revenue_vat": 990,
    "revenue": 788.5
  },
  {
    "date": "2026-07-31",
    "orders": 4,
    "revenue_vat": 11200,
    "revenue": 9256.2
  },
  {
    "date": "2026-08-04",
    "orders": 2,
    "revenue_vat": 4680,
    "revenue": 3702.72
  }
];
